import { SliceDefinition, SliceType } from '../types/ucp';

export const SLICE_DEFINITIONS: Record<SliceType, SliceDefinition> = {
  HEADER_NAV: {
    type: 'HEADER_NAV',
    label: 'Header Navigation',
    category: 'navigation',
    icon: '🔝',
    description: 'Top bar with search, notification bell, QR scanner',
    configurable: ['title', 'searchPlaceholder', 'showNotificationBell', 'showQRScanner'],
    minHeight: 60,
    singleton: true,
  },
  QUICK_ACCESS: {
    type: 'QUICK_ACCESS',
    label: 'Quick Access Buttons',
    category: 'function',
    icon: '⚡',
    description: 'Row of primary product shortcuts (e.g. 朝朝宝, 借钱, 转账)',
    configurable: ['items'],
    minHeight: 80,
    singleton: true,
  },
  PROMO_BANNER: {
    type: 'PROMO_BANNER',
    label: 'Promo Banner',
    category: 'promotion',
    icon: '🎪',
    description: 'Full-width campaign banner with image, title, CTA',
    configurable: ['title', 'subtitle', 'ctaLabel', 'ctaDeepLink', 'imageUrl', 'backgroundColor', 'badgeText'],
    minHeight: 120,
  },
  FUNCTION_GRID: {
    type: 'FUNCTION_GRID',
    label: 'Function Grid',
    category: 'function',
    icon: '🔲',
    description: 'Icon grid of banking functions (credit card, transfers, etc.)',
    configurable: ['rows'],
    minHeight: 140,
    singleton: true,
  },
  AI_ASSISTANT: {
    type: 'AI_ASSISTANT',
    label: 'AI Assistant Entry',
    category: 'function',
    icon: '🤖',
    description: 'Intelligent wealth assistant greeting bar',
    configurable: ['greeting'],
    minHeight: 44,
  },
  AD_BANNER: {
    type: 'AD_BANNER',
    label: 'Advertisement Banner',
    category: 'promotion',
    icon: '📢',
    description: 'Dismissible promotional banner with image swap support',
    configurable: ['title', 'subtitle', 'ctaLabel', 'ctaDeepLink', 'imageUrl', 'dismissible', 'validUntil'],
    minHeight: 90,
  },
  FLASH_LOAN: {
    type: 'FLASH_LOAN',
    label: 'Flash Loan Card',
    category: 'wealth',
    icon: '⚡💳',
    description: 'Instant loan product card with maximum amount display',
    configurable: ['productName', 'tagline', 'maxAmount', 'currency', 'ctaLabel', 'ctaDeepLink'],
    minHeight: 80,
  },
  WEALTH_SELECTION: {
    type: 'WEALTH_SELECTION',
    label: 'Wealth Selection',
    category: 'wealth',
    icon: '💰',
    description: 'Featured wealth products (7-day yield, risk level)',
    configurable: ['sectionTitle', 'products', 'moreDeepLink'],
    minHeight: 280,
  },
  FEATURED_RANKINGS: {
    type: 'FEATURED_RANKINGS',
    label: 'Featured Rankings',
    category: 'wealth',
    icon: '🏆',
    description: 'Top-performing funds and product rankings',
    configurable: ['sectionTitle', 'items', 'moreDeepLink'],
    minHeight: 180,
  },
  LIFE_DEALS: {
    type: 'LIFE_DEALS',
    label: 'Life Deals',
    category: 'lifestyle',
    icon: '🛍️',
    description: 'Lifestyle merchant offers (KFC, Luckin, DQ…)',
    configurable: ['sectionTitle', 'deals', 'moreDeepLink', 'bottomLinks'],
    minHeight: 200,
  },
  SPACER: {
    type: 'SPACER',
    label: 'Spacer',
    category: 'layout',
    icon: '↕️',
    description: 'Vertical spacing element',
    configurable: ['height'],
    minHeight: 16,
  },
  MARKET_BRIEFING_TEXT: {
    type: 'MARKET_BRIEFING_TEXT',
    label: 'Market Briefing Text',
    category: 'insight',
    icon: '📋',
    description: 'Bullet-point market briefing sourced from a UCP content entry',
    configurable: ['ucpContentId', 'sectionTitle', 'bulletPoints', 'disclaimer'],
    minHeight: 200,
  },
  VIDEO_PLAYER: {
    type: 'VIDEO_PLAYER',
    label: 'Video Player',
    category: 'insight',
    icon: '🎬',
    description: 'Inline video player linked to a UCP content asset (video)',
    configurable: ['ucpAssetId', 'title', 'presenterName', 'presenterTitle', 'autoplay', 'showCaption'],
    minHeight: 180,
  },
  CONTACT_RM_CTA: {
    type: 'CONTACT_RM_CTA',
    label: 'Contact Your RM',
    category: 'insight',
    icon: '📞',
    description: 'Sticky CTA routing customer to Relationship Manager finder',
    configurable: ['label', 'subLabel', 'deepLink', 'backgroundColor', 'textColor', 'sticky'],
    minHeight: 56,
    singleton: true,
  },
  DEPOSIT_RATE_TABLE: {
    type: 'DEPOSIT_RATE_TABLE',
    label: 'Deposit Rate Table',
    category: 'wealth',
    icon: '🏦',
    description: 'Time deposit interest rate table — term and rate columns only',
    configurable: ['sectionTitle', 'asAtDate', 'rates', 'footnote'],
    minHeight: 220,
  },
  DEPOSIT_OPEN_CTA: {
    type: 'DEPOSIT_OPEN_CTA',
    label: 'Button CTA',
    category: 'wealth',
    icon: '🏧',
    description: 'Full-width "Open a Deposit" CTA button for deposit campaigns',
    configurable: ['label', 'deepLink', 'backgroundColor', 'textColor'],
    minHeight: 56,
  },
  DEPOSIT_FAQ: {
    type: 'DEPOSIT_FAQ',
    label: 'General FAQ',
    category: 'wealth',
    icon: '❓',
    description: 'Collapsible FAQ accordion for deposit products — question/answer pairs',
    configurable: ['sectionTitle', 'items'],
    minHeight: 200,
  },
};

export const SLICE_CATEGORIES: { id: string; label: string; icon: string }[] = [
  { id: 'navigation', label: 'Navigation',  icon: '🔝' },
  { id: 'promotion',  label: 'Promotions',  icon: '🎪' },
  { id: 'function',   label: 'Functions',   icon: '⚡' },
  { id: 'wealth',     label: 'Wealth',      icon: '💰' },
  { id: 'lifestyle',  label: 'Lifestyle',   icon: '🛍️' },
  { id: 'layout',     label: 'Layout',      icon: '📐' },
  { id: 'insight',    label: 'Insight',     icon: '📈' },
];
