import {
  PageLayout, WorkflowEntry, AuditEntry, StaffUser,
  Market, ReleaseTarget, BizLine, AdGroup, ApprovalFlow,
  WeChatServiceAccount, WeChatMessageTemplate,
  PageMarketStatus, PageSubmission, PageApprovalInstance,
  AEOScore, PageUsageStat, ServiceAccountMessage,
  ContentAsset, UIComponent,
} from '../types/ucp';
import { v4 } from '../utils/uuid';

// ─── Reference data ───────────────────────────────────────────────────────────

export const MARKETS: Market[] = [
  { marketId: 'GLOBAL', marketName: 'Global (.com)',              active: true,  timezone: 'UTC',              tzLabel: 'UTC (UTC+0)' },
  { marketId: 'HK',     marketName: 'Hong Kong (.com.hk)',        active: true,  timezone: 'Asia/Hong_Kong',   tzLabel: 'HKT (UTC+8)' },
  { marketId: 'SG',     marketName: 'Singapore (.com.sg)',        active: true,  timezone: 'Asia/Singapore',   tzLabel: 'SGT (UTC+8)' },
  { marketId: 'UK',     marketName: 'United Kingdom (.co.uk)',    active: true,  timezone: 'Europe/London',    tzLabel: 'BST/GMT (UTC+0/+1)' },
  { marketId: 'IN',     marketName: 'India (bank.in)',            active: true,  timezone: 'Asia/Kolkata',     tzLabel: 'IST (UTC+5:30)' },
  { marketId: 'CN',     marketName: 'China (WeChat)',             active: true,  timezone: 'Asia/Shanghai',    tzLabel: 'CST (UTC+8)' },
  { marketId: 'MC',     marketName: 'Mainland China (hsbc.cn)',   active: true,  timezone: 'Asia/Shanghai',    tzLabel: 'CST (UTC+8)' },
];

export const RELEASE_TARGETS: ReleaseTarget[] = [
  { targetId: 'GLOBAL', displayName: 'Global (.com)',           domainSuffix: '.com',      isGlobal: true,  active: true },
  { targetId: 'HK',     displayName: 'Hong Kong (.com.hk)',     domainSuffix: '.com.hk',   isGlobal: false, active: true },
  { targetId: 'SG',     displayName: 'Singapore (.com.sg)',     domainSuffix: '.com.sg',   isGlobal: false, active: true },
  { targetId: 'UK',     displayName: 'United Kingdom (.co.uk)', domainSuffix: '.co.uk',    isGlobal: false, active: true },
  { targetId: 'IN',     displayName: 'India (bank.in)',         domainSuffix: 'bank.in',   isGlobal: false, active: true },
];

export const BIZ_LINES: BizLine[] = [
  { bizLineId: 'PAYMENT',     displayName: 'Payment & Cards',    description: 'Credit card, transaction pages',        active: true },
  { bizLineId: 'WEB_ENABLER', displayName: 'Web Enablement',     description: 'Core web infrastructure, navigation',   active: true },
  { bizLineId: 'LENDING',     displayName: 'Lending & Mortgage', description: 'Loan, mortgage, overdraft pages',        active: true },
  { bizLineId: 'COLLECTION',  displayName: 'Collections',        description: 'Debt management, repayment pages',       active: true },
  { bizLineId: 'WEALTH',      displayName: 'Wealth & Investments', description: 'Premier, Jade, investment pages',     active: true },
  { bizLineId: 'MARKETING',   displayName: 'Marketing & Campaigns', description: 'Campaign pages, promotional banners', active: true },
];

export const AD_GROUPS: AdGroup[] = [
  { groupId: 'HK-WEALTH-AD',    groupName: 'HK Wealth AD Group',    marketId: 'HK',     bizLineId: 'WEALTH',   groupType: 'AD_GROUP' },
  { groupId: 'HK-PAYMENT-AD',   groupName: 'HK Payment AD Group',   marketId: 'HK',     bizLineId: 'PAYMENT',  groupType: 'AD_GROUP' },
  { groupId: 'HK-MARKETING-AD', groupName: 'HK Marketing AD Group', marketId: 'HK',     bizLineId: 'MARKETING', groupType: 'AD_GROUP' },
  { groupId: 'SG-WEALTH-AD',    groupName: 'SG Wealth AD Group',    marketId: 'SG',     bizLineId: 'WEALTH',   groupType: 'AD_GROUP' },
  { groupId: 'GLOBAL-WEALTH-AD', groupName: 'Global Wealth AD Group', marketId: 'GLOBAL', bizLineId: 'WEALTH', groupType: 'AD_GROUP' },
  { groupId: 'HK-ADMIN-GRP',    groupName: 'HK Admin Group',        marketId: 'HK',     bizLineId: 'WEALTH',   groupType: 'ADMIN_GROUP' },
  { groupId: 'GLOBAL-ADMIN-GRP', groupName: 'Global Admin Group',   marketId: 'GLOBAL', bizLineId: 'WEALTH',   groupType: 'ADMIN_GROUP' },
  { groupId: 'HK-AUDIT-GRP',    groupName: 'HK Audit Group',        marketId: 'HK',     bizLineId: 'WEALTH',   groupType: 'AUDIT_GROUP' },
];

export const APPROVAL_FLOWS: ApprovalFlow[] = [
  {
    flowId: 'flow-hk-1step',
    flowName: 'HK Standard 1-Step',
    marketId: 'HK',
    bizLineId: null,
    minApprovers: 1,
    samePersionRestriction: false,
    steps: [{ stepOrder: 1, approverGroupId: 'HK-WEALTH-AD', approverGroupName: 'HK Wealth AD Group' }],
  },
  {
    flowId: 'flow-hk-2step',
    flowName: 'HK Dual Approval',
    marketId: 'HK',
    bizLineId: null,
    minApprovers: 2,
    samePersionRestriction: true,
    steps: [
      { stepOrder: 1, approverGroupId: 'HK-WEALTH-AD', approverGroupName: 'HK Wealth AD Group' },
      { stepOrder: 2, approverGroupId: 'HK-WEALTH-AD', approverGroupName: 'HK Wealth AD Group' },
    ],
  },
  {
    flowId: 'flow-sg-1step',
    flowName: 'SG Standard',
    marketId: 'SG',
    bizLineId: null,
    minApprovers: 1,
    samePersionRestriction: false,
    steps: [{ stepOrder: 1, approverGroupId: 'SG-WEALTH-AD', approverGroupName: 'SG Wealth AD Group' }],
  },
  {
    flowId: 'flow-global-1step',
    flowName: 'Global Standard',
    marketId: 'GLOBAL',
    bizLineId: null,
    minApprovers: 1,
    samePersionRestriction: false,
    steps: [{ stepOrder: 1, approverGroupId: 'GLOBAL-WEALTH-AD', approverGroupName: 'Global Wealth AD Group' }],
  },
];

// ─── WeChat Service Accounts ──────────────────────────────────────────────────

export const WECHAT_ACCOUNTS: WeChatServiceAccount[] = [
  {
    accountId: 'wxa-hk-wealth',
    displayName: 'HSBC HK Wealth SA',
    wechatName: '汇丰財富',
    appid: 'wx_hk_wealth_001',
    accountType: 'SERVICE_ACCOUNT',
    verified: true,
    followerCount: 320000,
    primaryMarketId: 'HK',
    scope: 'MARKET',
    active: true,
    assignedMarkets: [{ marketId: 'HK', marketName: 'Hong Kong', isDefault: true }],
  },
  {
    accountId: 'wxa-hk-retail',
    displayName: 'HSBC HK Retail SA',
    wechatName: '汇丰銀行HK',
    appid: 'wx_hk_retail_002',
    accountType: 'SERVICE_ACCOUNT',
    verified: true,
    followerCount: 920000,
    primaryMarketId: 'HK',
    scope: 'MARKET',
    active: true,
    assignedMarkets: [{ marketId: 'HK', marketName: 'Hong Kong', isDefault: false }],
  },
  {
    accountId: 'wxa-cn-official',
    displayName: 'HSBC CN Official SA',
    wechatName: '汇丰银行',
    appid: 'wx_cn_official_003',
    accountType: 'SERVICE_ACCOUNT',
    verified: true,
    followerCount: 2400000,
    primaryMarketId: 'CN',
    scope: 'MARKET',
    active: true,
    assignedMarkets: [{ marketId: 'CN', marketName: 'China', isDefault: true }],
  },
];

export const WECHAT_TEMPLATES: WeChatMessageTemplate[] = [
  {
    templateId: 'tpl-promo-invite',
    accountId: 'wxa-hk-wealth',
    wechatTemplateId: 'T_0000001234',
    templateName: 'HSBC Promo Invitation v2',
    fields: [
      { key: 'title',  label: '標題',    type: 'text' },
      { key: 'amount', label: '申請資格', type: 'text' },
      { key: 'date',   label: '截止日期', type: 'date' },
      { key: 'remark', label: '備註',    type: 'text' },
    ],
    bizLineScope: ['WEALTH'],
    active: true,
  },
  {
    templateId: 'tpl-rate-alert',
    accountId: 'wxa-hk-wealth',
    wechatTemplateId: 'T_0000001235',
    templateName: 'HSBC Rate Alert',
    fields: [
      { key: 'product', label: '產品',   type: 'text' },
      { key: 'rate',    label: '最新利率', type: 'text' },
      { key: 'date',    label: '生效日期', type: 'date' },
    ],
    bizLineScope: null,
    active: true,
  },
];

// ─── Mock pages ───────────────────────────────────────────────────────────────

export const DEFAULT_PAGE_LAYOUT: PageLayout = {
  pageId: 'home-wealth-hk',
  name: 'Home – Wealth Hub (HK)',
  pageType: 'WEALTH_HUB',
  description: 'Main wealth hub home page for HK market',
  platform: 'all',
  locale: 'zh-HK',
  thumbnail: '💰',
  tags: ['wealth', 'home', 'hk'],
  channel: 'SDUI',
  scope: 'MARKET',
  marketId: 'HK',
  releaseMarketIds: ['HK'],
  bizLineId: 'WEALTH',
  groupId: 'HK-WEALTH-AD',
  authoringStatus: 'APPROVED',
  slices: [
    {
      instanceId: 'slice-header',
      type: 'HEADER_NAV',
      props: { title: '定期存款', searchPlaceholder: '搜尋功能、產品', showNotificationBell: true, showQRScanner: true },
      visible: true, locked: false,
    },
    {
      instanceId: 'slice-quick',
      type: 'QUICK_ACCESS',
      props: {
        items: [
          { id: 'q1', icon: '🌙', label: '朝朝寶',   deepLink: 'hsbc://wealth/morning-treasure' },
          { id: 'q2', icon: '💵', label: '借錢',     deepLink: 'hsbc://loan/apply' },
          { id: 'q3', icon: '↔️', label: '轉帳',     deepLink: 'hsbc://transfer' },
          { id: 'q4', icon: '📊', label: '賬戶總覽', deepLink: 'hsbc://accounts' },
        ],
      },
      visible: true, locked: false,
    },
    {
      instanceId: 'slice-promo-10',
      type: 'PROMO_BANNER',
      props: { title: '10分招財日', subtitle: '查帳單·學投資·優配置', ctaLabel: '點擊參與', ctaDeepLink: 'hsbc://campaign/finance-day', imageUrl: '', backgroundColor: '#E8F4FD', badgeText: '每月10日開啓' },
      visible: true, locked: false,
    },
    {
      instanceId: 'slice-wealth-sel',
      type: 'WEALTH_SELECTION',
      props: {
        sectionTitle: '財富精選',
        products: [
          { id: 'w1', productName: '活錢理財｜歷史天天正收益', tag: '代碼', yield7Day: '2.80%', riskLevel: 'R1低風險', redemption: '贖回T+1到帳', ctaLabel: '去看看', ctaDeepLink: 'hsbc://wealth/daily-positive', highlighted: true },
          { id: 'w2', productName: '主投債券', tag: '代碼', yield7Day: '3.04%', riskLevel: '歷史周周正', redemption: '成立以來…', ctaLabel: '查看', ctaDeepLink: 'hsbc://wealth/bond-fund' },
        ],
        moreDeepLink: 'hsbc://wealth/all',
      },
      visible: true, locked: false,
    },
    {
      instanceId: 'slice-ai',
      type: 'AI_ASSISTANT',
      props: { greeting: 'Hi，我是你的智能財富助理', avatarUrl: '' },
      visible: true, locked: false,
    },
  ],
};

export const JADE_CAMPAIGN_PAGE: PageLayout = {
  pageId: 'jade-upgrade-hk',
  name: 'Jade Upgrade Campaign (HK)',
  pageType: 'CAMPAIGN',
  description: 'Jade upgrade invitation page for Premier customers',
  platform: 'all',
  locale: 'zh-HK',
  thumbnail: '🟡',
  tags: ['jade', 'wealth', 'campaign'],
  channel: 'WEB_WECHAT',
  scope: 'MARKET',
  marketId: 'HK',
  releaseMarketIds: ['HK'],
  bizLineId: 'WEALTH',
  groupId: 'HK-WEALTH-AD',
  authoringStatus: 'APPROVED',
  wechatPageUrl: 'https://wechat.hsbc.com.hk/pages/jade-upgrade',
  wechatShareTitle: '您的HSBC Jade升級邀請',
  wechatShareDesc: '立即了解專屬優惠，限時申請',
  slices: [
    {
      instanceId: 'jade-hero',
      type: 'PROMO_BANNER',
      props: { title: 'HSBC Jade 升級邀請', subtitle: '專為Premier客戶而設的尊貴服務', ctaLabel: '立即申請', ctaDeepLink: 'hsbc://jade/apply', imageUrl: '', backgroundColor: '#1D1D1B', badgeText: '尊屬優惠' },
      visible: true, locked: false,
    },
    {
      instanceId: 'jade-wealth',
      type: 'WEALTH_SELECTION',
      props: { sectionTitle: 'Jade 專屬產品', products: [], moreDeepLink: 'hsbc://jade/all' },
      visible: true, locked: false,
    },
  ],
};

export const VISA_CAMPAIGN_PAGE: PageLayout = {
  pageId: 'visa-platinum-campaign',
  name: 'Visa Platinum Q3 Campaign',
  pageType: 'CAMPAIGN',
  description: 'Visa Platinum no-FX campaign for Q3 2026',
  platform: 'web',
  locale: 'en-HK',
  thumbnail: '💳',
  tags: ['cards', 'campaign', 'visa'],
  channel: 'WEB_STANDARD',
  scope: 'GLOBAL',
  marketId: 'GLOBAL',
  releaseMarketIds: ['GLOBAL', 'HK', 'SG'],
  bizLineId: 'PAYMENT',
  groupId: 'GLOBAL-WEALTH-AD',
  authoringStatus: 'DRAFT',
  webSlug: '/credit-cards/visa-platinum-q3',
  webMetaTitle: 'HSBC Visa Platinum – No FX Fee | HSBC',
  webMetaDescription: 'Apply for HSBC Visa Platinum with no foreign transaction fee. Earn rewards globally.',
  webLayoutTemplate: 'CAMPAIGN',
  lastReviewedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 38).toISOString(),
  authorCredentials: 'HSBC Cards Product Team – Licensed by HKMA',
  slices: [],
};

export const OBKYC_PAGE_LAYOUT: PageLayout = {
  pageId: 'obkyc-journey',
  name: 'OBKYC – Account Opening Journey',
  pageType: 'KYC_JOURNEY',
  description: 'Open Banking KYC journey — 10-step mobile flow',
  platform: 'all',
  locale: 'en-HK',
  thumbnail: '🪪',
  tags: ['kyc', 'onboarding'],
  channel: 'SDUI',
  scope: 'MARKET',
  marketId: 'HK',
  releaseMarketIds: ['HK'],
  bizLineId: 'WEB_ENABLER',
  groupId: 'HK-WEALTH-AD',
  authoringStatus: 'DRAFT',
  slices: [
    {
      instanceId: 'kyc-header',
      type: 'HEADER_NAV',
      props: { title: 'Account Opening', searchPlaceholder: 'Search', showNotificationBell: false, showQRScanner: false },
      visible: true, locked: true,
    },
    {
      instanceId: 'kyc-promo',
      type: 'PROMO_BANNER',
      props: { title: 'Open Banking Account Opening', subtitle: 'Complete your KYC in minutes. Regulated by HKMA.', ctaLabel: 'Begin Application', ctaDeepLink: 'hsbc://kyc/start', imageUrl: '', backgroundColor: '#E8F0FE', badgeText: 'HKMA Regulated' },
      visible: true, locked: false,
    },
  ],
};

export const ALL_PAGES: PageLayout[] = [
  DEFAULT_PAGE_LAYOUT,
  JADE_CAMPAIGN_PAGE,
  VISA_CAMPAIGN_PAGE,
  OBKYC_PAGE_LAYOUT,
];

// ─── Mock workflow entries ────────────────────────────────────────────────────

export const MOCK_WORKFLOW_ENTRIES: WorkflowEntry[] = [
  {
    entryId: 'wf-001',
    pageId: 'home-wealth-hk',
    pageName: 'Home – Wealth Hub (HK)',
    status: 'LIVE',
    authorId: 'j.chan@hsbc.com.hk',
    authorName: 'Janet Chan',
    comments: [],
    layout: DEFAULT_PAGE_LAYOUT,
    version: 3,
  },
  {
    entryId: 'wf-002',
    pageId: 'jade-upgrade-hk',
    pageName: 'Jade Upgrade Campaign (HK)',
    status: 'LIVE',
    authorId: 'j.chan@hsbc.com.hk',
    authorName: 'Janet Chan',
    comments: [],
    layout: JADE_CAMPAIGN_PAGE,
    version: 2,
  },
  {
    entryId: 'wf-003',
    pageId: 'visa-platinum-campaign',
    pageName: 'Visa Platinum Q3 Campaign',
    status: 'DRAFT',
    authorId: 'j.chan@hsbc.com.hk',
    authorName: 'Janet Chan',
    comments: [],
    layout: VISA_CAMPAIGN_PAGE,
    version: 1,
  },
  {
    entryId: 'wf-004',
    pageId: 'obkyc-journey',
    pageName: 'OBKYC – Account Opening Journey',
    status: 'DRAFT',
    authorId: 'k.lee@hsbc.com.hk',
    authorName: 'Karen Lee',
    comments: [],
    layout: OBKYC_PAGE_LAYOUT,
    version: 1,
  },
];

// ─── Mock market production status ────────────────────────────────────────────

export const MOCK_MARKET_STATUS: PageMarketStatus[] = [
  { statusId: 'pms-001', pageId: 'home-wealth-hk',        releaseTargetId: 'HK',     domainSuffix: '.com.hk',  productionStatus: 'LIVE',           liveSince: '2026-03-12', version: 3 },
  { statusId: 'pms-002', pageId: 'jade-upgrade-hk',       releaseTargetId: 'HK',     domainSuffix: 'wechat.hsbc.com.hk', productionStatus: 'LIVE', liveSince: '2026-03-15', version: 2 },
  { statusId: 'pms-003', pageId: 'visa-platinum-campaign', releaseTargetId: 'GLOBAL', domainSuffix: '.com',     productionStatus: 'LIVE',           liveSince: '2026-03-10', version: 2 },
  { statusId: 'pms-004', pageId: 'visa-platinum-campaign', releaseTargetId: 'HK',     domainSuffix: '.com.hk',  productionStatus: 'LIVE',           liveSince: '2026-03-12', version: 2 },
  { statusId: 'pms-005', pageId: 'visa-platinum-campaign', releaseTargetId: 'SG',     domainSuffix: '.com.sg',  productionStatus: 'NEVER_RELEASED', version: undefined },
];

// ─── Mock approval submissions ────────────────────────────────────────────────

export const MOCK_SUBMISSIONS: PageSubmission[] = [
  {
    submissionId: 'sub-001',
    pageId: 'visa-platinum-campaign',
    pageVersion: 3,
    submittedBy: 'j.chan@hsbc.com.hk',
    submittedByName: 'Janet Chan',
    submittedAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    releaseTargets: ['IN'],
    instances: [
      {
        instanceId: 'inst-001',
        submissionId: 'sub-001',
        pageId: 'visa-platinum-campaign',
        releaseTargetId: 'IN',
        releaseTargetName: 'India (bank.in)',
        domainSuffix: 'bank.in',
        approvalFlowId: 'flow-hk-1step',
        overallStatus: 'PENDING',
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
        steps: [
          {
            stepId: 'step-001',
            stepOrder: 1,
            requiredGroupId: 'HK-WEALTH-AD',
            requiredGroupName: 'HK Wealth AD Group',
            status: 'PENDING',
          },
        ],
      },
    ],
  },
];

// ─── Mock AEO Scores ──────────────────────────────────────────────────────────

export const MOCK_AEO_SCORES: AEOScore[] = [
  {
    scoreId: 'aeo-001',
    pageId: 'visa-platinum-campaign',
    releaseTargetId: 'GLOBAL',
    pageVersion: 2,
    scoredAt: new Date(Date.now() - 86400000).toISOString(),
    trigger: 'DAP_SYNC',
    faqSchemaPts: 20,   faqSchemaNote: undefined,
    productSchemaPts: 20,
    freshnessPts: 15,
    authorCredPts: 10,
    regulatoryRefPts: 10,
    structuredRatePts: 10,
    directAnswerPts: 10,
    staticScore: 95,
    llmCitationPts: 5,  llmCitationNote: 'Cited by ChatGPT and Perplexity',
    totalScore: 88,
    aeoGrade: 'A',
  },
  {
    scoreId: 'aeo-002',
    pageId: 'visa-platinum-campaign',
    releaseTargetId: 'HK',
    pageVersion: 2,
    scoredAt: new Date(Date.now() - 86400000).toISOString(),
    trigger: 'DAP_SYNC',
    faqSchemaPts: 20,
    productSchemaPts: 20,
    freshnessPts: 0,    freshnessNote: 'Last reviewed 38 days ago (threshold: 30 days)',
    authorCredPts: 10,
    regulatoryRefPts: 10,
    structuredRatePts: 0, structuredRateNote: 'Rate embedded in image — move to structured field',
    directAnswerPts: 10,
    staticScore: 70,
    llmCitationPts: 5,  llmCitationNote: 'Cited by ChatGPT',
    totalScore: 74,
    aeoGrade: 'B',
  },
  {
    scoreId: 'aeo-003',
    pageId: 'visa-platinum-campaign',
    releaseTargetId: 'IN',
    pageVersion: 3,
    scoredAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    trigger: 'ON_SUBMIT',
    faqSchemaPts: 20,
    productSchemaPts: 20,
    freshnessPts: 0,    freshnessNote: 'Last reviewed 38 days ago',
    authorCredPts: 10,
    regulatoryRefPts: 0, regulatoryRefNote: 'No RBI / SEBI / IRDAI reference found for India',
    structuredRatePts: 0, structuredRateNote: 'Rate in image',
    directAnswerPts: 10,
    staticScore: 60,
    llmCitationPts: 0,
    totalScore: 62,
    aeoGrade: 'C',
  },
];

// ─── Mock Usage Stats ─────────────────────────────────────────────────────────

export const MOCK_USAGE_STATS: PageUsageStat[] = [
  { statId: 'us-001', pageId: 'visa-platinum-campaign', releaseTargetId: 'GLOBAL', period: 'DAILY',   periodStart: '2026-04-30', totalAccesses: 8412,   uniqueUsers: 6104,  sourceStack: 'GCP' },
  { statId: 'us-002', pageId: 'visa-platinum-campaign', releaseTargetId: 'GLOBAL', period: 'WEEKLY',  periodStart: '2026-04-28', totalAccesses: 47230,  uniqueUsers: 31890, sourceStack: 'GCP' },
  { statId: 'us-003', pageId: 'visa-platinum-campaign', releaseTargetId: 'GLOBAL', period: 'MONTHLY', periodStart: '2026-04-01', totalAccesses: 183440, uniqueUsers: 109200, sourceStack: 'GCP' },
  { statId: 'us-004', pageId: 'visa-platinum-campaign', releaseTargetId: 'HK',     period: 'DAILY',   periodStart: '2026-04-30', totalAccesses: 3210,   uniqueUsers: 2100,  sourceStack: 'GCP' },
  { statId: 'us-005', pageId: 'visa-platinum-campaign', releaseTargetId: 'HK',     period: 'WEEKLY',  periodStart: '2026-04-28', totalAccesses: 18200,  uniqueUsers: 12400, sourceStack: 'GCP' },
  { statId: 'us-006', pageId: 'visa-platinum-campaign', releaseTargetId: 'HK',     period: 'MONTHLY', periodStart: '2026-04-01', totalAccesses: 67300,  uniqueUsers: 39800, sourceStack: 'GCP' },
  { statId: 'us-007', pageId: 'jade-upgrade-hk',        releaseTargetId: 'HK',     period: 'DAILY',   periodStart: '2026-04-30', totalAccesses: 3104,   uniqueUsers: 1890,  sourceStack: 'WECHAT_SA',
    templateMsgDelivered: 48200, templateMsgOpened: 19280, templateMsgClicked: 9140, wechatShareCount: 312 },
  { statId: 'us-008', pageId: 'jade-upgrade-hk',        releaseTargetId: 'HK',     period: 'WEEKLY',  periodStart: '2026-04-28', totalAccesses: 18420,  uniqueUsers: 11200, sourceStack: 'WECHAT_SA' },
];

// ─── Mock Service Account Messages ───────────────────────────────────────────

export const MOCK_SA_MESSAGES: ServiceAccountMessage[] = [
  {
    messageId: 'msg-001',
    pageId: 'jade-upgrade-hk',
    accountId: 'wxa-hk-wealth',
    accountName: 'HSBC HK Wealth SA',
    templateId: 'tpl-promo-invite',
    marketId: 'HK',
    ownedByGroupId: 'HK-WEALTH-AD',
    draftedBy: 'j.chan@hsbc.com.hk',
    draftedByName: 'Janet Chan',
    messageType: 'TEMPLATE_MESSAGE',
    messageName: 'Jade Upgrade Invitation – Apr 2026',
    templateData: {
      title: '您的HSBC Jade升級邀請',
      amount: 'HKD 7,800,000',
      date: '2026-04-30',
      remark: '點擊查看專屬優惠 →',
    },
    audienceType: 'SEGMENT',
    segmentId: 'premier',
    estimatedRecipients: 48200,
    status: 'SENT',
    deliveredCount: 48200,
    openedCount: 19280,
    clickedCount: 9140,
    sharedCount: 312,
    createdAt: new Date(Date.now() - 86400000 * 10).toISOString(),
    approvedBy: 'm.wong@hsbc.com.hk',
    approvedByName: 'Michael Wong',
    approvedAt: new Date(Date.now() - 86400000 * 9).toISOString(),
    sentAt: new Date(Date.now() - 86400000 * 9).toISOString(),
  },
];

// ─── Mock audit log ───────────────────────────────────────────────────────────

export const MOCK_AUDIT: AuditEntry[] = [
  {
    id: 'a-001',
    timestamp: new Date(Date.now() - 86400000 * 10).toISOString(),
    actorId: 'j.chan@hsbc.com.hk',
    actorRole: 'WEALTH-AUTHOR',
    action: 'PAGE_CREATED',
    pageId: 'home-wealth-hk',
    pageName: 'Home – Wealth Hub (HK)',
    details: 'Initial page draft — Channel: SDUI',
    channel: 'SDUI',
    marketId: 'HK',
    bizLineId: 'WEALTH',
  },
  {
    id: 'a-002',
    timestamp: new Date(Date.now() - 86400000 * 9).toISOString(),
    actorId: 'j.chan@hsbc.com.hk',
    actorRole: 'WEALTH-AUTHOR',
    action: 'PAGE_RELEASED_TO_MARKET',
    pageId: 'home-wealth-hk',
    pageName: 'Home – Wealth Hub (HK)',
    details: 'Released to HK (.com.hk) v3',
    marketId: 'HK',
    releaseTargetId: 'HK',
  },
  {
    id: 'a-003',
    timestamp: new Date(Date.now() - 86400000 * 5).toISOString(),
    actorId: 'j.chan@hsbc.com.hk',
    actorRole: 'WEALTH-AUTHOR',
    action: 'PAGE_SUBMITTED',
    pageId: 'visa-platinum-campaign',
    pageName: 'Visa Platinum Q3 Campaign',
    details: 'Submitted for India (bank.in)',
    channel: 'WEB_STANDARD',
    marketId: 'GLOBAL',
    releaseTargetId: 'IN',
  },
  {
    id: 'a-004',
    timestamp: new Date(Date.now() - 86400000 * 3).toISOString(),
    actorId: 'j.chan@hsbc.com.hk',
    actorRole: 'WEALTH-AUTHOR',
    action: 'WECHAT_MESSAGE_SENT',
    pageId: 'jade-upgrade-hk',
    pageName: 'Jade Upgrade Campaign (HK)',
    details: 'Template message sent to 48,200 Premier followers via HSBC HK Wealth SA',
    channel: 'WEB_WECHAT',
    marketId: 'HK',
  },
];

// ─── Staff user roster ────────────────────────────────────────────────────────

export const MOCK_USERS: StaffUser[] = [
  { id: 'j.chan@hsbc.com.hk',  name: 'Janet Chan',   email: 'j.chan@hsbc.com.hk',  role: 'WEALTH-AUTHOR',   marketId: 'HK',     bizLineId: 'WEALTH',  groupId: 'HK-WEALTH-AD' },
  { id: 'm.wong@hsbc.com.hk',  name: 'Michael Wong', email: 'm.wong@hsbc.com.hk',  role: 'WEALTH-APPROVER', marketId: 'HK',     bizLineId: 'WEALTH',  groupId: 'HK-WEALTH-AD' },
  { id: 'k.lee@hsbc.com.hk',   name: 'Karen Lee',    email: 'k.lee@hsbc.com.hk',   role: 'PAYMENT-AUTHOR',  marketId: 'HK',     bizLineId: 'PAYMENT', groupId: 'HK-PAYMENT-AD' },
  { id: 'b.lam@hsbc.com.hk',   name: 'Brian Lam',    email: 'b.lam@hsbc.com.hk',   role: 'ADMIN',           marketId: 'HK',     bizLineId: 'WEALTH',  groupId: 'HK-ADMIN-GRP', isGlobalAdmin: true },
  { id: 's.ng@hsbc.com.hk',    name: 'Sarah Ng',     email: 's.ng@hsbc.com.hk',    role: 'AUDITOR',         marketId: 'HK',     bizLineId: 'WEALTH',  groupId: 'HK-AUDIT-GRP' },
  { id: 'g.author@hsbc.com',   name: 'Global Author', email: 'g.author@hsbc.com',  role: 'WEALTH-AUTHOR',   marketId: 'GLOBAL', bizLineId: 'WEALTH',  groupId: 'GLOBAL-WEALTH-AD' },
];

// Re-export for compat
export const DEFAULT_PAGE_LAYOUT_COMPAT = DEFAULT_PAGE_LAYOUT;

// ─── Content Assets ───────────────────────────────────────────────────────────

export const MOCK_CONTENT_ASSETS: ContentAsset[] = [
  {
    assetId: 'asset-001',
    name: 'Jade Banner Hero',
    assetType: 'IMAGE',
    mimeType: 'image/jpeg',
    sizeBytes: 248320,
    url: 'https://placehold.co/1200x400/1a1a2e/c9a96e?text=Jade+Hero',
    thumbnailUrl: 'https://placehold.co/240x80/1a1a2e/c9a96e?text=Jade+Hero',
    altText: 'HSBC Jade Premier Banking hero banner',
    tags: ['jade', 'hero', 'banner'],
    marketId: 'HK',
    bizLineId: 'WEALTH',
    uploadedBy: 'j.chan@hsbc.com.hk',
    uploadedByName: 'Janet Chan',
    uploadedAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    status: 'ACTIVE',
  },
  {
    assetId: 'asset-002',
    name: 'VISA Infinite Card Art',
    assetType: 'IMAGE',
    mimeType: 'image/png',
    sizeBytes: 184210,
    url: 'https://placehold.co/800x500/DB0011/ffffff?text=VISA+Infinite',
    thumbnailUrl: 'https://placehold.co/160x100/DB0011/ffffff?text=VISA+Infinite',
    altText: 'HSBC VISA Infinite credit card product image',
    tags: ['visa', 'credit-card', 'product'],
    marketId: 'GLOBAL',
    bizLineId: 'PAYMENT',
    uploadedBy: 'k.lee@hsbc.com.hk',
    uploadedByName: 'Karen Lee',
    uploadedAt: new Date(Date.now() - 86400000 * 12).toISOString(),
    status: 'ACTIVE',
  },
  {
    assetId: 'asset-003',
    name: 'KYC Walkthrough Video',
    assetType: 'VIDEO',
    mimeType: 'video/mp4',
    sizeBytes: 18874368,
    url: 'https://placehold.co/1280x720/003366/ffffff?text=KYC+Video',
    thumbnailUrl: 'https://placehold.co/256x144/003366/ffffff?text=KYC+Video',
    altText: 'KYC onboarding walkthrough tutorial',
    tags: ['kyc', 'onboarding', 'tutorial'],
    marketId: 'HK',
    bizLineId: 'WEB_ENABLER',
    uploadedBy: 'j.chan@hsbc.com.hk',
    uploadedByName: 'Janet Chan',
    uploadedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    status: 'ACTIVE',
  },
  {
    assetId: 'asset-004',
    name: 'HSBC Premier T&C PDF',
    assetType: 'DOCUMENT',
    mimeType: 'application/pdf',
    sizeBytes: 3145728,
    url: 'https://placehold.co/1x1/ffffff/ffffff?text=PDF',
    tags: ['terms', 'legal', 'premier'],
    marketId: 'HK',
    bizLineId: 'WEALTH',
    uploadedBy: 'j.chan@hsbc.com.hk',
    uploadedByName: 'Janet Chan',
    uploadedAt: new Date(Date.now() - 86400000 * 20).toISOString(),
    status: 'ACTIVE',
  },
  {
    assetId: 'asset-005',
    name: 'Rate Sheet Q2 2026',
    assetType: 'FILE',
    mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    sizeBytes: 524288,
    url: 'https://placehold.co/1x1/ffffff/ffffff?text=XLSX',
    tags: ['rates', 'wealth', 'q2'],
    marketId: 'GLOBAL',
    bizLineId: 'WEALTH',
    uploadedBy: 'g.author@hsbc.com',
    uploadedByName: 'Global Author',
    uploadedAt: new Date(Date.now() - 86400000 * 8).toISOString(),
    status: 'ACTIVE',
  },
  {
    assetId: 'asset-006',
    name: 'WeChat Campaign Banner',
    assetType: 'IMAGE',
    mimeType: 'image/jpeg',
    sizeBytes: 102400,
    url: 'https://placehold.co/900x500/07C160/ffffff?text=WeChat+Campaign',
    thumbnailUrl: 'https://placehold.co/180x100/07C160/ffffff?text=WeChat+Campaign',
    altText: 'WeChat Jade upgrade campaign banner',
    tags: ['wechat', 'campaign', 'jade'],
    marketId: 'HK',
    bizLineId: 'WEALTH',
    uploadedBy: 'j.chan@hsbc.com.hk',
    uploadedByName: 'Janet Chan',
    uploadedAt: new Date(Date.now() - 86400000 * 1).toISOString(),
    status: 'ACTIVE',
  },
  {
    assetId: 'asset-007',
    name: 'Old Promo Banner 2025',
    assetType: 'IMAGE',
    mimeType: 'image/jpeg',
    sizeBytes: 196608,
    url: 'https://placehold.co/1200x400/888888/ffffff?text=Old+Banner',
    thumbnailUrl: 'https://placehold.co/240x80/888888/ffffff?text=Old+Banner',
    altText: 'Archived 2025 promo banner',
    tags: ['archived', 'promo'],
    marketId: 'HK',
    bizLineId: 'MARKETING',
    uploadedBy: 'k.lee@hsbc.com.hk',
    uploadedByName: 'Karen Lee',
    uploadedAt: new Date(Date.now() - 86400000 * 180).toISOString(),
    status: 'ARCHIVED',
  },
];

// ─── UI Component Registry ────────────────────────────────────────────────────

export const MOCK_UI_COMPONENTS: UIComponent[] = [
  {
    componentId: 'comp-HEADER_NAV',
    sliceType: 'HEADER_NAV',
    label: 'Header Navigation',
    description: 'Top bar with search, notification bell, QR scanner',
    icon: '🔝',
    category: 'navigation',
    configurable: ['title', 'searchPlaceholder', 'showNotificationBell', 'showQRScanner'],
    minHeight: 60,
    singleton: true,
    version: '2.3.1',
    maintainedBy: 'HIVE Platform Team',
    createdAt: '2024-03-15T00:00:00Z',
    updatedAt: '2025-11-02T00:00:00Z',
    status: 'ACTIVE',
  },
  {
    componentId: 'comp-QUICK_ACCESS',
    sliceType: 'QUICK_ACCESS',
    label: 'Quick Access Buttons',
    description: 'Row of primary product shortcuts (e.g. 朝朝宝, 借钱, 转账)',
    icon: '⚡',
    category: 'function',
    configurable: ['items'],
    minHeight: 80,
    singleton: true,
    version: '1.8.0',
    maintainedBy: 'HIVE Platform Team',
    createdAt: '2024-01-10T00:00:00Z',
    updatedAt: '2025-09-14T00:00:00Z',
    status: 'ACTIVE',
  },
  {
    componentId: 'comp-PROMO_BANNER',
    sliceType: 'PROMO_BANNER',
    label: 'Promo Banner',
    description: 'Full-width campaign banner with image, title, CTA',
    icon: '🎪',
    category: 'promotion',
    configurable: ['title', 'subtitle', 'ctaLabel', 'ctaDeepLink', 'imageUrl', 'backgroundColor', 'badgeText'],
    minHeight: 120,
    singleton: false,
    version: '3.1.0',
    maintainedBy: 'Marketing Enablement Team',
    createdAt: '2024-02-01T00:00:00Z',
    updatedAt: '2026-01-20T00:00:00Z',
    status: 'ACTIVE',
  },
  {
    componentId: 'comp-FUNCTION_GRID',
    sliceType: 'FUNCTION_GRID',
    label: 'Function Grid',
    description: 'Icon grid of banking functions (credit card, transfers, etc.)',
    icon: '🔲',
    category: 'function',
    configurable: ['rows'],
    minHeight: 140,
    singleton: true,
    version: '2.0.4',
    maintainedBy: 'HIVE Platform Team',
    createdAt: '2024-01-10T00:00:00Z',
    updatedAt: '2025-07-05T00:00:00Z',
    status: 'ACTIVE',
  },
  {
    componentId: 'comp-AI_ASSISTANT',
    sliceType: 'AI_ASSISTANT',
    label: 'AI Assistant Entry',
    description: 'Intelligent wealth assistant greeting bar',
    icon: '🤖',
    category: 'function',
    configurable: ['greeting'],
    minHeight: 44,
    singleton: false,
    version: '1.2.0',
    maintainedBy: 'AI Team',
    createdAt: '2025-03-01T00:00:00Z',
    updatedAt: '2025-12-10T00:00:00Z',
    status: 'ACTIVE',
  },
  {
    componentId: 'comp-AD_BANNER',
    sliceType: 'AD_BANNER',
    label: 'Advertisement Banner',
    description: 'Dismissible promotional banner with image swap support',
    icon: '📢',
    category: 'promotion',
    configurable: ['title', 'subtitle', 'ctaLabel', 'ctaDeepLink', 'imageUrl', 'dismissible', 'validUntil'],
    minHeight: 90,
    singleton: false,
    version: '1.5.2',
    maintainedBy: 'Marketing Enablement Team',
    createdAt: '2024-04-12T00:00:00Z',
    updatedAt: '2025-08-30T00:00:00Z',
    status: 'ACTIVE',
  },
  {
    componentId: 'comp-FLASH_LOAN',
    sliceType: 'FLASH_LOAN',
    label: 'Flash Loan Card',
    description: 'Instant loan product card with maximum amount display',
    icon: '⚡💳',
    category: 'wealth',
    configurable: ['productName', 'tagline', 'maxAmount', 'currency', 'ctaLabel', 'ctaDeepLink'],
    minHeight: 80,
    singleton: false,
    version: '1.0.3',
    maintainedBy: 'Lending Product Team',
    createdAt: '2024-06-20T00:00:00Z',
    updatedAt: '2025-10-01T00:00:00Z',
    status: 'ACTIVE',
  },
  {
    componentId: 'comp-WEALTH_SELECTION',
    sliceType: 'WEALTH_SELECTION',
    label: 'Wealth Selection',
    description: 'Featured wealth products (7-day yield, risk level)',
    icon: '💰',
    category: 'wealth',
    configurable: ['sectionTitle', 'products', 'moreDeepLink'],
    minHeight: 280,
    singleton: false,
    version: '2.2.1',
    maintainedBy: 'Wealth Product Team',
    createdAt: '2024-02-28T00:00:00Z',
    updatedAt: '2026-02-15T00:00:00Z',
    status: 'ACTIVE',
  },
  {
    componentId: 'comp-FEATURED_RANKINGS',
    sliceType: 'FEATURED_RANKINGS',
    label: 'Featured Rankings',
    description: 'Top-performing funds and product rankings',
    icon: '🏆',
    category: 'wealth',
    configurable: ['sectionTitle', 'items', 'moreDeepLink'],
    minHeight: 180,
    singleton: false,
    version: '1.4.0',
    maintainedBy: 'Wealth Product Team',
    createdAt: '2024-05-10T00:00:00Z',
    updatedAt: '2025-11-28T00:00:00Z',
    status: 'ACTIVE',
  },
  {
    componentId: 'comp-LIFE_DEALS',
    sliceType: 'LIFE_DEALS',
    label: 'Life Deals',
    description: 'Lifestyle merchant offers (KFC, Luckin, DQ…)',
    icon: '🛍️',
    category: 'lifestyle',
    configurable: ['sectionTitle', 'deals', 'moreDeepLink', 'bottomLinks'],
    minHeight: 200,
    singleton: false,
    version: '1.1.0',
    maintainedBy: 'Lifestyle Partnerships Team',
    createdAt: '2024-07-01T00:00:00Z',
    updatedAt: '2025-09-05T00:00:00Z',
    status: 'ACTIVE',
  },
  {
    componentId: 'comp-SPACER',
    sliceType: 'SPACER',
    label: 'Spacer',
    description: 'Vertical spacing element',
    icon: '↕️',
    category: 'layout',
    configurable: ['height'],
    minHeight: 16,
    singleton: false,
    version: '1.0.0',
    maintainedBy: 'HIVE Platform Team',
    createdAt: '2023-12-01T00:00:00Z',
    updatedAt: '2023-12-01T00:00:00Z',
    status: 'ACTIVE',
  },
];
