import type {
  PageLayout, WorkflowEntry, AuditEntry, StaffUser,
  BizLine, AdGroup,
  ContentAsset, UIComponent, ContentApprovalFlow,
} from '../types/ucp';

// ─── Biz Lines ────────────────────────────────────────────────────────────────

export const BIZ_LINES: BizLine[] = [
  { bizLineId: 'PAYMENT',     displayName: 'Payment & Cards',       description: 'Credit card, transaction pages',        active: true },
  { bizLineId: 'WEB_ENABLER', displayName: 'Web Enablement',        description: 'Core web infrastructure, navigation',   active: true },
  { bizLineId: 'LENDING',     displayName: 'Lending & Mortgage',    description: 'Loan, mortgage, overdraft pages',        active: true },
  { bizLineId: 'COLLECTION',  displayName: 'Collections',           description: 'Debt management, repayment pages',       active: true },
  { bizLineId: 'WEALTH',      displayName: 'Wealth & Investments',  description: 'Premier, Jade, investment pages',        active: true },
  { bizLineId: 'MARKETING',   displayName: 'Marketing & Campaigns', description: 'Campaign pages, promotional banners',    active: true },
];

export const AD_GROUPS: AdGroup[] = [
  { groupId: 'HK-WEALTH-AD',     groupName: 'HK Wealth AD Group',      marketId: 'HK',     bizLineId: 'WEALTH',      groupType: 'AD_GROUP' },
  { groupId: 'HK-PAYMENT-AD',    groupName: 'HK Payment AD Group',     marketId: 'HK',     bizLineId: 'PAYMENT',     groupType: 'AD_GROUP' },
  { groupId: 'HK-MARKETING-AD',  groupName: 'HK Marketing AD Group',   marketId: 'HK',     bizLineId: 'MARKETING',   groupType: 'AD_GROUP' },
  { groupId: 'SG-WEALTH-AD',     groupName: 'SG Wealth AD Group',      marketId: 'SG',     bizLineId: 'WEALTH',      groupType: 'AD_GROUP' },
  { groupId: 'GLOBAL-WEALTH-AD', groupName: 'Global Wealth AD Group',  marketId: 'GLOBAL', bizLineId: 'WEALTH',      groupType: 'AD_GROUP' },
  { groupId: 'HK-ADMIN-GRP',     groupName: 'HK Admin Group',          marketId: 'HK',     bizLineId: 'WEALTH',      groupType: 'ADMIN_GROUP' },
  { groupId: 'GLOBAL-ADMIN-GRP', groupName: 'Global Admin Group',      marketId: 'GLOBAL', bizLineId: 'WEALTH',      groupType: 'ADMIN_GROUP' },
  { groupId: 'HK-AUDIT-GRP',     groupName: 'HK Audit Group',          marketId: 'HK',     bizLineId: 'WEALTH',      groupType: 'AUDIT_GROUP' },
];

// ─── Mock pages ───────────────────────────────────────────────────────────────

export const DEFAULT_PAGE_LAYOUT: PageLayout = {
  pageId: 'home-wealth-hk',
  name: 'Home – Wealth Hub (HK)',
  pageType: 'WEALTH_HUB',
  description: 'Main wealth hub home page for HK market',
  platform: 'all',
  locale: 'zh-HK',
  thumbnail: '💰',
  tags: ['wealth', 'home', 'hk'],
  bizLineId: 'WEALTH',
  groupId: 'HK-WEALTH-AD',
  authoringStatus: 'APPROVED',
  slices: [
    {
      instanceId: 'slice-header',
      type: 'HEADER_NAV',
      props: { title: '定期存款', searchPlaceholder: '搜尋功能、產品', showNotificationBell: true, showQRScanner: true },
      visible: true, locked: false,
    },
    {
      instanceId: 'slice-quick',
      type: 'QUICK_ACCESS',
      props: {
        items: [
          { id: 'q1', icon: '🌙', label: '朝朝寶',   deepLink: 'hsbc://wealth/morning-treasure' },
          { id: 'q2', icon: '💵', label: '借錢',     deepLink: 'hsbc://loan/apply' },
          { id: 'q3', icon: '↔️', label: '轉帳',     deepLink: 'hsbc://transfer' },
          { id: 'q4', icon: '📊', label: '賬戶總覽', deepLink: 'hsbc://accounts' },
        ],
      },
      visible: true, locked: false,
    },
    {
      instanceId: 'slice-promo-10',
      type: 'PROMO_BANNER',
      props: { title: '10分招財日', subtitle: '查帳單·學投資·優配置', ctaLabel: '點擊參與', ctaDeepLink: 'hsbc://campaign/finance-day', imageUrl: '', backgroundColor: '#E8F4FD', badgeText: '每月10日開啓' },
      visible: true, locked: false,
    },
    {
      instanceId: 'slice-wealth-sel',
      type: 'WEALTH_SELECTION',
      props: {
        sectionTitle: '財富精選',
        products: [
          { id: 'w1', productName: '活錢理財｜歷史天天正收益', tag: '代碼', yield7Day: '2.80%', riskLevel: 'R1低風險', redemption: '贖回T+1到帳', ctaLabel: '去看看', ctaDeepLink: 'hsbc://wealth/daily-positive', highlighted: true },
          { id: 'w2', productName: '主投債券', tag: '代碼', yield7Day: '3.04%', riskLevel: '歷史周周正', redemption: '成立以來…', ctaLabel: '查看', ctaDeepLink: 'hsbc://wealth/bond-fund' },
        ],
        moreDeepLink: 'hsbc://wealth/all',
      },
      visible: true, locked: false,
    },
    {
      instanceId: 'slice-ai',
      type: 'AI_ASSISTANT',
      props: { greeting: 'Hi，我是你的智能財富助理', avatarUrl: '' },
      visible: true, locked: false,
    },
  ],
};

export const JADE_CAMPAIGN_PAGE: PageLayout = {
  pageId: 'jade-upgrade-hk',
  name: 'Jade Upgrade Campaign (HK)',
  pageType: 'CAMPAIGN',
  description: 'Jade upgrade invitation page for Premier customers',
  platform: 'all',
  locale: 'zh-HK',
  thumbnail: '🟡',
  tags: ['jade', 'wealth', 'campaign'],
  bizLineId: 'WEALTH',
  groupId: 'HK-WEALTH-AD',
  authoringStatus: 'APPROVED',
  slices: [
    {
      instanceId: 'jade-hero',
      type: 'PROMO_BANNER',
      props: { title: 'HSBC Jade 升級邀請', subtitle: '專為Premier客戶而設的尊貴服務', ctaLabel: '立即申請', ctaDeepLink: 'hsbc://jade/apply', imageUrl: '', backgroundColor: '#1D1D1B', badgeText: '尊屬優惠' },
      visible: true, locked: false,
    },
    {
      instanceId: 'jade-wealth',
      type: 'WEALTH_SELECTION',
      props: { sectionTitle: 'Jade 專屬產品', products: [], moreDeepLink: 'hsbc://jade/all' },
      visible: true, locked: false,
    },
  ],
};

export const VISA_CAMPAIGN_PAGE: PageLayout = {
  pageId: 'visa-platinum-campaign',
  name: 'Visa Platinum Q3 Campaign',
  pageType: 'CAMPAIGN',
  description: 'Visa Platinum no-FX campaign for Q3 2026',
  platform: 'web',
  locale: 'en-HK',
  thumbnail: '💳',
  tags: ['cards', 'campaign', 'visa'],
  bizLineId: 'PAYMENT',
  groupId: 'GLOBAL-WEALTH-AD',
  authoringStatus: 'DRAFT',
  slices: [],
};

export const OBKYC_PAGE_LAYOUT: PageLayout = {
  pageId: 'obkyc-journey',
  name: 'OBKYC – Account Opening Journey',
  pageType: 'KYC_JOURNEY',
  description: 'Open Banking KYC journey — 10-step mobile flow',
  platform: 'all',
  locale: 'en-HK',
  thumbnail: '🪪',
  tags: ['kyc', 'onboarding'],
  bizLineId: 'WEB_ENABLER',
  groupId: 'HK-WEALTH-AD',
  authoringStatus: 'DRAFT',
  slices: [
    {
      instanceId: 'kyc-header',
      type: 'HEADER_NAV',
      props: { title: 'Account Opening', searchPlaceholder: 'Search', showNotificationBell: false, showQRScanner: false },
      visible: true, locked: true,
    },
    {
      instanceId: 'kyc-promo',
      type: 'PROMO_BANNER',
      props: { title: 'Open Banking Account Opening', subtitle: 'Complete your KYC in minutes. Regulated by HKMA.', ctaLabel: 'Begin Application', ctaDeepLink: 'hsbc://kyc/start', imageUrl: '', backgroundColor: '#E8F0FE', badgeText: 'HKMA Regulated' },
      visible: true, locked: false,
    },
  ],
};

export const MARKET_INSIGHT_PAGE: PageLayout = {
  pageId: 'fx-viewpoint-hk',
  name: 'FX Viewpoint — EUR & GBP (HK)',
  pageType: 'MARKET_INSIGHT',
  description: 'Market insight page: EUR and GBP analysis — ECB on hold and BoE rate cut. Includes video, briefing text and RM contact CTA.',
  platform: 'all',
  locale: 'en-HK',
  thumbnail: '📈',
  tags: ['fx', 'market-insight', 'eur', 'gbp', 'wealth'],
  bizLineId: 'WEALTH',
  groupId: 'HK-WEALTH-AD',
  authoringStatus: 'APPROVED',
  slices: [
    {
      instanceId: 'mi-header',
      type: 'HEADER_NAV',
      props: { title: 'FX Viewpoint', showNotificationBell: false, showQRScanner: false, showBackButton: true },
      visible: true, locked: true,
    },
    {
      instanceId: 'mi-content-header',
      type: 'VIDEO_PLAYER',
      props: {
        ucpAssetId: 'asset-008',
        title: 'FX Viewpoint — EUR & GBP Market Insights (May 2026)',
        thumbnailUrl: 'https://placehold.co/1280x720/003366/ffffff?text=FX+Viewpoint+EUR+%26+GBP',
        videoUrl: 'http://localhost:3001/media/fx-viewpoint.mov',
        presenterName: 'Jackie Wong',
        presenterTitle: 'FX Strategist, HSBC Global Research',
        autoplay: false,
        showCaption: true,
      },
      visible: true, locked: false,
    },
    {
      instanceId: 'mi-briefing',
      type: 'MARKET_BRIEFING_TEXT',
      props: {
        ucpContentId: 'ucp-content-fx-viewpoint-001',
        sectionTitle: 'Key takeaways',
        bulletPoints: [
          'A weak USD is likely to persist into 2026, providing temporary support for the EUR and GBP.',
          'With the ECB expected to maintain its policy rate in 2026, the EUR should remain broadly stable.',
          'BoE delivered a 25 bps cut in May 2026 — further easing is data-dependent and market pricing appears stretched.',
          'GBP/USD faces near-term resistance at 1.3200 amid mixed UK growth signals.',
          'Investors should consider diversified FX exposure to manage downside risk against a volatile USD backdrop.',
        ],
        disclaimer: 'This material is issued by HSBC and is for information purposes only. It does not constitute investment advice or a recommendation to buy or sell any financial instrument.',
      },
      visible: true, locked: false,
    },
    {
      instanceId: 'mi-contact-rm',
      type: 'CONTACT_RM_CTA',
      props: {
        label: 'Contact Your RM',
        subLabel: 'Speak to your Relationship Manager about FX opportunities',
        deepLink: 'hsbc://rm/contact?context=fx-viewpoint',
        backgroundColor: '#DB0011',
        textColor: '#FFFFFF',
        sticky: true,
      },
      visible: true, locked: false,
    },
  ],
};

export const DEPOSIT_CAMPAIGN_PAGE: PageLayout = {
  pageId: 'deposit-campaign-hk',
  name: 'New Fund Deposit Campaign (CN)',
  pageType: 'CAMPAIGN',
  description: 'Renminbi Savings new fund deposit campaign — highlights elevated time deposit rates with a rate table and FAQ.',
  platform: 'all',
  locale: 'en-CN',
  thumbnail: '🏦',
  tags: ['deposit', 'savings', 'campaign', 'renminbi', 'time-deposit'],
  bizLineId: 'WEALTH',
  groupId: 'HK-WEALTH-AD',
  authoringStatus: 'APPROVED',
  slices: [
    {
      instanceId: 'dep-header',
      type: 'HEADER_NAV',
      props: {
        title: 'Renminbi Savings Offers',
        showNotificationBell: false,
        showQRScanner: false,
        showBackButton: true,
      },
      visible: true,
      locked: true,
    },
    {
      instanceId: 'dep-image-banner',
      type: 'PROMO_BANNER',
      props: {
        imageUrl: '/media/deposit-campaign-banner.jpg',
        ucpAssetId: 'asset-009',
        backgroundColor: '#FFFFFF',
      },
      visible: true,
      locked: false,
    },
    {
      instanceId: 'dep-cd-rate-banner',
      type: 'PROMO_BANNER',
      props: {
        title: '🌟 Up to 1.15% p.a. Annual Equivalent Rate',
        subtitle: '3-Month New Fund CNY Transferable CD — exclusively for new deposits. Don\'t miss this limited-time rate. Start earning more today.',
        badgeText: '🔥 New Funds Only',
        backgroundColor: '#FFF7ED',
        textColor: '#92400E',
      },
      visible: true,
      locked: false,
    },
    {
      instanceId: 'dep-rate-table',
      type: 'DEPOSIT_RATE_TABLE',
      props: {
        sectionTitle: 'Time Deposit Rate:',
        asAtDate: '5/22/2025',
        rates: [
          { term: '3 Month Time Deposit',  rate: '0.65' },
          { term: '6 Month Time Deposit',  rate: '0.85' },
          { term: '12 Month Time Deposit', rate: '0.95' },
          { term: '24 Month Time Deposit', rate: '1.05' },
          { term: '36 Month Time Deposit', rate: '1.25' },
          { term: '60 Month Time Deposit', rate: '1.30' },
        ],
        footnote: 'Time deposit minimum balance for Personal Banking customers: RMB50. New Fund refers to funds not previously held with HSBC.',
      },
      visible: true,
      locked: false,
    },
    {
      instanceId: 'dep-open-cta',
      type: 'DEPOSIT_OPEN_CTA',
      props: {
        label: 'Open a Deposit',
        deepLink: 'hsbc://deposit/open?currency=CNY&campaign=new-fund',
        backgroundColor: '#C41E3A',
        textColor: '#FFFFFF',
      },
      visible: true,
      locked: false,
    },
    {
      instanceId: 'dep-spacer',
      type: 'SPACER',
      props: { height: 16 },
      visible: true,
      locked: false,
    },
    {
      instanceId: 'dep-faq',
      type: 'DEPOSIT_FAQ',
      props: {
        sectionTitle: 'Frequently Asked Questions',
        items: [
          {
            id: 'faq-1',
            question: 'Can I withdraw my time deposit before it matures?',
            answer: 'Yes, you can. But you\'ll earn less or no interest, and may have to pay an early withdrawal fee. For foreign currency deposits, visit a bank branch.',
          },
          {
            id: 'faq-2',
            question: 'What happens if I don\'t withdraw my money after maturity?',
            answer: 'If you don\'t take out your money when it matures, most banks will automatically renew your deposit for the same term at the current interest rate. You can also choose to withdraw it or change the term before maturity.',
          },
          {
            id: 'faq-3',
            question: 'How long can I keep a time deposit?',
            answer: 'Banks usually offer terms like 3 months, 6 months, 1 year, 2 years, 3 years, 5 years, or even 10 years. Longer terms usually have higher interest rates. The most popular choices are 6-month or 12-month plans.',
          },
          {
            id: 'faq-4',
            question: 'Why is the interest rate higher for time deposits than regular savings accounts?',
            answer: 'Banks can offer better rates because they know you\'ll keep your money in the account for a fixed period. This lets them use the funds for longer-term investments, so they share more of the profit with you as interest.',
          },
        ],
      },
      visible: true,
      locked: false,
    },
  ],
};

export const ALL_PAGES: PageLayout[] = [
  DEFAULT_PAGE_LAYOUT,
  JADE_CAMPAIGN_PAGE,
  VISA_CAMPAIGN_PAGE,
  OBKYC_PAGE_LAYOUT,
  MARKET_INSIGHT_PAGE,
  DEPOSIT_CAMPAIGN_PAGE,
];

// ─── Mock workflow entries ────────────────────────────────────────────────────

export const MOCK_WORKFLOW_ENTRIES: WorkflowEntry[] = [
  {
    entryId: 'wf-001',
    pageId: 'home-wealth-hk',
    pageName: 'Home – Wealth Hub (HK)',
    status: 'LIVE',
    authorId: 'j.chan@hsbc.com.hk',
    authorName: 'Janet Chan',
    comments: [],
    layout: DEFAULT_PAGE_LAYOUT,
    version: 3,
  },
  {
    entryId: 'wf-002',
    pageId: 'jade-upgrade-hk',
    pageName: 'Jade Upgrade Campaign (HK)',
    status: 'LIVE',
    authorId: 'j.chan@hsbc.com.hk',
    authorName: 'Janet Chan',
    comments: [],
    layout: JADE_CAMPAIGN_PAGE,
    version: 2,
  },
  {
    entryId: 'wf-003',
    pageId: 'visa-platinum-campaign',
    pageName: 'Visa Platinum Q3 Campaign',
    status: 'DRAFT',
    authorId: 'j.chan@hsbc.com.hk',
    authorName: 'Janet Chan',
    comments: [],
    layout: VISA_CAMPAIGN_PAGE,
    version: 1,
  },
  {
    entryId: 'wf-004',
    pageId: 'obkyc-journey',
    pageName: 'OBKYC – Account Opening Journey',
    status: 'DRAFT',
    authorId: 'k.lee@hsbc.com.hk',
    authorName: 'Karen Lee',
    comments: [],
    layout: OBKYC_PAGE_LAYOUT,
    version: 1,
  },
  {
    entryId: 'wf-005',
    pageId: 'fx-viewpoint-hk',
    pageName: 'FX Viewpoint — EUR & GBP (HK)',
    status: 'LIVE',
    authorId: 'j.chan@hsbc.com.hk',
    authorName: 'Janet Chan',
    comments: [],
    layout: MARKET_INSIGHT_PAGE,
    version: 1,
  },
  {
    entryId: 'wf-006',
    pageId: 'deposit-campaign-hk',
    pageName: 'New Fund Deposit Campaign (HK)',
    status: 'LIVE',
    authorId: 'j.chan@hsbc.com.hk',
    authorName: 'Janet Chan',
    comments: [],
    layout: DEPOSIT_CAMPAIGN_PAGE,
    version: 1,
  },
];

// ─── Mock audit log ───────────────────────────────────────────────────────────

export const MOCK_AUDIT: AuditEntry[] = [
  {
    id: 'a-001',
    timestamp: new Date(Date.now() - 86400000 * 10).toISOString(),
    actorId: 'j.chan@hsbc.com.hk',
    actorRole: 'WEALTH-AUTHOR',
    action: 'PAGE_CREATED',
    pageId: 'home-wealth-hk',
    pageName: 'Home – Wealth Hub (HK)',
    details: 'Initial page draft',
    bizLineId: 'WEALTH',
  },
  {
    id: 'a-002',
    timestamp: new Date(Date.now() - 86400000 * 9).toISOString(),
    actorId: 'j.chan@hsbc.com.hk',
    actorRole: 'WEALTH-AUTHOR',
    action: 'PAGE_APPROVED',
    pageId: 'home-wealth-hk',
    pageName: 'Home – Wealth Hub (HK)',
    details: 'Approved v3',
    bizLineId: 'WEALTH',
  },
  {
    id: 'a-003',
    timestamp: new Date(Date.now() - 86400000 * 5).toISOString(),
    actorId: 'j.chan@hsbc.com.hk',
    actorRole: 'WEALTH-AUTHOR',
    action: 'PAGE_CREATED',
    pageId: 'visa-platinum-campaign',
    pageName: 'Visa Platinum Q3 Campaign',
    details: 'Draft created',
    bizLineId: 'PAYMENT',
  },
  {
    id: 'a-004',
    timestamp: new Date(Date.now() - 86400000 * 3).toISOString(),
    actorId: 'k.lee@hsbc.com.hk',
    actorRole: 'PAYMENT-AUTHOR',
    action: 'SLICE_ADDED',
    pageId: 'visa-platinum-campaign',
    pageName: 'Visa Platinum Q3 Campaign',
    details: 'Added PROMO_BANNER',
    bizLineId: 'PAYMENT',
  },
];

// ─── Staff user roster ────────────────────────────────────────────────────────

export const MOCK_USERS: StaffUser[] = [
  { id: 'j.chan@hsbc.com.hk',  name: 'Janet Chan',    email: 'j.chan@hsbc.com.hk',  role: 'WEALTH-AUTHOR',   marketId: 'HK',     bizLineId: 'WEALTH',  groupId: 'HK-WEALTH-AD' },
  { id: 'm.wong@hsbc.com.hk',  name: 'Michael Wong',  email: 'm.wong@hsbc.com.hk',  role: 'WEALTH-APPROVER', marketId: 'HK',     bizLineId: 'WEALTH',  groupId: 'HK-WEALTH-AD' },
  { id: 'k.lee@hsbc.com.hk',   name: 'Karen Lee',     email: 'k.lee@hsbc.com.hk',   role: 'PAYMENT-AUTHOR',  marketId: 'HK',     bizLineId: 'PAYMENT', groupId: 'HK-PAYMENT-AD' },
  { id: 'b.lam@hsbc.com.hk',   name: 'Brian Lam',     email: 'b.lam@hsbc.com.hk',   role: 'ADMIN',           marketId: 'HK',     bizLineId: 'WEALTH',  groupId: 'HK-ADMIN-GRP', isGlobalAdmin: true },
  { id: 's.ng@hsbc.com.hk',    name: 'Sarah Ng',      email: 's.ng@hsbc.com.hk',    role: 'AUDITOR',         marketId: 'HK',     bizLineId: 'WEALTH',  groupId: 'HK-AUDIT-GRP' },
  { id: 'g.author@hsbc.com',   name: 'Global Author', email: 'g.author@hsbc.com',   role: 'WEALTH-AUTHOR',   marketId: 'GLOBAL', bizLineId: 'WEALTH',  groupId: 'GLOBAL-WEALTH-AD' },
];

// ─── Content Assets ───────────────────────────────────────────────────────────

export const MOCK_CONTENT_ASSETS: ContentAsset[] = [
  {
    assetId: 'asset-001',
    name: 'Jade Banner Hero',
    assetType: 'IMAGE',
    mimeType: 'image/jpeg',
    sizeBytes: 248320,
    url: 'https://placehold.co/1200x400/1a1a2e/c9a96e?text=Jade+Hero',
    thumbnailUrl: 'https://placehold.co/240x80/1a1a2e/c9a96e?text=Jade+Hero',
    altText: 'HSBC Jade Premier Banking hero banner',
    tags: ['jade', 'hero', 'banner'],
    marketId: 'HK',
    bizLineId: 'WEALTH',
    uploadedBy: 'j.chan@hsbc.com.hk',
    uploadedByName: 'Janet Chan',
    uploadedAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    status: 'ACTIVE',
  },
  {
    assetId: 'asset-002',
    name: 'VISA Infinite Card Art',
    assetType: 'IMAGE',
    mimeType: 'image/png',
    sizeBytes: 184210,
    url: 'https://placehold.co/800x500/DB0011/ffffff?text=VISA+Infinite',
    thumbnailUrl: 'https://placehold.co/160x100/DB0011/ffffff?text=VISA+Infinite',
    altText: 'HSBC VISA Infinite credit card product image',
    tags: ['visa', 'credit-card', 'product'],
    marketId: 'GLOBAL',
    bizLineId: 'PAYMENT',
    uploadedBy: 'k.lee@hsbc.com.hk',
    uploadedByName: 'Karen Lee',
    uploadedAt: new Date(Date.now() - 86400000 * 12).toISOString(),
    status: 'ACTIVE',
  },
  {
    assetId: 'asset-003',
    name: 'KYC Walkthrough Video',
    assetType: 'VIDEO',
    mimeType: 'video/mp4',
    sizeBytes: 18874368,
    url: 'https://placehold.co/1280x720/003366/ffffff?text=KYC+Video',
    thumbnailUrl: 'https://placehold.co/256x144/003366/ffffff?text=KYC+Video',
    altText: 'KYC onboarding walkthrough tutorial',
    tags: ['kyc', 'onboarding', 'tutorial'],
    marketId: 'HK',
    bizLineId: 'WEB_ENABLER',
    uploadedBy: 'j.chan@hsbc.com.hk',
    uploadedByName: 'Janet Chan',
    uploadedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    status: 'ACTIVE',
  },
  {
    assetId: 'asset-004',
    name: 'HSBC Premier T&C PDF',
    assetType: 'DOCUMENT',
    mimeType: 'application/pdf',
    sizeBytes: 3145728,
    url: 'https://placehold.co/1x1/ffffff/ffffff?text=PDF',
    tags: ['terms', 'legal', 'premier'],
    marketId: 'HK',
    bizLineId: 'WEALTH',
    uploadedBy: 'j.chan@hsbc.com.hk',
    uploadedByName: 'Janet Chan',
    uploadedAt: new Date(Date.now() - 86400000 * 20).toISOString(),
    status: 'ACTIVE',
  },
  {
    assetId: 'asset-005',
    name: 'Rate Sheet Q2 2026',
    assetType: 'FILE',
    mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    sizeBytes: 524288,
    url: 'https://placehold.co/1x1/ffffff/ffffff?text=XLSX',
    tags: ['rates', 'wealth', 'q2'],
    marketId: 'GLOBAL',
    bizLineId: 'WEALTH',
    uploadedBy: 'g.author@hsbc.com',
    uploadedByName: 'Global Author',
    uploadedAt: new Date(Date.now() - 86400000 * 8).toISOString(),
    status: 'ACTIVE',
  },
  {
    assetId: 'asset-006',
    name: 'WeChat Campaign Banner',
    assetType: 'IMAGE',
    mimeType: 'image/jpeg',
    sizeBytes: 102400,
    url: 'https://placehold.co/900x500/07C160/ffffff?text=WeChat+Campaign',
    thumbnailUrl: 'https://placehold.co/180x100/07C160/ffffff?text=WeChat+Campaign',
    altText: 'WeChat Jade upgrade campaign banner',
    tags: ['wechat', 'campaign', 'jade'],
    marketId: 'HK',
    bizLineId: 'WEALTH',
    uploadedBy: 'j.chan@hsbc.com.hk',
    uploadedByName: 'Janet Chan',
    uploadedAt: new Date(Date.now() - 86400000 * 1).toISOString(),
    status: 'ACTIVE',
  },
  {
    assetId: 'asset-008',
    name: 'FX Viewpoint — EUR & GBP Market Insights (May 2026)',
    assetType: 'VIDEO',
    mimeType: 'video/mp4',
    sizeBytes: 163549482,
    url: '/media/fx-viewpoint.mov',
    thumbnailUrl: 'https://placehold.co/1280x720/003366/ffffff?text=FX+Viewpoint+EUR+%26+GBP',
    altText: 'HSBC FX Viewpoint: EUR and GBP — ECB on hold and BoE cut rates. Presented by Jackie Wong.',
    tags: ['fx', 'viewpoint', 'eur', 'gbp', 'market-insight', 'wealth'],
    marketId: 'HK',
    bizLineId: 'WEALTH',
    uploadedBy: 'j.chan@hsbc.com.hk',
    uploadedByName: 'Janet Chan',
    uploadedAt: new Date(Date.now() - 86400000 * 1).toISOString(),
    status: 'ACTIVE',
    durationSeconds: 120,
    presenter: 'Jackie Wong',
    presenterTitle: 'FX Strategist, HSBC Global Research',
    approvalStatus: 'APPROVED',
    approvalGroupId: 'HK-WEALTH-AD',
    approvalReviewedAt: new Date(Date.now() - 86400000 * 1).toISOString(),
    approvalReviewerId: 'approver-01',
    approvalReviewerName: 'Amy Leung',
  },
  {
    assetId: 'asset-007',
    name: 'Old Promo Banner 2025',
    assetType: 'IMAGE',
    mimeType: 'image/jpeg',
    sizeBytes: 196608,
    url: 'https://placehold.co/1200x400/888888/ffffff?text=Old+Banner',
    thumbnailUrl: 'https://placehold.co/240x80/888888/ffffff?text=Old+Banner',
    altText: 'Archived 2025 promo banner',
    tags: ['archived', 'promo'],
    marketId: 'HK',
    bizLineId: 'MARKETING',
    uploadedBy: 'k.lee@hsbc.com.hk',
    uploadedByName: 'Karen Lee',
    uploadedAt: new Date(Date.now() - 86400000 * 180).toISOString(),
    status: 'ARCHIVED',
  },
  {
    assetId: 'asset-009',
    name: 'Deposit Campaign Hero Banner',
    assetType: 'IMAGE',
    mimeType: 'image/jpeg',
    sizeBytes: 312000,
    url: '/media/deposit-campaign-banner.jpg',
    thumbnailUrl: '/media/deposit-campaign-banner.jpg',
    altText: 'Father and child looking out over mountains and lake — Renminbi Savings new fund deposit campaign',
    tags: ['deposit', 'campaign', 'savings', 'renminbi', 'banner'],
    marketId: 'HK',
    bizLineId: 'WEALTH',
    uploadedBy: 'j.chan@hsbc.com.hk',
    uploadedByName: 'Janet Chan',
    uploadedAt: new Date(Date.now() - 86400000 * 0).toISOString(),
    status: 'ACTIVE',
    approvalStatus: 'APPROVED',
    approvalGroupId: 'HK-WEALTH-AD',
    approvalReviewedAt: new Date(Date.now()).toISOString(),
    approvalReviewerId: 'approver-01',
    approvalReviewerName: 'Michael Wong',
  },
];

// ─── UI Component Registry ────────────────────────────────────────────────────

export const MOCK_UI_COMPONENTS: UIComponent[] = [
  {
    componentId: 'comp-HEADER_NAV',
    sliceType: 'HEADER_NAV',
    label: 'Header Navigation',
    description: 'Top bar with search, notification bell, QR scanner',
    icon: '🔝',
    category: 'navigation',
    configurable: ['title', 'searchPlaceholder', 'showNotificationBell', 'showQRScanner'],
    minHeight: 60,
    singleton: true,
    version: '2.3.1',
    maintainedBy: 'HIVE Platform Team',
    createdAt: '2024-03-15T00:00:00Z',
    updatedAt: '2025-11-02T00:00:00Z',
    status: 'ACTIVE',
  },
  {
    componentId: 'comp-QUICK_ACCESS',
    sliceType: 'QUICK_ACCESS',
    label: 'Quick Access Buttons',
    description: 'Row of primary product shortcuts (e.g. 朝朝宝, 借钱, 转账)',
    icon: '⚡',
    category: 'function',
    configurable: ['items'],
    minHeight: 80,
    singleton: true,
    version: '1.8.0',
    maintainedBy: 'HIVE Platform Team',
    createdAt: '2024-01-10T00:00:00Z',
    updatedAt: '2025-09-14T00:00:00Z',
    status: 'ACTIVE',
  },
  {
    componentId: 'comp-PROMO_BANNER',
    sliceType: 'PROMO_BANNER',
    label: 'Promo Banner',
    description: 'Full-width campaign banner with image, title, CTA',
    icon: '🎪',
    category: 'promotion',
    configurable: ['title', 'subtitle', 'ctaLabel', 'ctaDeepLink', 'imageUrl', 'backgroundColor', 'badgeText'],
    minHeight: 120,
    singleton: false,
    version: '3.1.0',
    maintainedBy: 'Marketing Enablement Team',
    createdAt: '2024-02-01T00:00:00Z',
    updatedAt: '2026-01-20T00:00:00Z',
    status: 'ACTIVE',
  },
  {
    componentId: 'comp-FUNCTION_GRID',
    sliceType: 'FUNCTION_GRID',
    label: 'Function Grid',
    description: 'Icon grid of banking functions (credit card, transfers, etc.)',
    icon: '🔲',
    category: 'function',
    configurable: ['rows'],
    minHeight: 140,
    singleton: true,
    version: '2.0.4',
    maintainedBy: 'HIVE Platform Team',
    createdAt: '2024-01-10T00:00:00Z',
    updatedAt: '2025-07-05T00:00:00Z',
    status: 'ACTIVE',
  },
  {
    componentId: 'comp-AI_ASSISTANT',
    sliceType: 'AI_ASSISTANT',
    label: 'AI Assistant Entry',
    description: 'Intelligent wealth assistant greeting bar',
    icon: '🤖',
    category: 'function',
    configurable: ['greeting'],
    minHeight: 44,
    singleton: false,
    version: '1.2.0',
    maintainedBy: 'AI Team',
    createdAt: '2025-03-01T00:00:00Z',
    updatedAt: '2025-12-10T00:00:00Z',
    status: 'ACTIVE',
  },
  {
    componentId: 'comp-AD_BANNER',
    sliceType: 'AD_BANNER',
    label: 'Advertisement Banner',
    description: 'Dismissible promotional banner with image swap support',
    icon: '📢',
    category: 'promotion',
    configurable: ['title', 'subtitle', 'ctaLabel', 'ctaDeepLink', 'imageUrl', 'dismissible', 'validUntil'],
    minHeight: 90,
    singleton: false,
    version: '1.5.2',
    maintainedBy: 'Marketing Enablement Team',
    createdAt: '2024-04-12T00:00:00Z',
    updatedAt: '2025-08-30T00:00:00Z',
    status: 'ACTIVE',
  },
  {
    componentId: 'comp-FLASH_LOAN',
    sliceType: 'FLASH_LOAN',
    label: 'Flash Loan Card',
    description: 'Instant loan product card with maximum amount display',
    icon: '⚡💳',
    category: 'wealth',
    configurable: ['productName', 'tagline', 'maxAmount', 'currency', 'ctaLabel', 'ctaDeepLink'],
    minHeight: 80,
    singleton: false,
    version: '1.0.3',
    maintainedBy: 'Lending Product Team',
    createdAt: '2024-06-20T00:00:00Z',
    updatedAt: '2025-10-01T00:00:00Z',
    status: 'ACTIVE',
  },
  {
    componentId: 'comp-WEALTH_SELECTION',
    sliceType: 'WEALTH_SELECTION',
    label: 'Wealth Selection',
    description: 'Featured wealth products (7-day yield, risk level)',
    icon: '💰',
    category: 'wealth',
    configurable: ['sectionTitle', 'products', 'moreDeepLink'],
    minHeight: 280,
    singleton: false,
    version: '2.2.1',
    maintainedBy: 'Wealth Product Team',
    createdAt: '2024-02-28T00:00:00Z',
    updatedAt: '2026-02-15T00:00:00Z',
    status: 'ACTIVE',
  },
  {
    componentId: 'comp-FEATURED_RANKINGS',
    sliceType: 'FEATURED_RANKINGS',
    label: 'Featured Rankings',
    description: 'Top-performing funds and product rankings',
    icon: '🏆',
    category: 'wealth',
    configurable: ['sectionTitle', 'items', 'moreDeepLink'],
    minHeight: 180,
    singleton: false,
    version: '1.4.0',
    maintainedBy: 'Wealth Product Team',
    createdAt: '2024-05-10T00:00:00Z',
    updatedAt: '2025-11-28T00:00:00Z',
    status: 'ACTIVE',
  },
  {
    componentId: 'comp-LIFE_DEALS',
    sliceType: 'LIFE_DEALS',
    label: 'Life Deals',
    description: 'Lifestyle merchant offers (KFC, Luckin, DQ…)',
    icon: '🛍️',
    category: 'lifestyle',
    configurable: ['sectionTitle', 'deals', 'moreDeepLink', 'bottomLinks'],
    minHeight: 200,
    singleton: false,
    version: '1.1.0',
    maintainedBy: 'Lifestyle Partnerships Team',
    createdAt: '2024-07-01T00:00:00Z',
    updatedAt: '2025-09-05T00:00:00Z',
    status: 'ACTIVE',
  },
  {
    componentId: 'comp-SPACER',
    sliceType: 'SPACER',
    label: 'Spacer',
    description: 'Vertical spacing element',
    icon: '↕️',
    category: 'layout',
    configurable: ['height'],
    minHeight: 16,
    singleton: false,
    version: '1.0.0',
    maintainedBy: 'HIVE Platform Team',
    createdAt: '2023-12-01T00:00:00Z',
    updatedAt: '2023-12-01T00:00:00Z',
    status: 'ACTIVE',
  },
  {
    componentId: 'comp-MARKET_BRIEFING_TEXT',
    sliceType: 'MARKET_BRIEFING_TEXT',
    label: 'Market Briefing Text',
    description: 'Structured market briefing sourced from a UCP content entry — section title, bullet-point key takeaways and regulatory disclaimer.',
    icon: '📋',
    category: 'insight',
    configurable: ['ucpContentId', 'sectionTitle', 'bulletPoints', 'disclaimer'],
    minHeight: 200,
    singleton: false,
    version: '1.0.0',
    maintainedBy: 'Wealth Content Team',
    createdAt: '2026-04-01T00:00:00Z',
    updatedAt: '2026-05-01T00:00:00Z',
    status: 'ACTIVE',
  },
  {
    componentId: 'comp-VIDEO_PLAYER',
    sliceType: 'VIDEO_PLAYER',
    label: 'Video Player',
    description: 'Inline video player linked to a UCP content asset — displays presenter name, title, and playback controls.',
    icon: '🎬',
    category: 'insight',
    configurable: ['ucpAssetId', 'title', 'presenterName', 'presenterTitle', 'autoplay', 'showCaption'],
    minHeight: 180,
    singleton: false,
    version: '1.0.0',
    maintainedBy: 'Wealth Content Team',
    createdAt: '2026-05-01T00:00:00Z',
    updatedAt: '2026-05-01T00:00:00Z',
    status: 'ACTIVE',
  },
  {
    componentId: 'comp-CONTACT_RM_CTA',
    sliceType: 'CONTACT_RM_CTA',
    label: 'Contact Your RM',
    description: 'Sticky full-width CTA button routing the customer to the Relationship Manager finder, optionally pre-seeded with a context topic.',
    icon: '📞',
    category: 'insight',
    configurable: ['label', 'subLabel', 'deepLink', 'backgroundColor', 'textColor', 'sticky'],
    minHeight: 56,
    singleton: true,
    version: '1.0.0',
    maintainedBy: 'Premier & Jade Team',
    createdAt: '2026-04-01T00:00:00Z',
    updatedAt: '2026-05-01T00:00:00Z',
    status: 'ACTIVE',
  },
  {
    componentId: 'comp-DEPOSIT_RATE_TABLE',
    sliceType: 'DEPOSIT_RATE_TABLE',
    label: 'Deposit Rate Table',
    description: 'Time deposit interest rate table — term and rate columns only.',
    icon: '🏦',
    category: 'wealth',
    configurable: ['sectionTitle', 'asAtDate', 'rates', 'footnote'],
    minHeight: 220,
    singleton: false,
    version: '1.0.0',
    maintainedBy: 'Wealth Product Team',
    createdAt: '2026-05-05T00:00:00Z',
    updatedAt: '2026-05-05T00:00:00Z',
    status: 'ACTIVE',
  },
  {
    componentId: 'comp-DEPOSIT_OPEN_CTA',
    sliceType: 'DEPOSIT_OPEN_CTA',
    label: 'Button CTA',
    description: 'Full-width "Open a Deposit" CTA button for deposit campaigns.',
    icon: '🏧',
    category: 'wealth',
    configurable: ['label', 'deepLink', 'backgroundColor', 'textColor'],
    minHeight: 56,
    singleton: false,
    version: '1.0.0',
    maintainedBy: 'Wealth Product Team',
    createdAt: '2026-05-05T00:00:00Z',
    updatedAt: '2026-05-05T00:00:00Z',
    status: 'ACTIVE',
  },
  {
    componentId: 'comp-DEPOSIT_FAQ',
    sliceType: 'DEPOSIT_FAQ',
    label: 'General FAQ',
    description: 'Collapsible FAQ accordion for deposit products — question/answer pairs.',
    icon: '❓',
    category: 'wealth',
    configurable: ['sectionTitle', 'items'],
    minHeight: 200,
    singleton: false,
    version: '1.0.0',
    maintainedBy: 'Wealth Product Team',
    createdAt: '2026-05-05T00:00:00Z',
    updatedAt: '2026-05-05T00:00:00Z',
    status: 'ACTIVE',
  },
];

// ─── Content Approval Flows (reuse OCDP AD groups) ───────────────────────────

export const CONTENT_APPROVAL_FLOWS: ContentApprovalFlow[] = [
  { flowId: 'caf-hk-wealth',  flowName: 'HK Wealth Content Approval',  marketId: 'HK',     bizLineId: 'WEALTH',    approverGroupId: 'HK-WEALTH-AD',     approverGroupName: 'HK Wealth AD Group' },
  { flowId: 'caf-hk-mktg',   flowName: 'HK Marketing Approval',       marketId: 'HK',     bizLineId: 'MARKETING', approverGroupId: 'HK-MARKETING-AD',  approverGroupName: 'HK Marketing AD Group' },
  { flowId: 'caf-sg-wealth',  flowName: 'SG Wealth Content Approval',  marketId: 'SG',     bizLineId: 'WEALTH',    approverGroupId: 'SG-WEALTH-AD',     approverGroupName: 'SG Wealth AD Group' },
  { flowId: 'caf-global',     flowName: 'Global Wealth Approval',      marketId: 'GLOBAL', bizLineId: null,        approverGroupId: 'GLOBAL-WEALTH-AD', approverGroupName: 'Global Wealth AD Group' },
];

// ─── Pages that reference each content asset (for delete-guard) ──────────────
// Map: assetId → array of page names that reference it

export const MOCK_PAGES_REFERENCING_ASSETS: Record<string, { pageId: string; pageName: string }[]> = {
  'asset-008': [{ pageId: 'fx-viewpoint-hk',       pageName: 'FX Viewpoint — EUR & GBP (HK)' }],
  'asset-001': [{ pageId: 'home-wealth-hk',         pageName: 'Home – Wealth Hub (HK)' }],
  'asset-002': [{ pageId: 'visa-promo-hk',          pageName: 'VISA Infinite Promo (HK)' }],
  'asset-006': [{ pageId: 'wechat-jade-hk',         pageName: 'WeChat Jade Campaign (HK)' }],
  'asset-009': [{ pageId: 'deposit-campaign-hk',    pageName: 'New Fund Deposit Campaign (HK)' }],
};
