import type {
  PageLayout, WorkflowEntry, AuditEntry, StaffUser,
  BizLine, AdGroup,
  ContentAsset, UIComponent, ContentApprovalFlow, PageTemplate,
} from '../types/ucp';

// ─── Biz Lines ────────────────────────────────────────────────────────────────

export const BIZ_LINES: BizLine[] = [
  { bizLineId: 'PAYMENT',     displayName: 'Payment & Cards',       description: 'Credit card, transaction pages',        active: true },
  { bizLineId: 'WEB_ENABLER', displayName: 'Web Enablement',        description: 'Core web infrastructure, navigation',   active: true },
  { bizLineId: 'LENDING',     displayName: 'Lending & Mortgage',    description: 'Loan, mortgage, overdraft pages',        active: true },
  { bizLineId: 'COLLECTION',  displayName: 'Collections',           description: 'Debt management, repayment pages',       active: true },
  { bizLineId: 'WEALTH',      displayName: 'Wealth & Investments',  description: 'Premier, Jade, investment pages',        active: true },
  { bizLineId: 'MARKETING',   displayName: 'Marketing & Campaigns', description: 'Campaign pages, promotional banners',    active: true },
];

export const AD_GROUPS: AdGroup[] = [
  { groupId: 'HK-WEALTH-AD',     groupName: 'HK Wealth AD Group',      marketId: 'HK',     bizLineId: 'WEALTH',      groupType: 'AD_GROUP' },
  { groupId: 'HK-PAYMENT-AD',    groupName: 'HK Payment AD Group',     marketId: 'HK',     bizLineId: 'PAYMENT',     groupType: 'AD_GROUP' },
  { groupId: 'HK-MARKETING-AD',  groupName: 'HK Marketing AD Group',   marketId: 'HK',     bizLineId: 'MARKETING',   groupType: 'AD_GROUP' },
  { groupId: 'CN-WEALTH-AD',     groupName: 'CN Wealth AD Group',      marketId: 'CN',     bizLineId: 'WEALTH',      groupType: 'AD_GROUP' },
  { groupId: 'SG-WEALTH-AD',     groupName: 'SG Wealth AD Group',      marketId: 'SG',     bizLineId: 'WEALTH',      groupType: 'AD_GROUP' },
  { groupId: 'GLOBAL-WEALTH-AD', groupName: 'Global Wealth AD Group',  marketId: 'GLOBAL', bizLineId: 'WEALTH',      groupType: 'AD_GROUP' },
  { groupId: 'HK-ADMIN-GRP',     groupName: 'HK Admin Group',          marketId: 'HK',     bizLineId: 'WEALTH',      groupType: 'ADMIN_GROUP' },
  { groupId: 'GLOBAL-ADMIN-GRP', groupName: 'Global Admin Group',      marketId: 'GLOBAL', bizLineId: 'WEALTH',      groupType: 'ADMIN_GROUP' },
  { groupId: 'HK-AUDIT-GRP',     groupName: 'HK Audit Group',          marketId: 'HK',     bizLineId: 'WEALTH',      groupType: 'AUDIT_GROUP' },
];

// ─── Mock pages ───────────────────────────────────────────────────────────────

export const DEFAULT_PAGE_LAYOUT: PageLayout = {
  pageId: 'home-hub-hk',
  name: 'Home Hub (HK)',
  pageType: 'HOME_HUB',
  description: 'Main Home Hub page for HK market',
  platform: 'all',
  locale: 'zh-TW',
  thumbnail: '💰',
  tags: ['wealth', 'home', 'hk'],
  bizLineId: 'WEALTH',
  groupId: 'HK-WEALTH-AD',
  authoringStatus: 'APPROVED',
  slices: [
    {
      instanceId: 'slice-header',
      type: 'HEADER_NAV',
      props: { title: '定期存款', searchPlaceholder: '搜尋功能、產品', showNotificationBell: true, showQRScanner: true },
      visible: true, locked: false,
    },
    {
      instanceId: 'slice-quick',
      type: 'QUICK_ACCESS',
      props: {
        items: [
          { id: 'q1', icon: '🌙', label: '朝朝寶',   deepLink: 'hsbc://wealth/morning-treasure' },
          { id: 'q2', icon: '💵', label: '借錢',     deepLink: 'hsbc://loan/apply' },
          { id: 'q3', icon: '↔️', label: '轉帳',     deepLink: 'hsbc://transfer' },
          { id: 'q4', icon: '📊', label: '賬戶總覽', deepLink: 'hsbc://accounts' },
        ],
      },
      visible: true, locked: false,
    },
    {
      instanceId: 'slice-promo-10',
      type: 'PROMO_BANNER',
      props: { title: '10分招財日', subtitle: '查帳單·學投資·優配置', ctaLabel: '點擊參與', ctaDeepLink: 'hsbc://campaign/finance-day', imageUrl: '', backgroundColor: '#E8F4FD', badgeText: '每月10日開啓' },
      visible: true, locked: false,
    },
    {
      instanceId: 'slice-wealth-sel',
      type: 'WEALTH_SELECTION',
      props: {
        sectionTitle: '財富精選',
        products: [
          { id: 'w1', productName: '活錢理財｜歷史天天正收益', tag: '代碼', yield7Day: '2.80%', riskLevel: 'R1低風險', redemption: '贖回T+1到帳', ctaLabel: '去看看', ctaDeepLink: 'hsbc://wealth/daily-positive', highlighted: true },
          { id: 'w2', productName: '主投債券', tag: '代碼', yield7Day: '3.04%', riskLevel: '歷史周周正', redemption: '成立以來…', ctaLabel: '查看', ctaDeepLink: 'hsbc://wealth/bond-fund' },
        ],
        moreDeepLink: 'hsbc://wealth/all',
      },
      visible: true, locked: false,
    },
    {
      instanceId: 'slice-ai',
      type: 'AI_ASSISTANT',
      props: { greeting: 'Hi，我是你的智能財富助理', avatarUrl: '' },
      visible: true, locked: false,
    },
    {
      instanceId: 'slice-wealth-studio',
      type: 'WEALTH_STUDIO_CAROUSEL',
      props: {
        sectionTitle: 'Premier Elite Wealth Studio',
        moreLabel: 'View all',
        moreDeepLink: 'hsbc://wealth-studio',
        items: [
          {
            id: 'ws-ep14',
            ucpAssetId: 'asset-014',
            title: 'Navigating Markets in 2026',
            episodeLabel: 'Episode 14',
            presenter: 'Emily Cheung',
            presenterTitle: 'Senior Wealth Strategist, HSBC Premier',
            durationSeconds: 90,
            thumbnailUrl: 'http://localhost:4000/media/fx-viewpoint-thumbnail.jpg',
            videoUrl: 'http://localhost:4000/media/Wealth1.mp4',
          },
          {
            id: 'ws-ep15',
            ucpAssetId: 'asset-015',
            title: 'Gold & Alternative Assets',
            episodeLabel: 'Episode 15',
            presenter: 'Derek Lam',
            presenterTitle: 'Head of Alternative Investments, HSBC Jade',
            durationSeconds: 145,
            thumbnailUrl: 'http://localhost:4000/media/fx-viewpoint-thumbnail.jpg',
            videoUrl: 'http://localhost:4000/media/Wealth2.mp4',
          },
        ],
      },
      visible: true, locked: false,
    },
  ],
};

export const JADE_CAMPAIGN_PAGE: PageLayout = {
  pageId: 'jade-upgrade-hk',
  name: 'Elite Upgrade Campaign (HK)',
  pageType: 'CAMPAIGN',
  description: 'Elite upgrade invitation page for Premier customers with curated wealth and lifestyle privileges',
  platform: 'all',
  locale: 'zh-TW',
  thumbnail: '💎',
  tags: ['elite', 'wealth', 'campaign', 'wechat'],
  bizLineId: 'WEALTH',
  groupId: 'HK-WEALTH-AD',
  authoringStatus: 'APPROVED',
  slices: [
    {
      instanceId: 'elite-hero',
      type: 'CAMPAIGN_HERO',
      props: {
        headline: 'HSBC Elite 升級邀請',
        subHeadline: '專為合資格Premier客戶而設，結合專屬財富策劃、環球銀行服務及生活禮遇。',
        badge: 'WeChat限時邀請',
        bgGradient: 'linear-gradient(160deg,#0D5C3A 0%,#1A1A2E 100%)',
        accentColor: '#C9A84C',
      },
      visible: true, locked: false,
    },
    {
      instanceId: 'elite-ad',
      type: 'PROMO_BANNER',
      props: {
        title: '預約Elite升級諮詢',
        subtitle: '即日起透過WeChat提交升級意向，可獲專人跟進資格及財富需要。',
        ctaLabel: '立即升級',
        ctaDeepLink: 'hsbc://elite/upgrade/apply',
        imageUrl: 'https://placehold.co/900x500/0D5C3A/C9A84C?text=HSBC+Elite+Upgrade',
        backgroundColor: '#0D5C3A',
        badgeText: '限時禮遇',
      },
      visible: true, locked: false,
    },
    {
      instanceId: 'elite-benefits',
      type: 'CAMPAIGN_BENEFITS',
      props: {
        sectionTitle: 'Elite專屬禮遇',
        items: [
          { icon: '💎', title: '專屬財富團隊', description: '由資深Relationship Manager及財富顧問跟進您的投資及保障需要。' },
          { icon: '🌍', title: '環球銀行支援', description: '跨境戶口、外匯及海外生活安排支援，配合家庭及事業規劃。' },
          { icon: '📈', title: '投資方案優先資訊', description: '獲取市場觀點、基金焦點及多元資產配置建議。' },
          { icon: '🎭', title: '生活及活動禮遇', description: '精選餐飲、旅遊及會員活動邀請，提升日常銀行體驗。' },
        ],
        benefits: [
          { icon: '💎', title: '專屬財富團隊', desc: '由資深Relationship Manager及財富顧問跟進您的投資及保障需要。' },
          { icon: '🌍', title: '環球銀行支援', desc: '跨境戶口、外匯及海外生活安排支援，配合家庭及事業規劃。' },
          { icon: '📈', title: '投資方案優先資訊', desc: '獲取市場觀點、基金焦點及多元資產配置建議。' },
          { icon: '🎭', title: '生活及活動禮遇', desc: '精選餐飲、旅遊及會員活動邀請，提升日常銀行體驗。' },
        ],
      },
      visible: true, locked: false,
    },
    {
      instanceId: 'elite-rm',
      type: 'CONTACT_RM_CTA',
      props: {
        label: '聯絡客戶經理',
        subLabel: '查詢Elite升級資格及專屬優惠',
        deepLink: 'hsbc://rm/contact?campaign=elite-upgrade-hk',
        backgroundColor: '#0D5C3A',
        textColor: '#FFFFFF',
        sticky: false,
      },
      visible: true, locked: false,
    },
    {
      instanceId: 'elite-upgrade-cta',
      type: 'CAMPAIGN_CTA',
      props: {
        primaryLabel: '立即升級',
        primaryUrl: 'hsbc://elite/upgrade/apply',
        subNote: '提交後將由HSBC專人跟進，優惠受條款及資格審批約束。',
        secondaryLabel: '了解Elite服務',
        secondaryUrl: 'hsbc://elite/upgrade/learn',
        offerBadge: 'WeChat專屬升級通道',
      },
      visible: true, locked: false,
    },
  ],
};

export const VISA_CAMPAIGN_PAGE: PageLayout = {
  pageId: 'visa-platinum-campaign',
  name: 'Visa Platinum Q3 Campaign',
  pageType: 'CAMPAIGN',
  description: 'Visa Platinum no-FX campaign for Q3 2026',
  platform: 'web',
  locale: 'en',
  thumbnail: '💳',
  tags: ['cards', 'campaign', 'visa'],
  bizLineId: 'PAYMENT',
  groupId: 'GLOBAL-WEALTH-AD',
  authoringStatus: 'DRAFT',
  slices: [],
};

export const OBKYC_PAGE_LAYOUT: PageLayout = {
  pageId: 'obkyc-journey',
  name: 'OBKYC – Account Opening Journey',
  pageType: 'KYC_JOURNEY',
  description: 'Open Banking KYC journey — 10-step mobile flow',
  platform: 'all',
  locale: 'en',
  thumbnail: '🪪',
  tags: ['kyc', 'onboarding'],
  bizLineId: 'WEB_ENABLER',
  groupId: 'HK-WEALTH-AD',
  authoringStatus: 'DRAFT',
  slices: [
    {
      instanceId: 'kyc-header',
      type: 'HEADER_NAV',
      props: { title: 'Account Opening', searchPlaceholder: 'Search', showNotificationBell: false, showQRScanner: false },
      visible: true, locked: true,
    },
    {
      instanceId: 'kyc-promo',
      type: 'PROMO_BANNER',
      props: { title: 'Open Banking Account Opening', subtitle: 'Complete your KYC in minutes. Regulated by HKMA.', ctaLabel: 'Begin Application', ctaDeepLink: 'hsbc://kyc/start', imageUrl: '', backgroundColor: '#E8F0FE', badgeText: 'HKMA Regulated' },
      visible: true, locked: false,
    },
  ],
};

export const MARKET_INSIGHT_PAGE: PageLayout = {
  pageId: 'fx-viewpoint-hk',
  name: 'FX Viewpoint — EUR & GBP (HK)',
  pageType: 'MARKET_INSIGHT',
  description: 'Market insight page: EUR and GBP analysis — ECB on hold and BoE rate cut. Includes video, briefing text and RM contact CTA.',
  platform: 'all',
  locale: 'en',
  thumbnail: '📈',
  tags: ['fx', 'market-insight', 'eur', 'gbp', 'wealth'],
  bizLineId: 'WEALTH',
  groupId: 'HK-WEALTH-AD',
  authoringStatus: 'APPROVED',
  slices: [
    {
      instanceId: 'mi-header',
      type: 'HEADER_NAV',
      props: { title: 'FX Viewpoint', showNotificationBell: false, showQRScanner: false, showBackButton: true },
      visible: true, locked: true,
    },
    {
      instanceId: 'mi-content-header',
      type: 'VIDEO_PLAYER',
      props: {
        ucpAssetId: 'asset-008',
        title: 'FX Viewpoint — EUR & GBP Market Insights (May 2026)',
        thumbnailUrl: 'http://localhost:4000/media/fx-viewpoint-thumbnail.jpg',
        videoUrl: 'http://localhost:4000/media/fx-viewpoint.mp4',
        presenterName: 'Jackie Wong',
        presenterTitle: 'FX Strategist, HSBC Global Research',
        autoplay: false,
        showCaption: true,
      },
      visible: true, locked: false,
    },
    {
      instanceId: 'mi-briefing',
      type: 'MARKET_BRIEFING_TEXT',
      props: {
        ucpContentId: 'ucp-content-fx-viewpoint-001',
        sectionTitle: 'Key takeaways',
        bulletPoints: [
          'A weak USD is likely to persist into 2026, providing temporary support for the EUR and GBP.',
          'With the ECB expected to maintain its policy rate in 2026, the EUR should remain broadly stable.',
          'BoE delivered a 25 bps cut in May 2026 — further easing is data-dependent and market pricing appears stretched.',
          'GBP/USD faces near-term resistance at 1.3200 amid mixed UK growth signals.',
          'Investors should consider diversified FX exposure to manage downside risk against a volatile USD backdrop.',
        ],
        disclaimer: 'This material is issued by HSBC and is for information purposes only. It does not constitute investment advice or a recommendation to buy or sell any financial instrument.',
      },
      visible: true, locked: false,
    },
    {
      instanceId: 'mi-contact-rm',
      type: 'CONTACT_RM_CTA',
      props: {
        label: 'Contact Your RM',
        subLabel: 'Speak to your Relationship Manager about FX opportunities',
        deepLink: 'hsbc://rm/contact?context=fx-viewpoint',
        backgroundColor: '#DB0011',
        textColor: '#FFFFFF',
        sticky: true,
      },
      visible: true, locked: false,
    },
  ],
};

const DEPOSIT_LEGAL_PROPS = {
  schemaType: 'schema.org/WebPage',
  lastReviewedDate: '2026-05-17',
  copyrightText: '© 版权所有。汇丰银行（中国）有限公司2026',
  publicSecurityText: '沪公网安备 31011502400282号',
  publicSecurityUrl: 'https://beian.mps.gov.cn/#/query/webSearch',
  icpText: '沪ICP备15029387-3号',
  icpUrl: 'https://beian.miit.gov.cn/#/Integrated/index',
  jsonLd: JSON.stringify({
    '@context': 'https://schema.org',
    '@type': 'FinancialProduct',
    name: '汇丰中国新资金存款优惠',
    provider: {
      '@type': 'BankOrCreditUnion',
      name: '汇丰银行（中国）有限公司',
    },
    areaServed: 'CN',
    category: 'Time Deposit',
    dateModified: '2026-05-17',
  }),
};

const DEPOSIT_INSURANCE_PROPS = {
  title: '存款保险',
  logoUrl: '/media/deposit-insurance-logo.jpg',
  altText: '存款保险标识',
  linkUrl: 'https://www.hsbc.com.cn/content/dam/hsbc/cn/docs/insurance/insurance-prodcut-electronic-notice.pdf',
};

export const DEPOSIT_CAMPAIGN_PAGE: PageLayout = {
  pageId: 'deposit-campaign-cn',
  name: 'New Fund Deposit Campaign (CN)',
  pageType: 'CAMPAIGN',
  description: '汇丰中国人民币新资金定期存款优惠页面，包含利率表、常见问题、存款保险及合规备案信息。',
  platform: 'all',
  locale: 'zh-CN',
  supportedLocales: ['zh-CN', 'en'],
  translations: {
    en: {
      'dep-header': { title: 'Renminbi Savings Offers' },
      'dep-cd-rate-banner': {
        title: 'Up to 1.15% p.a. Annual Equivalent Rate',
        subtitle: '3-Month New Fund CNY Transferable CD exclusively for new deposits. Start earning more with HSBC China today.',
        badgeText: 'New funds only',
      },
      'dep-rate-table': {
        sectionTitle: 'Time Deposit Rates',
        footnote: 'Minimum balance for Personal Banking customers is RMB50. New Fund refers to eligible funds newly deposited with HSBC China. Rates are for reference only and are subject to change.',
      },
      'dep-open-cta': { label: 'Open a Deposit' },
      'dep-faq': { sectionTitle: 'Frequently Asked Questions' },
      'dep-insurance': { title: 'Deposit Insurance', altText: 'Deposit Insurance logo' },
      'dep-legal-jsonld': {
        copyrightText: '© Copyright. HSBC Bank (China) Company Limited 2026',
        publicSecurityText: 'Shanghai public security filing No. 31011502400282',
        icpText: 'Shanghai ICP No. 15029387-3',
      },
    },
  },
  thumbnail: '🏦',
  tags: ['deposit', 'savings', 'campaign', 'renminbi', 'time-deposit', 'seo', 'aeo', 'sensordata'],
  bizLineId: 'WEALTH',
  groupId: 'CN-WEALTH-AD',
  authoringStatus: 'APPROVED',
  slices: [
    {
      instanceId: 'dep-header',
      type: 'HEADER_NAV',
      props: {
        title: '人民币存款优惠',
        showNotificationBell: false,
        showQRScanner: false,
        showBackButton: true,
      },
      visible: true,
      locked: true,
    },
    {
      instanceId: 'dep-image-banner',
      type: 'PROMO_BANNER',
      props: {
        imageUrl: '/media/deposit-campaign-banner.jpg',
        ucpAssetId: 'asset-009',
        backgroundColor: '#FFFFFF',
      },
      visible: true,
      locked: false,
    },
    {
      instanceId: 'dep-cd-rate-banner',
      type: 'PROMO_BANNER',
      props: {
        title: '年化利率最高 1.15%',
        subtitle: '3个月人民币新资金可转让存单优惠，适用于符合条件的新转入资金。把握限时机会，让闲置资金更有效运用。',
        badgeText: '仅限新资金',
        backgroundColor: '#FFF7ED',
        textColor: '#92400E',
      },
      visible: true,
      locked: false,
    },
    {
      instanceId: 'dep-rate-table',
      type: 'DEPOSIT_RATE_TABLE',
      props: {
        sectionTitle: '定期存款利率',
        asAtDate: '2025/05/22',
        rates: [
          { term: '3个月定期存款',  rate: '0.65' },
          { term: '6个月定期存款',  rate: '0.85' },
          { term: '12个月定期存款', rate: '0.95' },
          { term: '24个月定期存款', rate: '1.05' },
          { term: '36个月定期存款', rate: '1.25' },
          { term: '60个月定期存款', rate: '1.30' },
        ],
        footnote: '个人银行客户定期存款起存金额为人民币50元。新资金指符合条件的新转入汇丰中国资金。利率仅供参考，并可能不时调整。',
      },
      visible: true,
      locked: false,
    },
    {
      instanceId: 'dep-open-cta',
      type: 'DEPOSIT_OPEN_CTA',
      props: {
        label: '立即开立存款',
        deepLink: 'hsbc-cn://deposit/open?currency=CNY&campaign=new-fund',
        fallback: {
          ios: 'https://apps.apple.com/cn/app/hsbc-china/id1467398731',
          android: 'https://www.hsbc.com.cn/mobile-banking/',
          huawei: 'appmarket://details?id=cn.com.hsbc.hsbcchina',
          xiaomi: 'mimarket://details?id=cn.com.hsbc.hsbcchina',
        },
        analytics: {
          provider: 'SensorsData',
          events: ['deposit_open_click', 'deposit_open_conversion'],
          metrics: ['dau', 'mau', 'click_rate', 'conversion_rate'],
        },
        backgroundColor: '#C41E3A',
        textColor: '#FFFFFF',
      },
      visible: true,
      locked: false,
    },
    {
      instanceId: 'dep-spacer',
      type: 'SPACER',
      props: { height: 16 },
      visible: true,
      locked: false,
    },
    {
      instanceId: 'dep-faq',
      type: 'DEPOSIT_FAQ',
      props: {
        sectionTitle: '常见问题',
        items: [
          {
            id: 'faq-1',
            question: '定期存款到期前可以提前支取吗？',
            answer: '可以。提前支取可能无法享受原定利率，利息可能减少或为零，并可能产生相关费用。具体规则以汇丰中国实际办理要求为准。',
          },
          {
            id: 'faq-2',
            question: '到期后没有支取会怎样？',
            answer: '您可在办理时选择到期处理方式，例如到期支取或自动续存。自动续存时通常将按续存当日适用利率执行。',
          },
          {
            id: 'faq-3',
            question: '可选择哪些存期？',
            answer: '常见存期包括3个月、6个月、12个月、24个月、36个月及60个月。不同存期对应不同利率，您可根据资金安排选择。',
          },
          {
            id: 'faq-4',
            question: '为什么定期存款利率通常高于活期存款？',
            answer: '定期存款在约定期限内保持资金稳定，因此银行通常可提供高于活期存款的利率。实际利率以办理时页面或网点公示为准。',
          },
        ],
      },
      visible: true,
      locked: false,
    },
    {
      instanceId: 'dep-insurance',
      type: 'DEPOSIT_INSURANCE',
      props: DEPOSIT_INSURANCE_PROPS,
      visible: true,
      locked: false,
    },
    {
      instanceId: 'dep-legal-jsonld',
      type: 'JSON_LD_STRUCTURED_DATA',
      props: { ...DEPOSIT_LEGAL_PROPS, hidden: true, webOnly: true, outputChannels: ['WEB_STANDARD', 'web-sdui'] },
      visible: false,
      locked: false,
    },
  ],
};

export const ALL_PAGES: PageLayout[] = [
  DEFAULT_PAGE_LAYOUT,
  JADE_CAMPAIGN_PAGE,
  VISA_CAMPAIGN_PAGE,
  OBKYC_PAGE_LAYOUT,
  MARKET_INSIGHT_PAGE,
  DEPOSIT_CAMPAIGN_PAGE,
];

// ─── Mock workflow entries ────────────────────────────────────────────────────

export const MOCK_WORKFLOW_ENTRIES: WorkflowEntry[] = [
  {
    entryId: 'wf-001',
    pageId: 'home-hub-hk',
    pageName: 'Home Hub (HK)',
    status: 'LIVE',
    authorId: 'j.chan@hsbc.com.hk',
    authorName: 'Janet Chan',
    comments: [],
    layout: DEFAULT_PAGE_LAYOUT,
    version: 3,
  },
  {
    entryId: 'wf-002',
    pageId: 'jade-upgrade-hk',
    pageName: 'Elite Upgrade Campaign (HK)',
    status: 'LIVE',
    authorId: 'j.chan@hsbc.com.hk',
    authorName: 'Janet Chan',
    comments: [],
    layout: JADE_CAMPAIGN_PAGE,
    version: 2,
  },
  {
    entryId: 'wf-003',
    pageId: 'visa-platinum-campaign',
    pageName: 'Visa Platinum Q3 Campaign',
    status: 'DRAFT',
    authorId: 'j.chan@hsbc.com.hk',
    authorName: 'Janet Chan',
    comments: [],
    layout: VISA_CAMPAIGN_PAGE,
    version: 1,
  },
  {
    entryId: 'wf-004',
    pageId: 'obkyc-journey',
    pageName: 'OBKYC – Account Opening Journey',
    status: 'DRAFT',
    authorId: 'k.lee@hsbc.com.hk',
    authorName: 'Karen Lee',
    comments: [],
    layout: OBKYC_PAGE_LAYOUT,
    version: 1,
  },
  {
    entryId: 'wf-005',
    pageId: 'fx-viewpoint-hk',
    pageName: 'FX Viewpoint — EUR & GBP (HK)',
    status: 'LIVE',
    authorId: 'j.chan@hsbc.com.hk',
    authorName: 'Janet Chan',
    comments: [],
    layout: MARKET_INSIGHT_PAGE,
    version: 1,
  },
  {
    entryId: 'wf-006',
    pageId: 'deposit-campaign-cn',
    pageName: 'New Fund Deposit Campaign (CN)',
    status: 'LIVE',
    authorId: 'j.chan@hsbc.com.hk',
    authorName: 'Janet Chan',
    comments: [],
    layout: DEPOSIT_CAMPAIGN_PAGE,
    version: 1,
  },
];

// ─── Mock audit log ───────────────────────────────────────────────────────────

export const MOCK_AUDIT: AuditEntry[] = [
  {
    id: 'a-001',
    timestamp: new Date(Date.now() - 86400000 * 10).toISOString(),
    actorId: 'j.chan@hsbc.com.hk',
    actorRole: 'WEALTH-AUTHOR',
    action: 'PAGE_CREATED',
    pageId: 'home-hub-hk',
    pageName: 'Home Hub (HK)',
    details: 'Initial page draft',
    bizLineId: 'WEALTH',
  },
  {
    id: 'a-002',
    timestamp: new Date(Date.now() - 86400000 * 9).toISOString(),
    actorId: 'j.chan@hsbc.com.hk',
    actorRole: 'WEALTH-AUTHOR',
    action: 'PAGE_APPROVED',
    pageId: 'home-hub-hk',
    pageName: 'Home Hub (HK)',
    details: 'Approved v3',
    bizLineId: 'WEALTH',
  },
  {
    id: 'a-003',
    timestamp: new Date(Date.now() - 86400000 * 5).toISOString(),
    actorId: 'j.chan@hsbc.com.hk',
    actorRole: 'WEALTH-AUTHOR',
    action: 'PAGE_CREATED',
    pageId: 'visa-platinum-campaign',
    pageName: 'Visa Platinum Q3 Campaign',
    details: 'Draft created',
    bizLineId: 'PAYMENT',
  },
  {
    id: 'a-004',
    timestamp: new Date(Date.now() - 86400000 * 3).toISOString(),
    actorId: 'k.lee@hsbc.com.hk',
    actorRole: 'PAYMENT-AUTHOR',
    action: 'SLICE_ADDED',
    pageId: 'visa-platinum-campaign',
    pageName: 'Visa Platinum Q3 Campaign',
    details: 'Added PROMO_BANNER',
    bizLineId: 'PAYMENT',
  },
];

// ─── Staff user roster ────────────────────────────────────────────────────────

export const MOCK_USERS: StaffUser[] = [
  { id: 'j.chan@hsbc.com.hk',  name: 'Janet Chan',    email: 'j.chan@hsbc.com.hk',  role: 'WEALTH-AUTHOR',   marketId: 'HK',     bizLineId: 'WEALTH',  groupId: 'HK-WEALTH-AD' },
  { id: 'm.wong@hsbc.com.hk',  name: 'Michael Wong',  email: 'm.wong@hsbc.com.hk',  role: 'WEALTH-APPROVER', marketId: 'HK',     bizLineId: 'WEALTH',  groupId: 'HK-WEALTH-AD' },
  { id: 'k.lee@hsbc.com.hk',   name: 'Karen Lee',     email: 'k.lee@hsbc.com.hk',   role: 'PAYMENT-AUTHOR',  marketId: 'HK',     bizLineId: 'PAYMENT', groupId: 'HK-PAYMENT-AD' },
  { id: 'b.lam@hsbc.com.hk',   name: 'Brian Lam',     email: 'b.lam@hsbc.com.hk',   role: 'ADMIN',           marketId: 'HK',     bizLineId: 'WEALTH',  groupId: 'HK-ADMIN-GRP', isGlobalAdmin: true },
  { id: 's.ng@hsbc.com.hk',    name: 'Sarah Ng',      email: 's.ng@hsbc.com.hk',    role: 'AUDITOR',         marketId: 'HK',     bizLineId: 'WEALTH',  groupId: 'HK-AUDIT-GRP' },
  { id: 'g.author@hsbc.com',   name: 'Global Author', email: 'g.author@hsbc.com',   role: 'WEALTH-AUTHOR',   marketId: 'GLOBAL', bizLineId: 'WEALTH',  groupId: 'GLOBAL-WEALTH-AD' },
];

// ─── Content Assets ───────────────────────────────────────────────────────────

const ASSET_I18N_DEFAULTS = { supportedLocales: ['en'] as string[], translations: {} as Record<string, Record<string, string>> };

export const MOCK_CONTENT_ASSETS: ContentAsset[] = [
  {
    ...ASSET_I18N_DEFAULTS,
    assetId: 'asset-010',
    name: 'Home Hub — Feature Product Background',
    assetType: 'IMAGE',
    mimeType: 'image/jpeg',
    sizeBytes: 128000,
    url: 'https://placehold.co/800x200/1A2E4A/ffffff?text=Feature+Product',
    thumbnailUrl: 'https://placehold.co/160x40/1A2E4A/ffffff?text=Feature+Product',
    altText: 'Background image for feature product fund list section',
    tags: ['home', 'hub', 'funds', 'wealth'],
    marketId: 'HK',
    bizLineId: 'WEALTH',
    uploadedBy: 'j.chan@hsbc.com.hk',
    uploadedByName: 'Janet Chan',
    uploadedAt: new Date(Date.now()).toISOString(),
    status: 'ACTIVE',
  },
  {
    ...ASSET_I18N_DEFAULTS,
    assetId: 'asset-011',
    name: 'Premier Elite Wealth Studio — Episode 13 Thumbnail',
    assetType: 'IMAGE',
    mimeType: 'image/jpeg',
    sizeBytes: 192000,
    url: 'https://placehold.co/800x450/1A1A2E/ffffff?text=Wealth+Studio+Ep13',
    thumbnailUrl: 'https://placehold.co/160x90/1A1A2E/ffffff?text=Ep13',
    altText: 'How AI experts think about AI — Wealth Studio Episode 13',
    tags: ['wealth-studio', 'premier', 'elite', 'video', 'ai'],
    marketId: 'HK',
    bizLineId: 'WEALTH',
    uploadedBy: 'j.chan@hsbc.com.hk',
    uploadedByName: 'Janet Chan',
    uploadedAt: new Date(Date.now()).toISOString(),
    status: 'ACTIVE',
  },
  {
    ...ASSET_I18N_DEFAULTS,
    assetId: 'asset-012',
    name: 'Investment 101 — Guides & Insights Article Cover',
    assetType: 'IMAGE',
    mimeType: 'image/jpeg',
    sizeBytes: 156000,
    url: 'https://placehold.co/800x450/2D3748/ffffff?text=Investment+101',
    thumbnailUrl: 'https://placehold.co/160x90/2D3748/ffffff?text=Invest+101',
    altText: 'Investment 101 — An investment in knowledge pays the best interest',
    tags: ['guides', 'insights', 'investment', 'education'],
    marketId: 'HK',
    bizLineId: 'WEALTH',
    uploadedBy: 'j.chan@hsbc.com.hk',
    uploadedByName: 'Janet Chan',
    uploadedAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    status: 'ACTIVE',
  },
  {
    ...ASSET_I18N_DEFAULTS,
    assetId: 'asset-013',
    name: 'Time Deposit — Up to 15.5% p.a. Discover More Card',
    assetType: 'IMAGE',
    mimeType: 'image/jpeg',
    sizeBytes: 144000,
    url: 'https://placehold.co/600x400/1A2E4A/ffffff?text=FX+Deposit+15.5%25',
    thumbnailUrl: 'https://placehold.co/120x80/1A2E4A/ffffff?text=FX+Deposit',
    altText: 'Up to 15.5% p.a. FX Deposit Rate campaign card',
    tags: ['deposit', 'fx', 'campaign', 'discover'],
    marketId: 'HK',
    bizLineId: 'WEALTH',
    uploadedBy: 'j.chan@hsbc.com.hk',
    uploadedByName: 'Janet Chan',
    uploadedAt: new Date(Date.now() - 86400000).toISOString(),
    status: 'ACTIVE',
  },
  {
    ...ASSET_I18N_DEFAULTS,
    assetId: 'asset-001',
    name: 'Jade Banner Hero',
    assetType: 'IMAGE',
    mimeType: 'image/jpeg',
    sizeBytes: 248320,
    url: 'https://placehold.co/1200x400/1a1a2e/c9a96e?text=Jade+Hero',
    thumbnailUrl: 'https://placehold.co/240x80/1a1a2e/c9a96e?text=Jade+Hero',
    altText: 'HSBC Jade Premier Banking hero banner',
    tags: ['jade', 'hero', 'banner'],
    marketId: 'HK',
    bizLineId: 'WEALTH',
    uploadedBy: 'j.chan@hsbc.com.hk',
    uploadedByName: 'Janet Chan',
    uploadedAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    status: 'ACTIVE',
  },
  {
    ...ASSET_I18N_DEFAULTS,
    assetId: 'asset-002',
    name: 'VISA Infinite Card Art',
    assetType: 'IMAGE',
    mimeType: 'image/png',
    sizeBytes: 184210,
    url: 'https://placehold.co/800x500/DB0011/ffffff?text=VISA+Infinite',
    thumbnailUrl: 'https://placehold.co/160x100/DB0011/ffffff?text=VISA+Infinite',
    altText: 'HSBC VISA Infinite credit card product image',
    tags: ['visa', 'credit-card', 'product'],
    marketId: 'GLOBAL',
    bizLineId: 'PAYMENT',
    uploadedBy: 'k.lee@hsbc.com.hk',
    uploadedByName: 'Karen Lee',
    uploadedAt: new Date(Date.now() - 86400000 * 12).toISOString(),
    status: 'ACTIVE',
  },
  {
    ...ASSET_I18N_DEFAULTS,
    assetId: 'asset-003',
    name: 'KYC Walkthrough Video',
    assetType: 'VIDEO',
    mimeType: 'video/mp4',
    sizeBytes: 18874368,
    url: 'https://placehold.co/1280x720/003366/ffffff?text=KYC+Video',
    thumbnailUrl: 'https://placehold.co/256x144/003366/ffffff?text=KYC+Video',
    altText: 'KYC onboarding walkthrough tutorial',
    tags: ['kyc', 'onboarding', 'tutorial'],
    marketId: 'HK',
    bizLineId: 'WEB_ENABLER',
    uploadedBy: 'j.chan@hsbc.com.hk',
    uploadedByName: 'Janet Chan',
    uploadedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    status: 'ACTIVE',
  },
  {
    ...ASSET_I18N_DEFAULTS,
    assetId: 'asset-004',
    name: 'HSBC Premier T&C PDF',
    assetType: 'DOCUMENT',
    mimeType: 'application/pdf',
    sizeBytes: 3145728,
    url: 'https://placehold.co/1x1/ffffff/ffffff?text=PDF',
    tags: ['terms', 'legal', 'premier'],
    marketId: 'HK',
    bizLineId: 'WEALTH',
    uploadedBy: 'j.chan@hsbc.com.hk',
    uploadedByName: 'Janet Chan',
    uploadedAt: new Date(Date.now() - 86400000 * 20).toISOString(),
    status: 'ACTIVE',
  },
  {
    ...ASSET_I18N_DEFAULTS,
    assetId: 'asset-005',
    name: 'Rate Sheet Q2 2026',
    assetType: 'FILE',
    mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    sizeBytes: 524288,
    url: 'https://placehold.co/1x1/ffffff/ffffff?text=XLSX',
    tags: ['rates', 'wealth', 'q2'],
    marketId: 'GLOBAL',
    bizLineId: 'WEALTH',
    uploadedBy: 'g.author@hsbc.com',
    uploadedByName: 'Global Author',
    uploadedAt: new Date(Date.now() - 86400000 * 8).toISOString(),
    status: 'ACTIVE',
  },
  {
    ...ASSET_I18N_DEFAULTS,
    assetId: 'asset-006',
    name: 'WeChat Campaign Banner',
    assetType: 'IMAGE',
    mimeType: 'image/jpeg',
    sizeBytes: 102400,
    url: 'https://placehold.co/900x500/07C160/ffffff?text=WeChat+Campaign',
    thumbnailUrl: 'https://placehold.co/180x100/07C160/ffffff?text=WeChat+Campaign',
    altText: 'WeChat Jade upgrade campaign banner',
    tags: ['wechat', 'campaign', 'jade'],
    marketId: 'HK',
    bizLineId: 'WEALTH',
    uploadedBy: 'j.chan@hsbc.com.hk',
    uploadedByName: 'Janet Chan',
    uploadedAt: new Date(Date.now() - 86400000 * 1).toISOString(),
    status: 'ACTIVE',
  },
  {
    ...ASSET_I18N_DEFAULTS,
    assetId: 'asset-008',
    name: 'FX Viewpoint — EUR & GBP Market Insights (May 2026)',
    assetType: 'VIDEO',
    mimeType: 'video/mp4',
    sizeBytes: 163549482,
    url: 'http://localhost:4000/media/fx-viewpoint.mp4',
    thumbnailUrl: 'http://localhost:4000/media/fx-viewpoint-thumbnail.jpg',
    altText: 'HSBC FX Viewpoint: EUR and GBP — ECB on hold and BoE cut rates. Presented by Jackie Wong.',
    tags: ['fx', 'viewpoint', 'eur', 'gbp', 'market-insight', 'wealth'],
    marketId: 'HK',
    bizLineId: 'WEALTH',
    uploadedBy: 'j.chan@hsbc.com.hk',
    uploadedByName: 'Janet Chan',
    uploadedAt: new Date(Date.now() - 86400000 * 1).toISOString(),
    status: 'ACTIVE',
    durationSeconds: 120,
    presenter: 'Jackie Wong',
    presenterTitle: 'FX Strategist, HSBC Global Research',
    approvalStatus: 'APPROVED',
    approvalGroupId: 'HK-WEALTH-AD',
    approvalReviewedAt: new Date(Date.now() - 86400000 * 1).toISOString(),
    approvalReviewerId: 'approver-01',
    approvalReviewerName: 'Amy Leung',
  },
  {
    ...ASSET_I18N_DEFAULTS,
    assetId: 'asset-007',
    name: 'Old Promo Banner 2025',
    assetType: 'IMAGE',
    mimeType: 'image/jpeg',
    sizeBytes: 196608,
    url: 'https://placehold.co/1200x400/888888/ffffff?text=Old+Banner',
    thumbnailUrl: 'https://placehold.co/240x80/888888/ffffff?text=Old+Banner',
    altText: 'Archived 2025 promo banner',
    tags: ['archived', 'promo'],
    marketId: 'HK',
    bizLineId: 'MARKETING',
    uploadedBy: 'k.lee@hsbc.com.hk',
    uploadedByName: 'Karen Lee',
    uploadedAt: new Date(Date.now() - 86400000 * 180).toISOString(),
    status: 'ARCHIVED',
  },
  {
    ...ASSET_I18N_DEFAULTS,
    assetId: 'asset-009',
    name: 'Deposit Campaign Hero Banner',
    assetType: 'IMAGE',
    mimeType: 'image/jpeg',
    sizeBytes: 312000,
    url: '/media/deposit-campaign-banner.jpg',
    thumbnailUrl: '/media/deposit-campaign-banner.jpg',
    altText: 'Father and child looking out over mountains and lake — Renminbi Savings new fund deposit campaign',
    tags: ['deposit', 'campaign', 'savings', 'renminbi', 'banner'],
    marketId: 'HK',
    bizLineId: 'WEALTH',
    uploadedBy: 'j.chan@hsbc.com.hk',
    uploadedByName: 'Janet Chan',
    uploadedAt: new Date(Date.now() - 86400000 * 0).toISOString(),
    status: 'ACTIVE',
    approvalStatus: 'APPROVED',
    approvalGroupId: 'HK-WEALTH-AD',
    approvalReviewedAt: new Date(Date.now()).toISOString(),
    approvalReviewerId: 'approver-01',
    approvalReviewerName: 'Michael Wong',
  },
  {
    ...ASSET_I18N_DEFAULTS,
    assetId: 'asset-020',
    name: 'Deposit Insurance',
    assetType: 'IMAGE',
    mimeType: 'image/jpeg',
    sizeBytes: 301380,
    url: '/media/deposit-insurance-logo.jpg',
    thumbnailUrl: '/media/deposit-insurance-logo.jpg',
    altText: '存款保险标识',
    tags: ['deposit', 'insurance', 'compliance', 'cn'],
    marketId: 'CN',
    bizLineId: 'WEALTH',
    uploadedBy: 'j.chan@hsbc.com.hk',
    uploadedByName: 'Janet Chan',
    uploadedAt: new Date(Date.now()).toISOString(),
    status: 'ACTIVE',
    approvalStatus: 'APPROVED',
    approvalGroupId: 'CN-WEALTH-AD',
    approvalReviewedAt: new Date(Date.now()).toISOString(),
    approvalReviewerId: 'approver-01',
    approvalReviewerName: 'Michael Wong',
    supportedLocales: ['zh-CN', 'en'],
    translations: {
      en: {
        name: 'Deposit Insurance',
        altText: 'Deposit Insurance logo',
      },
    },
  },
  {
    ...ASSET_I18N_DEFAULTS,
    assetId: 'asset-014',
    name: 'Wealth Studio — Episode 14: Navigating Markets in 2026',
    assetType: 'VIDEO',
    mimeType: 'video/quicktime',
    sizeBytes: 1304056,
    url: 'http://localhost:4000/media/Wealth1.mp4',
    thumbnailUrl: 'http://localhost:4000/media/fx-viewpoint-thumbnail.jpg',
    altText: 'Wealth Studio Episode 14 — Navigating Markets in 2026',
    tags: ['wealth-studio', 'premier', 'elite', 'video', 'market'],
    marketId: 'HK',
    bizLineId: 'WEALTH',
    uploadedBy: 'j.chan@hsbc.com.hk',
    uploadedByName: 'Janet Chan',
    uploadedAt: new Date(Date.now()).toISOString(),
    status: 'ACTIVE',
    durationSeconds: 90,
    presenter: 'Emily Cheung',
    presenterTitle: 'Senior Wealth Strategist, HSBC Premier',
    approvalStatus: 'APPROVED',
    approvalGroupId: 'HK-WEALTH-AD',
    approvalReviewedAt: new Date(Date.now()).toISOString(),
    approvalReviewerId: 'approver-01',
    approvalReviewerName: 'Michael Wong',
  },
  {
    ...ASSET_I18N_DEFAULTS,
    assetId: 'asset-015',
    name: 'Wealth Studio — Episode 15: Gold & Alternative Assets',
    assetType: 'VIDEO',
    mimeType: 'video/quicktime',
    sizeBytes: 2387501,
    url: 'http://localhost:4000/media/Wealth2.mp4',
    thumbnailUrl: 'http://localhost:4000/media/fx-viewpoint-thumbnail.jpg',
    altText: 'Wealth Studio Episode 15 — Gold & Alternative Assets',
    tags: ['wealth-studio', 'premier', 'elite', 'video', 'gold'],
    marketId: 'HK',
    bizLineId: 'WEALTH',
    uploadedBy: 'j.chan@hsbc.com.hk',
    uploadedByName: 'Janet Chan',
    uploadedAt: new Date(Date.now()).toISOString(),
    status: 'ACTIVE',
    durationSeconds: 145,
    presenter: 'Derek Lam',
    presenterTitle: 'Head of Alternative Investments, HSBC Jade',
    approvalStatus: 'APPROVED',
    approvalGroupId: 'HK-WEALTH-AD',
    approvalReviewedAt: new Date(Date.now()).toISOString(),
    approvalReviewerId: 'approver-01',
    approvalReviewerName: 'Michael Wong',
  },
];

// ─── UI Component Registry ────────────────────────────────────────────────────

const COMP_I18N_DEFAULTS = { supportedLocales: ['en'] as string[], translations: {} as Record<string, Record<string, string>> };

export const MOCK_UI_COMPONENTS: UIComponent[] = [
  {
    ...COMP_I18N_DEFAULTS,
    componentId: 'comp-HOME_SEARCH_HEADER',
    sliceType: 'HOME_SEARCH_HEADER',
    label: 'Home Search Header (All Segments)',
    description: 'Segment-adaptive header (red/jade/orange/silver) with integrated AI semantic search bar',
    icon: '🏠🔍',
    category: 'navigation',
    configurable: ['premierLabel', 'premierBg', 'eliteLabel', 'eliteBg', 'advanceLabel', 'advanceBg', 'massLabel', 'massBg', 'enableNotification', 'enableHeadset', 'placeholder', 'enableSemanticSearch', 'searchApiEndpoint'],
    minHeight: 104,
    singleton: true,
    version: '1.0.0',
    maintainedBy: 'HIVE Platform Team',
    createdAt: '2026-05-07T00:00:00Z',
    updatedAt: '2026-05-07T00:00:00Z',
    status: 'ACTIVE',
  },
  {
    ...COMP_I18N_DEFAULTS,
    componentId: 'comp-COMBO_QUICK_ACCESS',
    sliceType: 'COMBO_QUICK_ACCESS',
    label: 'Quick Access + Tab Bar (Combo)',
    description: 'Combined single card: content tab bar (My pick/Invest/Global/HK Daily) + function entry point rows with group assignment and reordering',
    icon: '⚡',
    category: 'navigation',
    configurable: ['tabs', 'row1Items', 'row2Items'],
    minHeight: 130,
    singleton: true,
    version: '1.0.0',
    maintainedBy: 'HIVE Platform Team',
    createdAt: '2026-05-07T00:00:00Z',
    updatedAt: '2026-05-07T00:00:00Z',
    status: 'ACTIVE',
  },
  {
    ...COMP_I18N_DEFAULTS,
    componentId: 'comp-CARD_ACTIVATION_BANNER',
    sliceType: 'CARD_ACTIVATION_BANNER',
    label: 'Card Activation Banner',
    description: 'Dismissible notification prompting the customer to activate their card',
    icon: '🔔',
    category: 'promotion',
    configurable: ['message', 'deepLink'],
    minHeight: 44,
    singleton: false,
    version: '1.0.0',
    maintainedBy: 'HIVE Platform Team',
    createdAt: '2026-05-07T00:00:00Z',
    updatedAt: '2026-05-07T00:00:00Z',
    status: 'ACTIVE',
  },
  {
    ...COMP_I18N_DEFAULTS,
    componentId: 'comp-QUEST_BANNER',
    sliceType: 'QUEST_BANNER',
    label: 'Quest / Getting Started Banner',
    description: 'Getting-started quest progress card with HSBC hexagon icon and red left border',
    icon: '🎯',
    category: 'promotion',
    configurable: ['title', 'description', 'ctaLabel', 'ctaDeepLink', 'totalQuests'],
    minHeight: 80,
    singleton: false,
    version: '1.0.0',
    maintainedBy: 'Wealth Product Team',
    createdAt: '2026-05-07T00:00:00Z',
    updatedAt: '2026-05-07T00:00:00Z',
    status: 'ACTIVE',
  },
  {
    ...COMP_I18N_DEFAULTS,
    componentId: 'comp-FEATURE_PRODUCT',
    sliceType: 'FEATURE_PRODUCT',
    label: 'Feature Product (Fund List)',
    description: 'Pill-button fund list showing 1Y returns with configurable filter URLs',
    icon: '📊',
    category: 'wealth',
    configurable: ['sectionTitle', 'buttons', 'activeButtonId', 'funds', 'moreLabel', 'moreDeepLink', 'bestSellingUrl'],
    minHeight: 200,
    singleton: false,
    version: '1.0.0',
    maintainedBy: 'Wealth Product Team',
    createdAt: '2026-05-07T00:00:00Z',
    updatedAt: '2026-05-07T00:00:00Z',
    status: 'ACTIVE',
  },
  {
    ...COMP_I18N_DEFAULTS,
    componentId: 'comp-WEALTH_STUDIO_CAROUSEL',
    sliceType: 'WEALTH_STUDIO_CAROUSEL',
    label: 'Wealth Studio Carousel',
    description: 'Premier Elite Wealth Studio horizontal video episode carousel',
    icon: '🎬',
    category: 'wealth',
    configurable: ['sectionTitle', 'items', 'moreLabel', 'moreDeepLink'],
    minHeight: 160,
    singleton: false,
    version: '1.0.0',
    maintainedBy: 'Premier & Jade Team',
    createdAt: '2026-05-07T00:00:00Z',
    updatedAt: '2026-05-07T00:00:00Z',
    status: 'ACTIVE',
  },
  {
    ...COMP_I18N_DEFAULTS,
    componentId: 'comp-GUIDES_INSIGHTS_CAROUSEL',
    sliceType: 'GUIDES_INSIGHTS_CAROUSEL',
    label: 'Guides & Insights',
    description: 'Article card carousel — investment guides and market insights',
    icon: '📰',
    category: 'insight',
    configurable: ['sectionTitle', 'items', 'moreLabel', 'moreDeepLink'],
    minHeight: 160,
    singleton: false,
    version: '1.0.0',
    maintainedBy: 'Wealth Content Team',
    createdAt: '2026-05-07T00:00:00Z',
    updatedAt: '2026-05-07T00:00:00Z',
    status: 'ACTIVE',
  },
  {
    ...COMP_I18N_DEFAULTS,
    componentId: 'comp-FX_WATCHLIST',
    sliceType: 'FX_WATCHLIST',
    label: 'FX Watchlist',
    description: 'Currency pair watchlist with Gold Forex Club tier badge and live rates',
    icon: '💱',
    category: 'wealth',
    configurable: ['sectionTitle', 'tierBadge', 'tierDescription', 'pairs', 'moreLabel', 'moreDeepLink'],
    minHeight: 200,
    singleton: false,
    version: '1.0.0',
    maintainedBy: 'Wealth Product Team',
    createdAt: '2026-05-07T00:00:00Z',
    updatedAt: '2026-05-07T00:00:00Z',
    status: 'ACTIVE',
  },
  {
    ...COMP_I18N_DEFAULTS,
    componentId: 'comp-DISCOVER_MORE_CAROUSEL',
    sliceType: 'DISCOVER_MORE_CAROUSEL',
    label: 'Discover More',
    description: 'Horizontal campaign card carousel — product promotions and lifestyle offers',
    icon: '🔎',
    category: 'promotion',
    configurable: ['sectionTitle', 'items'],
    minHeight: 160,
    singleton: false,
    version: '1.0.0',
    maintainedBy: 'Marketing Enablement Team',
    createdAt: '2026-05-07T00:00:00Z',
    updatedAt: '2026-05-07T00:00:00Z',
    status: 'ACTIVE',
  },
  {
    ...COMP_I18N_DEFAULTS,
    componentId: 'comp-HEADER_NAV',
    sliceType: 'HEADER_NAV',
    label: 'Header Navigation',
    description: 'Top bar with search, notification bell, QR scanner',
    icon: '🔝',
    category: 'navigation',
    configurable: ['title', 'searchPlaceholder', 'showNotificationBell', 'showQRScanner'],
    minHeight: 60,
    singleton: true,
    version: '2.3.1',
    maintainedBy: 'HIVE Platform Team',
    createdAt: '2024-03-15T00:00:00Z',
    updatedAt: '2025-11-02T00:00:00Z',
    status: 'ACTIVE',
  },
  {
    ...COMP_I18N_DEFAULTS,
    componentId: 'comp-QUICK_ACCESS',
    sliceType: 'QUICK_ACCESS',
    label: 'Quick Access Buttons',
    description: 'Row of primary product shortcuts (e.g. 朝朝宝, 借钱, 转账)',
    icon: '⚡',
    category: 'function',
    configurable: ['items'],
    minHeight: 80,
    singleton: true,
    version: '1.8.0',
    maintainedBy: 'HIVE Platform Team',
    createdAt: '2024-01-10T00:00:00Z',
    updatedAt: '2025-09-14T00:00:00Z',
    status: 'ACTIVE',
  },
  {
    ...COMP_I18N_DEFAULTS,
    componentId: 'comp-FUNCTION_GRID',
    sliceType: 'FUNCTION_GRID',
    label: 'Function Grid',
    description: 'Grid of function entry points with configurable columns, rows and labels',
    icon: '⊞',
    category: 'function',
    configurable: ['gridColumns', 'maxRows', 'showLabels', 'rows'],
    minHeight: 80,
    singleton: false,
    version: '1.0.0',
    maintainedBy: 'HIVE Platform Team',
    createdAt: '2026-05-08T00:00:00Z',
    updatedAt: '2026-05-08T00:00:00Z',
    status: 'ACTIVE',
  },
  {
    ...COMP_I18N_DEFAULTS,
    componentId: 'comp-PROMO_BANNER',
    sliceType: 'PROMO_BANNER',
    label: 'Promo Banner',
    description: 'Full-width campaign banner with image, title, CTA',
    icon: '🎪',
    category: 'promotion',
    configurable: ['title', 'subtitle', 'ctaLabel', 'ctaDeepLink', 'imageUrl', 'backgroundColor', 'badgeText'],
    minHeight: 120,
    singleton: false,
    version: '3.1.0',
    maintainedBy: 'Marketing Enablement Team',
    createdAt: '2024-02-01T00:00:00Z',
    updatedAt: '2026-01-20T00:00:00Z',
    status: 'ACTIVE',
  },
  {
    ...COMP_I18N_DEFAULTS,
    componentId: 'comp-AI_ASSISTANT',
    sliceType: 'AI_ASSISTANT',
    label: 'AI Assistant Entry',
    description: 'Intelligent wealth assistant greeting bar',
    icon: '🤖',
    category: 'function',
    configurable: ['greeting'],
    minHeight: 44,
    singleton: false,
    version: '1.2.0',
    maintainedBy: 'AI Team',
    createdAt: '2025-03-01T00:00:00Z',
    updatedAt: '2025-12-10T00:00:00Z',
    status: 'ACTIVE',
  },
  {
    ...COMP_I18N_DEFAULTS,
    componentId: 'comp-WEALTH_SELECTION',
    sliceType: 'WEALTH_SELECTION',
    label: 'Wealth Selection',
    description: 'Featured wealth products (7-day yield, risk level)',
    icon: '💰',
    category: 'wealth',
    configurable: ['sectionTitle', 'products', 'moreDeepLink'],
    minHeight: 280,
    singleton: false,
    version: '2.2.1',
    maintainedBy: 'Wealth Product Team',
    createdAt: '2024-02-28T00:00:00Z',
    updatedAt: '2026-02-15T00:00:00Z',
    status: 'ACTIVE',
  },
  {
    ...COMP_I18N_DEFAULTS,
    componentId: 'comp-SPACER',
    sliceType: 'SPACER',
    label: 'Spacer',
    description: 'Vertical spacing element',
    icon: '↕️',
    category: 'layout',
    configurable: ['height'],
    minHeight: 16,
    singleton: false,
    version: '1.0.0',
    maintainedBy: 'HIVE Platform Team',
    createdAt: '2023-12-01T00:00:00Z',
    updatedAt: '2023-12-01T00:00:00Z',
    status: 'ACTIVE',
  },
  {
    ...COMP_I18N_DEFAULTS,
    componentId: 'comp-MARKET_BRIEFING_TEXT',
    sliceType: 'MARKET_BRIEFING_TEXT',
    label: 'Market Briefing Text',
    description: 'Structured market briefing sourced from a UCP content entry — section title, bullet-point key takeaways and regulatory disclaimer.',
    icon: '📋',
    category: 'insight',
    configurable: ['ucpContentId', 'sectionTitle', 'bulletPoints', 'disclaimer'],
    minHeight: 200,
    singleton: false,
    version: '1.0.0',
    maintainedBy: 'Wealth Content Team',
    createdAt: '2026-04-01T00:00:00Z',
    updatedAt: '2026-05-01T00:00:00Z',
    status: 'ACTIVE',
  },
  {
    ...COMP_I18N_DEFAULTS,
    componentId: 'comp-VIDEO_PLAYER',
    sliceType: 'VIDEO_PLAYER',
    label: 'Video Player',
    description: 'Inline video player linked to a UCP content asset — displays presenter name, title, and playback controls.',
    icon: '🎬',
    category: 'insight',
    configurable: ['ucpAssetId', 'title', 'presenterName', 'presenterTitle', 'autoplay', 'showCaption'],
    minHeight: 180,
    singleton: false,
    version: '1.0.0',
    maintainedBy: 'Wealth Content Team',
    createdAt: '2026-05-01T00:00:00Z',
    updatedAt: '2026-05-01T00:00:00Z',
    status: 'ACTIVE',
  },
  {
    ...COMP_I18N_DEFAULTS,
    componentId: 'comp-CONTACT_RM_CTA',
    sliceType: 'CONTACT_RM_CTA',
    label: 'Contact Your RM',
    description: 'Sticky full-width CTA button routing the customer to the Relationship Manager finder, optionally pre-seeded with a context topic.',
    icon: '📞',
    category: 'insight',
    configurable: ['label', 'subLabel', 'deepLink', 'backgroundColor', 'textColor', 'sticky'],
    minHeight: 56,
    singleton: true,
    version: '1.0.0',
    maintainedBy: 'Premier & Jade Team',
    createdAt: '2026-04-01T00:00:00Z',
    updatedAt: '2026-05-01T00:00:00Z',
    status: 'ACTIVE',
  },
  {
    ...COMP_I18N_DEFAULTS,
    componentId: 'comp-DEPOSIT_RATE_TABLE',
    sliceType: 'DEPOSIT_RATE_TABLE',
    label: 'Deposit Rate Table',
    description: 'Time deposit interest rate table — term and rate columns only.',
    icon: '🏦',
    category: 'wealth',
    configurable: ['sectionTitle', 'asAtDate', 'rates', 'footnote'],
    minHeight: 220,
    singleton: false,
    version: '1.0.0',
    maintainedBy: 'Wealth Product Team',
    createdAt: '2026-05-05T00:00:00Z',
    updatedAt: '2026-05-05T00:00:00Z',
    status: 'ACTIVE',
  },
  {
    ...COMP_I18N_DEFAULTS,
    componentId: 'comp-DEPOSIT_OPEN_CTA',
    sliceType: 'DEPOSIT_OPEN_CTA',
    label: 'Button CTA',
    description: 'Full-width "Open a Deposit" CTA button for deposit campaigns.',
    icon: '🏧',
    category: 'wealth',
    configurable: ['label', 'deepLink', 'backgroundColor', 'textColor'],
    minHeight: 56,
    singleton: false,
    version: '1.0.0',
    maintainedBy: 'Wealth Product Team',
    createdAt: '2026-05-05T00:00:00Z',
    updatedAt: '2026-05-05T00:00:00Z',
    status: 'ACTIVE',
  },
  {
    ...COMP_I18N_DEFAULTS,
    componentId: 'comp-DEPOSIT_FAQ',
    sliceType: 'DEPOSIT_FAQ',
    label: 'General FAQ',
    description: 'Collapsible FAQ accordion for deposit products — question/answer pairs.',
    icon: '❓',
    category: 'wealth',
    configurable: ['sectionTitle', 'items'],
    minHeight: 200,
    singleton: false,
    version: '1.0.0',
    maintainedBy: 'Wealth Product Team',
    createdAt: '2026-05-05T00:00:00Z',
    updatedAt: '2026-05-05T00:00:00Z',
    status: 'ACTIVE',
  },
  {
    ...COMP_I18N_DEFAULTS,
    componentId: 'comp-DEPOSIT_INSURANCE',
    sliceType: 'DEPOSIT_INSURANCE',
    label: 'Deposit Insurance',
    description: 'Deposit insurance logo block that links to the official HSBC China electronic notice PDF.',
    icon: '🛡️',
    category: 'wealth',
    configurable: ['title', 'logoUrl', 'altText', 'linkUrl'],
    minHeight: 120,
    singleton: false,
    version: '1.0.0',
    maintainedBy: 'Wealth Product Team',
    createdAt: '2026-05-17T00:00:00Z',
    updatedAt: '2026-05-17T00:00:00Z',
    status: 'ACTIVE',
    supportedLocales: ['zh-CN', 'en'],
    translations: {
      en: {
        label: 'Deposit Insurance',
        description: 'Deposit insurance logo block that links to the official HSBC China electronic notice PDF.',
      },
    },
  },
  {
    ...COMP_I18N_DEFAULTS,
    componentId: 'comp-JSON_LD_STRUCTURED_DATA',
    sliceType: 'JSON_LD_STRUCTURED_DATA',
    label: 'JSON-LD Structured Data · hidden in output',
    description: 'Hidden Web Standard structured-data and China legal filing component for SEO/AEO output.',
    icon: '🗂️',
    category: 'layout',
    configurable: ['schemaType', 'copyrightText', 'publicSecurityText', 'publicSecurityUrl', 'icpText', 'icpUrl', 'jsonLd'],
    minHeight: 32,
    singleton: true,
    version: '1.0.0',
    maintainedBy: 'Web Enablement Team',
    createdAt: '2026-05-17T00:00:00Z',
    updatedAt: '2026-05-17T00:00:00Z',
    status: 'ACTIVE',
    supportedLocales: ['zh-CN', 'en'],
    translations: {
      en: {
        label: 'JSON-LD Structured Data · hidden in output',
        description: 'Hidden Web Standard structured-data and China legal filing component for SEO/AEO output.',
      },
    },
  },
  {
    ...COMP_I18N_DEFAULTS,
    componentId: 'comp-ANNOUNCEMENT_OVERLAY',
    sliceType: 'ANNOUNCEMENT_OVERLAY',
    label: 'Announcement Overlay',
    description: 'Full-screen dimmed announcement shell with selectable styles for maintenance notices, special announcements, journey-level forced updates and seasonal greetings.',
    icon: '📣',
    category: 'notice',
    configurable: ['scenario', 'styleVariant', 'contentRef', 'visual', 'title', 'body', 'hotlines', 'dontShowAgain', 'actions', 'expiry', 'priority', 'blockInteraction'],
    minHeight: 620,
    singleton: true,
    version: '1.0.0',
    maintainedBy: 'Mobile Experience Platform Team',
    createdAt: '2026-05-14T00:00:00Z',
    updatedAt: '2026-05-14T00:00:00Z',
    status: 'ACTIVE',
    meta: {
      scenarios: ['MAINTENANCE_NOTICE', 'SPECIAL_ANNOUNCEMENT', 'JOURNEY_FORCE_UPDATE', 'SEASONAL_GREETING'],
      styleVariants: ['NOTICE_CARD', 'ENVELOPE_CARD', 'INLINE_FORCE_UPDATE', 'FESTIVE_CARD'],
      supportedActions: ['dismiss', 'openUrl', 'callPhone', 'appUpdate', 'deepLink'],
    },
  },
  {
    ...COMP_I18N_DEFAULTS,
    componentId: 'comp-ANNOUNCEMENT_VISUAL',
    sliceType: 'ANNOUNCEMENT_VISUAL',
    label: 'Announcement Visual',
    description: 'Illustration, brand logo or seasonal artwork block for announcement cards.',
    icon: '🖼️',
    category: 'notice',
    configurable: ['assetId', 'imageUrl', 'altText', 'placement', 'backgroundColor', 'safeAreaTop'],
    minHeight: 160,
    singleton: false,
    version: '1.0.0',
    maintainedBy: 'Brand Design Systems Team',
    createdAt: '2026-05-14T00:00:00Z',
    updatedAt: '2026-05-14T00:00:00Z',
    status: 'ACTIVE',
  },
  {
    ...COMP_I18N_DEFAULTS,
    componentId: 'comp-ANNOUNCEMENT_BODY',
    sliceType: 'ANNOUNCEMENT_BODY',
    label: 'Announcement Body',
    description: 'Structured title, message paragraphs, bullet lines, hotline links and opt-out checkbox text.',
    icon: '📝',
    category: 'notice',
    configurable: ['headline', 'paragraphs', 'bulletItems', 'hotlines', 'dontShowAgainLabel', 'legalEntityText'],
    minHeight: 220,
    singleton: false,
    version: '1.0.0',
    maintainedBy: 'Content Engineering',
    createdAt: '2026-05-14T00:00:00Z',
    updatedAt: '2026-05-14T00:00:00Z',
    status: 'ACTIVE',
  },
  {
    ...COMP_I18N_DEFAULTS,
    componentId: 'comp-ANNOUNCEMENT_ACTIONS',
    sliceType: 'ANNOUNCEMENT_ACTIONS',
    label: 'Announcement Actions',
    description: 'Primary, secondary and tertiary actions for close, HSBC Website, hotline and app update flows.',
    icon: '➡️',
    category: 'notice',
    configurable: ['primaryAction', 'secondaryAction', 'tertiaryAction', 'layout', 'forcePrimary'],
    minHeight: 72,
    singleton: false,
    version: '1.0.0',
    maintainedBy: 'Mobile Experience Platform Team',
    createdAt: '2026-05-14T00:00:00Z',
    updatedAt: '2026-05-14T00:00:00Z',
    status: 'ACTIVE',
  },
];

// ─── Content Approval Flows (reuse OCDP AD groups) ───────────────────────────

export const CONTENT_APPROVAL_FLOWS: ContentApprovalFlow[] = [
  { flowId: 'caf-hk-wealth',  flowName: 'HK Wealth Content Approval',  marketId: 'HK',     bizLineId: 'WEALTH',    approverGroupId: 'HK-WEALTH-AD',     approverGroupName: 'HK Wealth AD Group' },
  { flowId: 'caf-hk-mktg',   flowName: 'HK Marketing Approval',       marketId: 'HK',     bizLineId: 'MARKETING', approverGroupId: 'HK-MARKETING-AD',  approverGroupName: 'HK Marketing AD Group' },
  { flowId: 'caf-sg-wealth',  flowName: 'SG Wealth Content Approval',  marketId: 'SG',     bizLineId: 'WEALTH',    approverGroupId: 'SG-WEALTH-AD',     approverGroupName: 'SG Wealth AD Group' },
  { flowId: 'caf-global',     flowName: 'Global Wealth Approval',      marketId: 'GLOBAL', bizLineId: null,        approverGroupId: 'GLOBAL-WEALTH-AD', approverGroupName: 'Global Wealth AD Group' },
];

// ─── Pages that reference each content asset (for delete-guard) ──────────────
// Map: assetId → array of page names that reference it

export const MOCK_PAGES_REFERENCING_ASSETS: Record<string, { pageId: string; pageName: string }[]> = {
  'asset-008': [{ pageId: 'fx-viewpoint-hk',       pageName: 'FX Viewpoint — EUR & GBP (HK)' }],
  'asset-001': [{ pageId: 'home-hub-hk',         pageName: 'Home Hub (HK)' }],
  'asset-002': [{ pageId: 'visa-promo-hk',          pageName: 'VISA Infinite Promo (HK)' }],
  'asset-006': [{ pageId: 'wechat-jade-hk',         pageName: 'WeChat Jade Campaign (HK)' }],
  'asset-009': [{ pageId: 'deposit-campaign-cn',    pageName: 'New Fund Deposit Campaign (CN)' }],
};

// ─── Page Templates ───────────────────────────────────────────────────────────

const TMPL_I18N_DEFAULTS = { supportedLocales: ['en'] as string[], translations: {} as Record<string, Record<string, string>> };

export const PAGE_TEMPLATES: PageTemplate[] = [
  {
    ...TMPL_I18N_DEFAULTS,
    templateId: 'tpl-generic',
    name: 'Generic Page',
    description: 'A blank page with only a standard HSBC header navigation bar. Use as a starting point for any custom page layout.',
    icon: '📄',
    channels: ['SDUI', 'WEB_STANDARD', 'WEB_WECHAT'],
    bizLineIds: ['PAYMENT', 'WEB_ENABLER', 'LENDING', 'COLLECTION', 'WEALTH', 'MARKETING'],
    category: 'generic',
    seoAeoCompliance: false,
    
    status: 'ACTIVE',
    createdAt: '2026-01-15T00:00:00Z',
    updatedAt: '2026-05-01T00:00:00Z',
    maintainedBy: 'Platform Team',
    usageCount: 42,
    starterSlices: [
      {
        type: 'HEADER_NAV',
        props: { title: '', showNotificationBell: true, showQRScanner: false, showBackButton: false },
        locked: false,
      },
    ],
  },
  {
    ...TMPL_I18N_DEFAULTS,
    templateId: 'tpl-web-standard',
    name: 'Web Standard Page',
    description: 'A fully SEO/AEO-optimised web page for HSBC.com. Includes the global nav header, breadcrumb, structured content area and compliant footer. Mandatory for all public Web Standard pages.',
    icon: '🌐',
    channels: ['WEB_STANDARD'],
    bizLineIds: ['PAYMENT', 'WEB_ENABLER', 'LENDING', 'COLLECTION', 'WEALTH', 'MARKETING'],
    category: 'generic',
    seoAeoCompliance: true,
    
    status: 'ACTIVE',
    createdAt: '2026-01-15T00:00:00Z',
    updatedAt: '2026-05-01T00:00:00Z',
    maintainedBy: 'Web Enablement Team',
    usageCount: 28,
    starterSlices: [
      {
        type: 'HEADER_NAV',
        props: { title: '', showNotificationBell: true, showQRScanner: false, showBackButton: false },
        locked: true,
      },
      {
        type: 'SEO_HERO_HEADER',
        props: { h1Title: 'Page Title — clear & keyword-rich', valueProp: 'One sentence that summarises the page value for users and search engines.', breadcrumb: 'Products' },
        locked: true,
      },
      {
        type: 'PROMO_BANNER',
        props: { title: 'Page Headline', subtitle: 'Supporting copy goes here', backgroundColor: '#F9FAFB' },
        locked: false,
      },
      {
        type: 'SEO_FAQ',
        props: { sectionTitle: 'Frequently Asked Questions', items: [{ q: 'What is this page about?', a: 'Describe the page in plain language.' }, { q: 'How do I get started?', a: 'Explain the first step clearly.' }, { q: 'Who should I contact for help?', a: 'Provide a support contact or link.' }] },
        locked: true,
      },
      {
        type: 'SEO_STRUCTURED_DATA',
        props: { schemaType: 'schema.org/WebPage', jsonLd: '{}' },
        locked: true,
      },
    ],
  },
  {
    ...TMPL_I18N_DEFAULTS,
    templateId: 'tpl-segment-upgrade-campaign',
    name: 'Segment Upgrade Campaign',
    description: 'WeChat campaign page for HSBC segment upgrade journeys (e.g. Premier→Elite, Advance→Premier). Includes hero banner, benefits grid and apply CTA. OCDP can compose Mini Program-style WXML/WXSS artifacts with WeChat share metadata and native CTA styling.',
    icon: '🏆',
    channels: ['WEB_WECHAT'],
    bizLineIds: ['WEALTH', 'MARKETING'],
    category: 'campaign',
    seoAeoCompliance: false,
    
    status: 'ACTIVE',
    createdAt: '2026-02-01T00:00:00Z',
    updatedAt: '2026-05-01T00:00:00Z',
    maintainedBy: 'Wealth Marketing Team',
    usageCount: 3,
    starterSlices: [
      {
        type: 'CAMPAIGN_HERO',
        props: {
          headline: 'Upgrade Your Banking Experience',
          subHeadline: 'Exclusive invitation for valued HSBC customers. Discover premium benefits designed for you.',
          badge: 'By Invitation Only',
          bgGradient: 'linear-gradient(160deg,#1D1D1B 0%,#2C2C2A 100%)',
          accentColor: '#C9A84C',
        },
        locked: false,
      },
      {
        type: 'CAMPAIGN_BENEFITS',
        props: {
          sectionTitle: 'Exclusive Privileges',
          items: [
            { icon: '💎', title: 'Premium Service', description: 'Dedicated Relationship Manager available 24/7' },
            { icon: '✈️', title: 'Travel Benefits', description: 'Global airport lounge access for you and guests' },
            { icon: '💰', title: 'Preferential Rates', description: 'Privileged FX rates and higher savings yields' },
            { icon: '🎯', title: 'Wealth Solutions', description: 'Access to exclusive investment products' },
          ],
        },
        locked: false,
      },
      {
        type: 'SPACER',
        props: { height: 16 },
        locked: false,
      },
      {
        type: 'CAMPAIGN_CTA',
        props: {
          primaryLabel: 'Apply Now',
          primaryUrl: 'hsbc://upgrade/apply',
          subNote: 'No annual fee in the first year',
          secondaryLabel: 'Learn More',
          secondaryUrl: 'hsbc://upgrade/learn',
        },
        locked: false,
      },
    ],
  },
  {
    ...TMPL_I18N_DEFAULTS,
    templateId: 'tpl-announcement-overlay',
    name: 'Announcement Overlay',
    description: 'Reusable app overlay template for Maintenance notice, Special Announcement, Journey-level forced app update and Seasonal Greetings. OCDP authors choose the scenario/style variant and bind reusable UCP announcement content, artwork and actions.',
    icon: '📣',
    channels: ['SDUI'],
    bizLineIds: ['WEB_ENABLER', 'MARKETING'],
    category: 'generic',
    seoAeoCompliance: false,
    status: 'ACTIVE',
    createdAt: '2026-05-14T00:00:00Z',
    updatedAt: '2026-05-14T00:00:00Z',
    maintainedBy: 'Mobile Experience Platform Team',
    usageCount: 1,
    starterSlices: [
      {
        type: 'ANNOUNCEMENT_OVERLAY',
        props: {
          scenario: 'SPECIAL_ANNOUNCEMENT',
          styleVariant: 'ENVELOPE_CARD',
          contentRef: { source: 'UCP', id: 'ucp-ann-special-taipo-fire-001' },
          visual: {
            assetId: 'asset-ann-envelope',
            imageUrl: 'http://localhost:4000/media/announcement-envelope.jpg',
            altText: 'HSBC special announcement envelope illustration',
            placement: 'envelope-top',
          },
          title: 'Special announcement',
          body: [
            "Your well-being is our priority. We're committed to supporting our customers affected by the Tai Po fire incident.",
            'If you need urgent assistance, please contact the following dedicated hotlines:',
          ],
          hotlines: [
            { label: 'HSBC Banking Services / HSBC Life Insurance', phone: '(852) 2233 3066' },
            { label: 'HSBC General Insurance (operated by AXA)', phone: '(852) 2894 4078' },
          ],
          dontShowAgain: { enabled: true, label: "Don't show this message again" },
          actions: [
            { id: 'close', label: 'Close', type: 'dismiss', style: 'primary', tone: 'dark' },
            { id: 'website', label: 'HSBC Website', type: 'openUrl', style: 'secondary', url: 'https://www.hsbc.com.hk/' },
          ],
          priority: 95,
          blockInteraction: true,
          legalEntityText: 'The Hongkong and Shanghai Banking Corporation Limited',
        },
        locked: false,
      },
    ],
  },
  {
    ...TMPL_I18N_DEFAULTS,
    templateId: 'tpl-credit-card-acquisition',
    name: 'Credit Card Acquisition',
    description: 'SEO/AEO-optimised Web Standard campaign page for credit card acquisition. Follows HSBC.com web standards including structured hero, feature benefits grid and compliant CTA with fee disclosure. Suitable for all credit card product campaigns targeting search and organic traffic.',
    icon: '💳',
    channels: ['WEB_STANDARD'],
    bizLineIds: ['PAYMENT', 'MARKETING'],
    category: 'campaign',
    seoAeoCompliance: true,
    status: 'ACTIVE',
    createdAt: '2026-02-15T00:00:00Z',
    updatedAt: '2026-05-01T00:00:00Z',
    maintainedBy: 'Payment Marketing Team',
    usageCount: 5,
    starterSlices: [
      {
        type: 'CAMPAIGN_HERO',
        props: {
          headline: 'HSBC [Card Name] Credit Card',
          subHeadline: 'Earn rewards with every purchase. Apply today and enjoy your first year fee waived.',
          badge: 'Limited Time Offer',
          bgGradient: 'linear-gradient(160deg,#0A1A3D 0%,#0D2B6B 60%,#1A3A8F 100%)',
          accentColor: '#C9A84C',
        },
        locked: false,
      },
      {
        type: 'SEO_HERO_HEADER',
        props: { h1Title: 'HSBC [Card Name] Credit Card', valueProp: 'Earn rewards on every purchase — apply today and get your first year annual fee waived.', breadcrumb: 'Credit Cards' },
        locked: true,
      },
      {
        type: 'CAMPAIGN_BENEFITS',
        props: {
          sectionTitle: 'Card Benefits',
          items: [
            { icon: '🌍', title: '0% Foreign Transaction Fee', description: 'No extra charges on overseas spending' },
            { icon: '✈️', title: 'Airport Lounge Access', description: '6 complimentary lounge visits per year' },
            { icon: '🛡️', title: 'Travel Insurance', description: 'Up to HKD 800,000 coverage automatically' },
            { icon: '🎭', title: 'Lifestyle Rewards', description: 'Earn 2x points on dining and entertainment' },
            { icon: '💎', title: 'Concierge Service', description: '24/7 global concierge for travel and dining' },
            { icon: '📱', title: 'Contactless & Pay', description: 'Apple Pay, Google Pay and Samsung Pay' },
          ],
        },
        locked: false,
      },
      {
        type: 'CAMPAIGN_CTA',
        props: {
          primaryLabel: 'Apply for This Card',
          primaryUrl: '/apply/credit-card',
          subNote: 'First Year Annual Fee Waived',
          secondaryLabel: 'Compare Cards',
          secondaryUrl: '/credit-cards/compare',
        },
        locked: false,
      },
      {
        type: 'SEO_FAQ',
        props: { sectionTitle: 'Frequently Asked Questions', items: [{ q: 'What is the annual fee?', a: 'The first year annual fee is waived. From year 2, the fee is HKD 2,000.' }, { q: 'How do I apply?', a: 'Click Apply Now and complete the online form in under 5 minutes.' }, { q: 'What rewards do I earn?', a: 'Earn 2x points on dining and entertainment, 1x on all other spend.' }] },
        locked: true,
      },
      {
        type: 'SEO_STRUCTURED_DATA',
        props: { schemaType: 'schema.org/FinancialProduct', jsonLd: '{}' },
        locked: true,
      },
    ],
  },
  {
    ...TMPL_I18N_DEFAULTS,
    templateId: 'tpl-deposit-campaign',
    name: 'Deposit Campaign',
    description: 'SDUI campaign page for China time deposit promotions. Delivered to iOS, Android, HarmonyNext and Web SDUI; web output includes hidden JSON-LD for SEO/AEO.',
    icon: '🏦',
    channels: ['SDUI', 'WEB_STANDARD'],
    bizLineIds: ['WEALTH', 'MARKETING'],
    category: 'campaign',
    seoAeoCompliance: true,
    status: 'ACTIVE',
    createdAt: '2026-03-01T00:00:00Z',
    updatedAt: '2026-05-01T00:00:00Z',
    maintainedBy: 'Wealth Product Team',
    usageCount: 2,
    starterSlices: [
      {
        type: 'HEADER_NAV',
        props: { title: 'Savings Offers', showNotificationBell: false, showQRScanner: false, showBackButton: true },
        locked: true,
      },
      {
        type: 'PROMO_BANNER',
        props: {
          title: '🌟 Exclusive Savings Rate',
          subtitle: 'Limited-time offer for new funds only. Open your time deposit today.',
          badgeText: '🔥 New Funds Only',
          backgroundColor: '#FFF7ED',
        },
        locked: false,
      },
      {
        type: 'DEPOSIT_RATE_TABLE',
        props: {
          sectionTitle: 'Time Deposit Rates:',
          asAtDate: '',
          rates: [
            { term: '3 Month', rate: '—' },
            { term: '6 Month', rate: '—' },
            { term: '12 Month', rate: '—' },
          ],
          footnote: 'New Fund refers to funds not previously held with HSBC. Minimum balance applies.',
        },
        locked: false,
      },
      {
        type: 'DEPOSIT_OPEN_CTA',
        props: { label: 'Open a Deposit', deepLink: 'hsbc://deposit/open', backgroundColor: '#C41E3A', textColor: '#FFFFFF' },
        locked: false,
      },
      {
        type: 'SPACER',
        props: { height: 16 },
        locked: false,
      },
      {
        type: 'DEPOSIT_FAQ',
        props: {
          sectionTitle: 'Frequently Asked Questions',
          items: [
            { id: 'faq-1', question: 'What is a time deposit?', answer: 'A time deposit is a savings product with a fixed term and a guaranteed interest rate.' },
            { id: 'faq-2', question: 'What is "New Fund"?', answer: 'New Fund refers to funds not previously held with HSBC. Transferring from another HSBC account does not qualify.' },
          ],
        },
        locked: false,
      },
      {
        type: 'DEPOSIT_INSURANCE',
        props: DEPOSIT_INSURANCE_PROPS,
        locked: false,
      },
      {
        type: 'JSON_LD_STRUCTURED_DATA',
        props: { ...DEPOSIT_LEGAL_PROPS, hidden: true, webOnly: true, outputChannels: ['WEB_STANDARD', 'web-sdui'] },
        locked: false,
      },
    ],
  },
];
