import type { UCPContentAsset } from '../types/ocdp';

// Fallback content assets shown when the UCP proxy is unavailable.
// Mirrors the data served by mock-bff /api/v1/ucp/content-assets.
export const FALLBACK_CONTENT_ASSETS: UCPContentAsset[] = [
  {
    assetId: 'asset-010',
    name: 'Home Hub — Feature Product Background',
    assetType: 'IMAGE',
    mimeType: 'image/jpeg',
    sizeBytes: 128000,
    url: 'https://placehold.co/800x200/1A2E4A/ffffff?text=Feature+Product',
    thumbnailUrl: 'https://placehold.co/160x40/1A2E4A/ffffff?text=Feature+Product',
    altText: 'Background image for feature product fund list section',
    tags: ['home', 'hub', 'funds', 'wealth'],
    marketId: 'HK', bizLineId: 'WEALTH',
    uploadedBy: 'j.chan@hsbc.com.hk', uploadedByName: 'Janet Chan',
    uploadedAt: '2026-05-07T00:00:00Z',
    status: 'ACTIVE',
  },
  {
    assetId: 'asset-011',
    name: 'Premier Elite Wealth Studio — Episode 13 Thumbnail',
    assetType: 'IMAGE',
    mimeType: 'image/jpeg',
    sizeBytes: 192000,
    url: 'https://placehold.co/800x450/1A1A2E/ffffff?text=Wealth+Studio+Ep13',
    thumbnailUrl: 'https://placehold.co/160x90/1A1A2E/ffffff?text=Ep13',
    altText: 'How AI experts think about AI — Wealth Studio Episode 13',
    tags: ['wealth-studio', 'premier', 'elite', 'video', 'ai'],
    marketId: 'HK', bizLineId: 'WEALTH',
    uploadedBy: 'j.chan@hsbc.com.hk', uploadedByName: 'Janet Chan',
    uploadedAt: '2026-05-07T00:00:00Z',
    status: 'ACTIVE',
  },
  {
    assetId: 'asset-012',
    name: 'Investment 101 — Guides & Insights Article Cover',
    assetType: 'IMAGE',
    mimeType: 'image/jpeg',
    sizeBytes: 156000,
    url: 'https://placehold.co/800x450/2D3748/ffffff?text=Investment+101',
    thumbnailUrl: 'https://placehold.co/160x90/2D3748/ffffff?text=Invest+101',
    altText: 'Investment 101 — An investment in knowledge pays the best interest',
    tags: ['guides', 'insights', 'investment', 'education'],
    marketId: 'HK', bizLineId: 'WEALTH',
    uploadedBy: 'j.chan@hsbc.com.hk', uploadedByName: 'Janet Chan',
    uploadedAt: '2026-05-04T00:00:00Z',
    status: 'ACTIVE',
  },
  {
    assetId: 'asset-013',
    name: 'Time Deposit — Up to 15.5% p.a. Discover More Card',
    assetType: 'IMAGE',
    mimeType: 'image/jpeg',
    sizeBytes: 144000,
    url: 'https://placehold.co/600x400/1A2E4A/ffffff?text=FX+Deposit+15.5%25',
    thumbnailUrl: 'https://placehold.co/120x80/1A2E4A/ffffff?text=FX+Deposit',
    altText: 'Up to 15.5% p.a. FX Deposit Rate campaign card',
    tags: ['deposit', 'fx', 'campaign', 'discover'],
    marketId: 'HK', bizLineId: 'WEALTH',
    uploadedBy: 'j.chan@hsbc.com.hk', uploadedByName: 'Janet Chan',
    uploadedAt: '2026-05-06T00:00:00Z',
    status: 'ACTIVE',
  },
  {
    assetId: 'asset-001',
    name: 'Jade Banner Hero',
    assetType: 'IMAGE',
    mimeType: 'image/jpeg',
    sizeBytes: 248320,
    url: 'https://placehold.co/1200x400/1a1a2e/c9a96e?text=Jade+Hero',
    thumbnailUrl: 'https://placehold.co/240x80/1a1a2e/c9a96e?text=Jade+Hero',
    altText: 'HSBC Jade Premier Banking hero banner',
    tags: ['jade', 'hero', 'banner'],
    marketId: 'HK', bizLineId: 'WEALTH',
    uploadedBy: 'j.chan@hsbc.com.hk', uploadedByName: 'Janet Chan',
    uploadedAt: '2026-05-01T00:00:00Z',
    status: 'ACTIVE',
  },
  {
    assetId: 'asset-002',
    name: 'VISA Infinite Card Art',
    assetType: 'IMAGE',
    mimeType: 'image/png',
    sizeBytes: 184210,
    url: 'https://placehold.co/800x500/DB0011/ffffff?text=VISA+Infinite',
    thumbnailUrl: 'https://placehold.co/160x100/DB0011/ffffff?text=VISA+Infinite',
    altText: 'HSBC VISA Infinite credit card product image',
    tags: ['visa', 'credit-card', 'product'],
    marketId: 'GLOBAL', bizLineId: 'PAYMENT',
    uploadedBy: 'k.lee@hsbc.com.hk', uploadedByName: 'Karen Lee',
    uploadedAt: '2026-04-24T00:00:00Z',
    status: 'ACTIVE',
  },
  {
    assetId: 'asset-003',
    name: 'KYC Walkthrough Video',
    assetType: 'VIDEO',
    mimeType: 'video/mp4',
    sizeBytes: 18874368,
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    thumbnailUrl: 'https://placehold.co/256x144/003366/ffffff?text=KYC+Video',
    altText: 'KYC onboarding walkthrough tutorial',
    tags: ['kyc', 'onboarding', 'tutorial'],
    marketId: 'HK', bizLineId: 'WEB_ENABLER',
    uploadedBy: 'j.chan@hsbc.com.hk', uploadedByName: 'Janet Chan',
    uploadedAt: '2026-05-04T00:00:00Z',
    status: 'ACTIVE',
    durationSeconds: 90,
    presenter: 'HSBC Digital Team',
    presenterTitle: 'Customer Onboarding',
  },
  {
    assetId: 'asset-004',
    name: 'HSBC Premier T&C PDF',
    assetType: 'DOCUMENT',
    mimeType: 'application/pdf',
    sizeBytes: 3145728,
    url: 'https://placehold.co/1x1/ffffff/ffffff?text=PDF',
    tags: ['terms', 'legal', 'premier'],
    marketId: 'HK', bizLineId: 'WEALTH',
    uploadedBy: 'j.chan@hsbc.com.hk', uploadedByName: 'Janet Chan',
    uploadedAt: '2026-04-16T00:00:00Z',
    status: 'ACTIVE',
  },
  {
    assetId: 'asset-006',
    name: 'WeChat Campaign Banner',
    assetType: 'IMAGE',
    mimeType: 'image/jpeg',
    sizeBytes: 102400,
    url: 'https://placehold.co/900x500/07C160/ffffff?text=WeChat+Campaign',
    thumbnailUrl: 'https://placehold.co/180x100/07C160/ffffff?text=WeChat+Campaign',
    altText: 'WeChat Jade upgrade campaign banner',
    tags: ['wechat', 'campaign', 'jade'],
    marketId: 'HK', bizLineId: 'WEALTH',
    uploadedBy: 'j.chan@hsbc.com.hk', uploadedByName: 'Janet Chan',
    uploadedAt: '2026-05-05T00:00:00Z',
    status: 'ACTIVE',
  },
  {
    assetId: 'asset-008',
    name: 'FX Viewpoint — EUR & GBP Market Insights (May 2026)',
    assetType: 'VIDEO',
    mimeType: 'video/mp4',
    sizeBytes: 52428800,
    url: 'http://localhost:4000/media/fx-viewpoint.mp4',
    thumbnailUrl: 'http://localhost:4000/media/fx-viewpoint-thumbnail.jpg',
    altText: 'HSBC FX Viewpoint: EUR and GBP — ECB on hold and BoE cut rates. Presented by Jackie Wong.',
    tags: ['fx', 'viewpoint', 'eur', 'gbp', 'market-insight', 'wealth'],
    marketId: 'HK', bizLineId: 'WEALTH',
    uploadedBy: 'j.chan@hsbc.com.hk', uploadedByName: 'Janet Chan',
    uploadedAt: '2026-05-05T00:00:00Z',
    status: 'ACTIVE',
    durationSeconds: 120,
    presenter: 'Jackie Wong',
    presenterTitle: 'FX Strategist, HSBC Global Research',
  },
  {
    assetId: 'asset-009',
    name: 'Deposit Campaign Hero Banner',
    assetType: 'IMAGE',
    mimeType: 'image/jpeg',
    sizeBytes: 312000,
    url: '/media/deposit-campaign-banner.jpg',
    thumbnailUrl: '/media/deposit-campaign-banner.jpg',
    altText: 'Father and child looking out over mountains and lake — Renminbi Savings new fund deposit campaign',
    tags: ['deposit', 'campaign', 'savings', 'renminbi', 'banner'],
    marketId: 'CN', bizLineId: 'WEALTH',
    uploadedBy: 'j.chan@hsbc.com.hk', uploadedByName: 'Janet Chan',
    uploadedAt: '2026-05-05T00:00:00Z',
    status: 'ACTIVE',
  },
  {
    assetId: 'asset-014',
    name: 'Wealth Studio — Episode 14: Navigating Markets in 2026',
    assetType: 'VIDEO',
    mimeType: 'video/quicktime',
    sizeBytes: 1304056,
    url: 'http://localhost:4000/media/Wealth1.mp4',
    thumbnailUrl: 'http://localhost:4000/media/fx-viewpoint-thumbnail.jpg',
    altText: 'Wealth Studio Episode 14 — Navigating Markets in 2026',
    tags: ['wealth-studio', 'premier', 'elite', 'video', 'market'],
    marketId: 'HK', bizLineId: 'WEALTH',
    uploadedBy: 'j.chan@hsbc.com.hk', uploadedByName: 'Janet Chan',
    uploadedAt: '2026-05-11T00:00:00Z',
    status: 'ACTIVE',
    durationSeconds: 90,
    presenter: 'Emily Cheung',
    presenterTitle: 'Senior Wealth Strategist, HSBC Premier',
  },
  {
    assetId: 'asset-015',
    name: 'Wealth Studio — Episode 15: Gold & Alternative Assets',
    assetType: 'VIDEO',
    mimeType: 'video/quicktime',
    sizeBytes: 2387501,
    url: 'http://localhost:4000/media/Wealth2.mp4',
    thumbnailUrl: 'http://localhost:4000/media/fx-viewpoint-thumbnail.jpg',
    altText: 'Wealth Studio Episode 15 — Gold & Alternative Assets',
    tags: ['wealth-studio', 'premier', 'elite', 'video', 'gold'],
    marketId: 'HK', bizLineId: 'WEALTH',
    uploadedBy: 'j.chan@hsbc.com.hk', uploadedByName: 'Janet Chan',
    uploadedAt: '2026-05-11T00:00:00Z',
    status: 'ACTIVE',
    durationSeconds: 145,
    presenter: 'Derek Lam',
    presenterTitle: 'Head of Alternative Investments, HSBC Jade',
  },
];
