import type { UCPContentAsset } from '../types/ocdp';

// Fallback content assets shown when the UCP proxy is unavailable.
// Mirrors the data served by mock-bff /api/v1/ucp/content-assets.
export const FALLBACK_CONTENT_ASSETS: UCPContentAsset[] = [
  {
    assetId: 'asset-001',
    name: 'Jade Banner Hero',
    assetType: 'IMAGE',
    mimeType: 'image/jpeg',
    sizeBytes: 248320,
    url: 'https://placehold.co/1200x400/1a1a2e/c9a96e?text=Jade+Hero',
    thumbnailUrl: 'https://placehold.co/240x80/1a1a2e/c9a96e?text=Jade+Hero',
    altText: 'HSBC Jade Premier Banking hero banner',
    tags: ['jade', 'hero', 'banner'],
    marketId: 'HK', bizLineId: 'WEALTH',
    uploadedBy: 'j.chan@hsbc.com.hk', uploadedByName: 'Janet Chan',
    uploadedAt: '2026-05-01T00:00:00Z',
    status: 'ACTIVE',
  },
  {
    assetId: 'asset-002',
    name: 'VISA Infinite Card Art',
    assetType: 'IMAGE',
    mimeType: 'image/png',
    sizeBytes: 184210,
    url: 'https://placehold.co/800x500/DB0011/ffffff?text=VISA+Infinite',
    thumbnailUrl: 'https://placehold.co/160x100/DB0011/ffffff?text=VISA+Infinite',
    altText: 'HSBC VISA Infinite credit card product image',
    tags: ['visa', 'credit-card', 'product'],
    marketId: 'GLOBAL', bizLineId: 'PAYMENT',
    uploadedBy: 'k.lee@hsbc.com.hk', uploadedByName: 'Karen Lee',
    uploadedAt: '2026-04-24T00:00:00Z',
    status: 'ACTIVE',
  },
  {
    assetId: 'asset-003',
    name: 'KYC Walkthrough Video',
    assetType: 'VIDEO',
    mimeType: 'video/mp4',
    sizeBytes: 18874368,
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    thumbnailUrl: 'https://placehold.co/256x144/003366/ffffff?text=KYC+Video',
    altText: 'KYC onboarding walkthrough tutorial',
    tags: ['kyc', 'onboarding', 'tutorial'],
    marketId: 'HK', bizLineId: 'WEB_ENABLER',
    uploadedBy: 'j.chan@hsbc.com.hk', uploadedByName: 'Janet Chan',
    uploadedAt: '2026-05-04T00:00:00Z',
    status: 'ACTIVE',
    durationSeconds: 90,
    presenter: 'HSBC Digital Team',
    presenterTitle: 'Customer Onboarding',
  },
  {
    assetId: 'asset-004',
    name: 'HSBC Premier T&C PDF',
    assetType: 'DOCUMENT',
    mimeType: 'application/pdf',
    sizeBytes: 3145728,
    url: 'https://placehold.co/1x1/ffffff/ffffff?text=PDF',
    tags: ['terms', 'legal', 'premier'],
    marketId: 'HK', bizLineId: 'WEALTH',
    uploadedBy: 'j.chan@hsbc.com.hk', uploadedByName: 'Janet Chan',
    uploadedAt: '2026-04-16T00:00:00Z',
    status: 'ACTIVE',
  },
  {
    assetId: 'asset-006',
    name: 'WeChat Campaign Banner',
    assetType: 'IMAGE',
    mimeType: 'image/jpeg',
    sizeBytes: 102400,
    url: 'https://placehold.co/900x500/07C160/ffffff?text=WeChat+Campaign',
    thumbnailUrl: 'https://placehold.co/180x100/07C160/ffffff?text=WeChat+Campaign',
    altText: 'WeChat Jade upgrade campaign banner',
    tags: ['wechat', 'campaign', 'jade'],
    marketId: 'HK', bizLineId: 'WEALTH',
    uploadedBy: 'j.chan@hsbc.com.hk', uploadedByName: 'Janet Chan',
    uploadedAt: '2026-05-05T00:00:00Z',
    status: 'ACTIVE',
  },
  {
    assetId: 'asset-008',
    name: 'FX Viewpoint — EUR & GBP Market Insights (May 2026)',
    assetType: 'VIDEO',
    mimeType: 'video/mp4',
    sizeBytes: 52428800,
    url: 'http://localhost:4000/media/fx-viewpoint.mov',
    thumbnailUrl: 'https://placehold.co/1280x720/003366/ffffff?text=FX+Viewpoint+EUR+%26+GBP',
    altText: 'HSBC FX Viewpoint: EUR and GBP — ECB on hold and BoE cut rates. Presented by Jackie Wong.',
    tags: ['fx', 'viewpoint', 'eur', 'gbp', 'market-insight', 'wealth'],
    marketId: 'HK', bizLineId: 'WEALTH',
    uploadedBy: 'j.chan@hsbc.com.hk', uploadedByName: 'Janet Chan',
    uploadedAt: '2026-05-05T00:00:00Z',
    status: 'ACTIVE',
    durationSeconds: 120,
    presenter: 'Jackie Wong',
    presenterTitle: 'FX Strategist, HSBC Global Research',
  },
  {
    assetId: 'asset-009',
    name: 'Deposit Campaign Hero Banner',
    assetType: 'IMAGE',
    mimeType: 'image/jpeg',
    sizeBytes: 312000,
    url: '/media/deposit-campaign-banner.jpg',
    thumbnailUrl: '/media/deposit-campaign-banner.jpg',
    altText: 'Father and child looking out over mountains and lake — Renminbi Savings new fund deposit campaign',
    tags: ['deposit', 'campaign', 'savings', 'renminbi', 'banner'],
    marketId: 'CN', bizLineId: 'WEALTH',
    uploadedBy: 'j.chan@hsbc.com.hk', uploadedByName: 'Janet Chan',
    uploadedAt: '2026-05-05T00:00:00Z',
    status: 'ACTIVE',
  },
];
