import type { SliceType } from '../types/ocdp';

export interface PaletteComponent {
  sliceType:    SliceType;
  label:        string;
  icon:         string;
  category:     string;
  description:  string;
  singleton?:   boolean;
  minHeight:    number;
  configurable: string[];
}

export const PALETTE_COMPONENTS: PaletteComponent[] = [
  {
    sliceType: 'HOME_SEARCH_HEADER',
    label: 'Home Search Header (All Segments)',
    icon: '🏠🔍',
    category: 'navigation',
    description: 'Segment-adaptive top header (red/jade/orange/silver) with integrated AI semantic search bar — replaces separate header + search bar slices',
    singleton: true,
    minHeight: 104,
    configurable: ['premierLabel', 'premierBg', 'eliteLabel', 'eliteBg', 'advanceLabel', 'advanceBg', 'massLabel', 'massBg', 'enableNotification', 'enableHeadset', 'placeholder', 'enableSemanticSearch', 'searchApiEndpoint'],
  },
  {
    sliceType: 'HEADER_NAV',
    label: 'Header Navigation',
    icon: '🔝',
    category: 'navigation',
    description: 'Top bar with search, notification bell, QR scanner',
    singleton: true,
    minHeight: 60,
    configurable: ['title', 'searchPlaceholder', 'showNotificationBell', 'showQRScanner'],
  },
  {
    sliceType: 'COMBO_QUICK_ACCESS',
    label: 'Quick Access + Tab Bar (Combo)',
    icon: '⚡',
    category: 'navigation',
    description: 'Combined single card: content tab bar (My pick/Invest/Global/HK Daily) + two 5-icon quick-access rows',
    singleton: true,
    minHeight: 130,
    configurable: ['tabs', 'row1Items', 'row2Items'],
  },
  {
    sliceType: 'QUICK_ACCESS',
    label: 'Quick Access Buttons',
    icon: '⚡',
    category: 'function',
    description: 'Row of primary product shortcuts (e.g. 朝朝宝, 借钱, 转账)',
    singleton: true,
    minHeight: 80,
    configurable: ['items'],
  },
  {
    sliceType: 'FUNCTION_GRID',
    label: 'Function Grid',
    icon: '⊞',
    category: 'function',
    description: 'Grid of function entry points with configurable columns, rows and labels',
    minHeight: 80,
    configurable: ['gridColumns', 'maxRows', 'showLabels', 'rows'],
  },
  {
    sliceType: 'AI_ASSISTANT',
    label: 'AI Assistant Entry',
    icon: '🤖',
    category: 'function',
    description: 'Intelligent wealth assistant greeting bar',
    minHeight: 44,
    configurable: ['greeting'],
  },
  {
    sliceType: 'CARD_ACTIVATION_BANNER',
    label: 'Card Activation Banner',
    icon: '🔔',
    category: 'promotion',
    description: 'Dismissible notification prompting the customer to activate their card',
    minHeight: 44,
    configurable: ['message', 'deepLink'],
  },
  {
    sliceType: 'QUEST_BANNER',
    label: 'Quest / Getting Started Banner',
    icon: '🎯',
    category: 'promotion',
    description: 'Getting-started quest progress card with HSBC hexagon icon and red left border',
    minHeight: 80,
    configurable: ['title', 'description', 'ctaLabel', 'ctaDeepLink', 'totalQuests'],
  },
  {
    sliceType: 'FEATURE_PRODUCT',
    label: 'Feature Product (Fund List)',
    icon: '📊',
    category: 'wealth',
    description: 'Pill-button fund list showing 1Y returns with configurable filter URLs',
    minHeight: 200,
    configurable: ['sectionTitle', 'buttons', 'activeButtonId', 'funds', 'moreLabel', 'moreDeepLink', 'bestSellingUrl'],
  },
  {
    sliceType: 'WEALTH_STUDIO_CAROUSEL',
    label: 'Wealth Studio Carousel',
    icon: '🎬',
    category: 'wealth',
    description: 'Premier Elite Wealth Studio horizontal video episode carousel',
    minHeight: 160,
    configurable: ['sectionTitle', 'items', 'moreLabel', 'moreDeepLink'],
  },
  {
    sliceType: 'GUIDES_INSIGHTS_CAROUSEL',
    label: 'Guides & Insights',
    icon: '📰',
    category: 'insight',
    description: 'Article card carousel — investment guides and market insights',
    minHeight: 160,
    configurable: ['sectionTitle', 'items', 'moreLabel', 'moreDeepLink'],
  },
  {
    sliceType: 'FX_WATCHLIST',
    label: 'FX Watchlist',
    icon: '💱',
    category: 'wealth',
    description: 'Currency pair watchlist with Gold Forex Club tier badge and live rates',
    minHeight: 200,
    configurable: ['sectionTitle', 'tierBadge', 'tierDescription', 'pairs', 'moreLabel', 'moreDeepLink'],
  },
  {
    sliceType: 'DISCOVER_MORE_CAROUSEL',
    label: 'Discover More',
    icon: '🔎',
    category: 'promotion',
    description: 'Horizontal campaign card carousel — product promotions and lifestyle offers',
    minHeight: 160,
    configurable: ['sectionTitle', 'items'],
  },
  {
    sliceType: 'PROMO_BANNER',
    label: 'Promo Banner',
    icon: '🎪',
    category: 'promotion',
    description: 'Full-width campaign banner with image, title, CTA',
    minHeight: 120,
    configurable: ['title', 'subtitle', 'ctaLabel', 'ctaDeepLink', 'imageUrl', 'backgroundColor'],
  },
  {
    sliceType: 'WEALTH_SELECTION',
    label: 'Wealth Selection',
    icon: '💰',
    category: 'wealth',
    description: 'Featured wealth products (7-day yield, risk level)',
    minHeight: 280,
    configurable: ['sectionTitle', 'products', 'moreDeepLink'],
  },
  {
    sliceType: 'SPACER',
    label: 'Spacer',
    icon: '↕️',
    category: 'layout',
    description: 'Vertical spacing element',
    minHeight: 16,
    configurable: ['height'],
  },
  {
    sliceType: 'VIDEO_PLAYER',
    label: 'Video Player',
    icon: '🎬',
    category: 'insight',
    description: 'Inline video player linked to a UCP content asset (video)',
    minHeight: 180,
    configurable: ['ucpAssetId', 'title', 'presenterName', 'presenterTitle', 'autoplay', 'showCaption'],
  },
  {
    sliceType: 'MARKET_BRIEFING_TEXT',
    label: 'Market Briefing Text',
    icon: '📋',
    category: 'insight',
    description: 'Bullet-point market briefing text sourced from a UCP content entry',
    minHeight: 200,
    configurable: ['ucpContentId', 'sectionTitle', 'bulletPoints', 'disclaimer'],
  },
  {
    sliceType: 'CONTACT_RM_CTA',
    label: 'Contact Your RM',
    icon: '📞',
    category: 'insight',
    description: 'Sticky full-width CTA routing customer to Relationship Manager finder',
    singleton: true,
    minHeight: 56,
    configurable: ['label', 'subLabel', 'deepLink', 'backgroundColor', 'textColor', 'sticky'],
  },
  {
    sliceType: 'DEPOSIT_RATE_TABLE',
    label: 'Deposit Rate Table',
    icon: '🏦',
    category: 'wealth',
    description: 'Time deposit interest rate table — term and rate columns only',
    minHeight: 220,
    configurable: ['sectionTitle', 'asAtDate', 'rates', 'footnote'],
  },
  {
    sliceType: 'DEPOSIT_OPEN_CTA',
    label: 'Button CTA',
    icon: '🏧',
    category: 'wealth',
    description: 'Full-width "Open a Deposit" CTA button for deposit campaigns',
    minHeight: 56,
    configurable: ['label', 'deepLink', 'backgroundColor', 'textColor'],
  },
  {
    sliceType: 'DEPOSIT_FAQ',
    label: 'General FAQ',
    icon: '❓',
    category: 'wealth',
    description: 'Collapsible FAQ accordion for deposit products — question/answer pairs',
    minHeight: 200,
    configurable: ['sectionTitle', 'items'],
  },
  // ── Campaign components ─────────────────────────────────────────────────────
  {
    sliceType: 'CAMPAIGN_HERO',
    label: 'Campaign Hero',
    icon: '🎯',
    category: 'promotion',
    description: 'Full-width hero banner with headline, sub-copy, badge and background gradient — for campaign pages',
    singleton: true,
    minHeight: 200,
    configurable: ['headline', 'subHeadline', 'badge', 'bgGradient', 'accentColor', 'imageUrl'],
  },
  {
    sliceType: 'CAMPAIGN_BENEFITS',
    label: 'Campaign Benefits',
    icon: '✅',
    category: 'promotion',
    description: 'Icon + text benefit grid for campaign pages — up to 6 benefit items',
    minHeight: 160,
    configurable: ['sectionTitle', 'items', 'columns'],
  },
  {
    sliceType: 'CAMPAIGN_CTA',
    label: 'Campaign CTA',
    icon: '🚀',
    category: 'promotion',
    description: 'Primary CTA button block with optional secondary link — for campaign pages',
    singleton: true,
    minHeight: 100,
    configurable: ['primaryLabel', 'primaryUrl', 'subNote', 'secondaryLabel', 'secondaryUrl'],
  },
  // ── Notification / engagement ───────────────────────────────────────────────
  {
    sliceType: 'AD_BANNER',
    label: 'Ad Banner',
    icon: '📢',
    category: 'promotion',
    description: 'Dismissible promotional notification banner with title, subtitle and optional icon',
    minHeight: 44,
    configurable: ['title', 'subtitle', 'dismissible', 'backgroundColor'],
  },
  {
    sliceType: 'FLASH_LOAN',
    label: 'Flash Loan',
    icon: '⚡💳',
    category: 'function',
    description: 'Prominent flash loan entry card with limit, rate and apply CTA',
    singleton: true,
    minHeight: 64,
    configurable: ['productName', 'maxAmount', 'currency', 'interestRate', 'ctaLabel', 'deepLink'],
  },
  {
    sliceType: 'FEATURED_RANKINGS',
    label: 'Featured Rankings',
    icon: '🏆',
    category: 'wealth',
    description: 'Numbered ranking list of top-performing investment products',
    minHeight: 120,
    configurable: ['sectionTitle', 'items', 'moreDeepLink'],
  },
  {
    sliceType: 'LIFE_DEALS',
    label: 'Life Deals',
    icon: '🛍️',
    category: 'lifestyle',
    description: 'Lifestyle merchant deals — brand logo grid with offers',
    minHeight: 120,
    configurable: ['sectionTitle', 'items', 'moreDeepLink'],
  },
  // ── Segment-specific headers ────────────────────────────────────────────────
  {
    sliceType: 'PREMIER_HEADER',
    label: 'Premier Header',
    icon: '🔴',
    category: 'navigation',
    description: 'HSBC Premier top header bar (red)',
    singleton: true,
    minHeight: 52,
    configurable: ['brandLabel', 'enableNotification', 'enableHeadset'],
  },
  {
    sliceType: 'ELITE_HEADER',
    label: 'Elite (Jade) Header',
    icon: '💚',
    category: 'navigation',
    description: 'HSBC Jade Elite top header bar (jade green)',
    singleton: true,
    minHeight: 52,
    configurable: ['brandLabel', 'enableNotification', 'enableHeadset'],
  },
  {
    sliceType: 'ADVANCE_HEADER',
    label: 'Advance Header',
    icon: '🟠',
    category: 'navigation',
    description: 'HSBC One Advance top header bar (orange)',
    singleton: true,
    minHeight: 52,
    configurable: ['brandLabel', 'enableNotification', 'enableHeadset'],
  },
  {
    sliceType: 'MASS_HEADER',
    label: 'Personal Banking Header',
    icon: '⚫',
    category: 'navigation',
    description: 'HSBC Personal Banking top header bar (grey/silver)',
    singleton: true,
    minHeight: 52,
    configurable: ['brandLabel', 'enableNotification', 'enableHeadset'],
  },
  {
    sliceType: 'HOME_SEARCH_BAR',
    label: 'Search Bar',
    icon: '🔍',
    category: 'navigation',
    description: 'White pill search bar with optional QR scan, AI semantic search, chatbot and inbox icons',
    singleton: true,
    minHeight: 44,
    configurable: ['placeholder', 'enableQRScan', 'enableSemanticSearch', 'enableChatbot', 'enableMessageInbox'],
  },
  {
    sliceType: 'CONTENT_TAB_BAR',
    label: 'Content Tab Bar',
    icon: '🗂️',
    category: 'navigation',
    description: 'Horizontal pill tab switcher (e.g. My pick / Invest / Global / HK Daily)',
    singleton: true,
    minHeight: 40,
    configurable: ['tabs', 'activeTab'],
  },
  {
    sliceType: 'QUICK_ACCESS_GRID',
    label: 'Quick Access Grid (Row)',
    icon: '⚡',
    category: 'function',
    description: '5-icon quick-access row — use two instances for double-row layouts',
    minHeight: 64,
    configurable: ['items'],
  },
];
export const PALETTE_CATEGORIES = [
  { id: 'navigation', label: 'Navigation', icon: '🔝' },
  { id: 'promotion',  label: 'Promotions', icon: '🎪' },
  { id: 'function',   label: 'Functions',  icon: '⚡' },
  { id: 'wealth',     label: 'Wealth',     icon: '💰' },
  { id: 'lifestyle',  label: 'Lifestyle',  icon: '🛍️' },
  { id: 'layout',     label: 'Layout',     icon: '📐' },
  { id: 'insight',    label: 'Insight',    icon: '📈' },
];
