import type { SliceType } from '../types/ocdp';

export interface PaletteComponent {
  sliceType:    SliceType;
  label:        string;
  icon:         string;
  category:     string;
  description:  string;
  singleton?:   boolean;
  minHeight:    number;
  configurable: string[];
}

export const PALETTE_COMPONENTS: PaletteComponent[] = [
  {
    sliceType: 'HEADER_NAV',
    label: 'Header Navigation',
    icon: '🔝',
    category: 'navigation',
    description: 'Top bar with search, notification bell, QR scanner',
    singleton: true,
    minHeight: 60,
    configurable: ['title', 'searchPlaceholder', 'showNotificationBell', 'showQRScanner'],
  },
  {
    sliceType: 'AI_SEARCH_BAR',
    label: 'AI Search Bar',
    icon: '🔍',
    category: 'navigation',
    description: 'HSBC red semantic search bar with QR scan, chatbot and message entry',
    singleton: true,
    minHeight: 44,
    configurable: ['placeholder', 'enableSemanticSearch', 'enableQRScan', 'enableChatbot', 'enableMessageInbox', 'searchApiEndpoint'],
  },
  {
    sliceType: 'QUICK_ACCESS',
    label: 'Quick Access Buttons',
    icon: '⚡',
    category: 'function',
    description: 'Row of primary product shortcuts',
    singleton: true,
    minHeight: 80,
    configurable: ['items'],
  },
  {
    sliceType: 'PROMO_BANNER',
    label: 'Promo Banner',
    icon: '🎪',
    category: 'promotion',
    description: 'Full-width campaign banner with image, title, CTA',
    minHeight: 120,
    configurable: ['title', 'subtitle', 'ctaLabel', 'ctaDeepLink', 'imageUrl', 'backgroundColor'],
  },
  {
    sliceType: 'FUNCTION_GRID',
    label: 'Function Grid',
    icon: '🔲',
    category: 'function',
    description: 'Icon grid of banking functions',
    singleton: true,
    minHeight: 140,
    configurable: ['rows'],
  },
  {
    sliceType: 'AI_ASSISTANT',
    label: 'AI Assistant Entry',
    icon: '🤖',
    category: 'function',
    description: 'Intelligent wealth assistant greeting bar',
    minHeight: 44,
    configurable: ['greeting'],
  },
  {
    sliceType: 'AD_BANNER',
    label: 'Advertisement Banner',
    icon: '📢',
    category: 'promotion',
    description: 'Dismissible promotional banner with image swap support',
    minHeight: 90,
    configurable: ['title', 'subtitle', 'ctaLabel', 'imageUrl', 'dismissible'],
  },
  {
    sliceType: 'FLASH_LOAN',
    label: 'Flash Loan Card',
    icon: '⚡💳',
    category: 'wealth',
    description: 'Instant loan product card with maximum amount display',
    minHeight: 80,
    configurable: ['productName', 'tagline', 'maxAmount', 'currency', 'ctaLabel'],
  },
  {
    sliceType: 'WEALTH_SELECTION',
    label: 'Wealth Selection',
    icon: '💰',
    category: 'wealth',
    description: 'Featured wealth products (7-day yield, risk level)',
    minHeight: 280,
    configurable: ['sectionTitle', 'products', 'moreDeepLink'],
  },
  {
    sliceType: 'FEATURED_RANKINGS',
    label: 'Featured Rankings',
    icon: '🏆',
    category: 'wealth',
    description: 'Top-performing funds and product rankings',
    minHeight: 180,
    configurable: ['sectionTitle', 'items', 'moreDeepLink'],
  },
  {
    sliceType: 'LIFE_DEALS',
    label: 'Life Deals',
    icon: '🛍️',
    category: 'lifestyle',
    description: 'Lifestyle merchant offers',
    minHeight: 200,
    configurable: ['sectionTitle', 'deals', 'moreDeepLink'],
  },
  {
    sliceType: 'SPACER',
    label: 'Spacer',
    icon: '↕️',
    category: 'layout',
    description: 'Vertical spacing element',
    minHeight: 16,
    configurable: ['height'],
  },
  {
    sliceType: 'VIDEO_PLAYER',
    label: 'Video Player',
    icon: '🎬',
    category: 'insight',
    description: 'Inline video player linked to a UCP content asset (video)',
    minHeight: 180,
    configurable: ['ucpAssetId', 'title', 'presenterName', 'presenterTitle', 'autoplay', 'showCaption'],
  },
  {
    sliceType: 'MARKET_BRIEFING_TEXT',
    label: 'Market Briefing Text',
    icon: '📋',
    category: 'insight',
    description: 'Bullet-point market briefing text sourced from a UCP content entry',
    minHeight: 200,
    configurable: ['ucpContentId', 'sectionTitle', 'bulletPoints', 'disclaimer'],
  },
  {
    sliceType: 'CONTACT_RM_CTA',
    label: 'Contact Your RM',
    icon: '📞',
    category: 'insight',
    description: 'Sticky full-width CTA routing customer to Relationship Manager finder',
    singleton: true,
    minHeight: 56,
    configurable: ['label', 'subLabel', 'deepLink', 'backgroundColor', 'textColor', 'sticky'],
  },
  {
    sliceType: 'DEPOSIT_RATE_TABLE',
    label: 'Deposit Rate Table',
    icon: '🏦',
    category: 'wealth',
    description: 'Time deposit interest rate table — term and rate columns only',
    minHeight: 220,
    configurable: ['sectionTitle', 'asAtDate', 'rates', 'footnote'],
  },
  {
    sliceType: 'DEPOSIT_OPEN_CTA',
    label: 'Button CTA',
    icon: '🏧',
    category: 'wealth',
    description: 'Full-width "Open a Deposit" CTA button for deposit campaigns',
    minHeight: 56,
    configurable: ['label', 'deepLink', 'backgroundColor', 'textColor'],
  },
  {
    sliceType: 'DEPOSIT_FAQ',
    label: 'General FAQ',
    icon: '❓',
    category: 'wealth',
    description: 'Collapsible FAQ accordion for deposit products — question/answer pairs',
    minHeight: 200,
    configurable: ['sectionTitle', 'items'],
  },
];

export const PALETTE_CATEGORIES = [
  { id: 'navigation', label: 'Navigation', icon: '🔝' },
  { id: 'promotion',  label: 'Promotions', icon: '🎪' },
  { id: 'function',   label: 'Functions',  icon: '⚡' },
  { id: 'wealth',     label: 'Wealth',     icon: '💰' },
  { id: 'lifestyle',  label: 'Lifestyle',  icon: '🛍️' },
  { id: 'layout',     label: 'Layout',     icon: '📐' },
  { id: 'insight',    label: 'Insight',    icon: '📈' },
];
